-- ─────────────────────────────────────────────────────────────
-- Migration 002: Platform Admins
--
-- Adds a second tier of authenticated users — Clear30 platform
-- admins — who can log in and access any school's full portal.
-- ─────────────────────────────────────────────────────────────

BEGIN;

-- ─────────────────────────────────────────────────────────────
-- 1. platform_admins table
-- ─────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS schools.platform_admins (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  auth_id    uuid UNIQUE REFERENCES auth.users(id) ON DELETE SET NULL,
  email      text NOT NULL UNIQUE,
  name       text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE schools.platform_admins ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "deny_direct_access" ON schools.platform_admins;
CREATE POLICY "deny_direct_access" ON schools.platform_admins FOR ALL USING (false);


-- ─────────────────────────────────────────────────────────────
-- 2. is_platform_admin() helper function
-- ─────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION schools.is_platform_admin()
RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
STABLE
SET search_path = schools, public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM schools.platform_admins WHERE auth_id = auth.uid()
  )
$$;


-- ─────────────────────────────────────────────────────────────
-- 3. Update RLS policies to also allow platform admins
-- ─────────────────────────────────────────────────────────────

-- ── schools.schools ──────────────────────────────────────────
DROP POLICY IF EXISTS "portal_users_select_own_school" ON schools.schools;
CREATE POLICY "portal_users_select_own_school"
  ON schools.schools FOR SELECT
  USING (school_id = schools.get_portal_school_id() OR schools.is_platform_admin());

DROP POLICY IF EXISTS "portal_admins_update_own_school" ON schools.schools;
CREATE POLICY "portal_admins_update_own_school"
  ON schools.schools FOR UPDATE
  USING  ((school_id = schools.get_portal_school_id() AND schools.is_portal_admin()) OR schools.is_platform_admin())
  WITH CHECK ((school_id = schools.get_portal_school_id() AND schools.is_portal_admin()) OR schools.is_platform_admin());


-- ── schools.portal_users ──────────────────────────────────────
DROP POLICY IF EXISTS "portal_users_select_own_school_members" ON schools.portal_users;
CREATE POLICY "portal_users_select_own_school_members"
  ON schools.portal_users FOR SELECT
  USING (school_id = schools.get_portal_school_id() OR schools.is_platform_admin());

DROP POLICY IF EXISTS "portal_admins_insert_members" ON schools.portal_users;
CREATE POLICY "portal_admins_insert_members"
  ON schools.portal_users FOR INSERT
  WITH CHECK (
    (school_id = schools.get_portal_school_id() AND schools.is_portal_admin())
    OR schools.is_platform_admin()
  );

DROP POLICY IF EXISTS "portal_users_update_members" ON schools.portal_users;
CREATE POLICY "portal_users_update_members"
  ON schools.portal_users FOR UPDATE
  USING (
    (school_id = schools.get_portal_school_id() AND (schools.is_portal_admin() OR auth_id = auth.uid()))
    OR schools.is_platform_admin()
  )
  WITH CHECK (
    (school_id = schools.get_portal_school_id() AND (schools.is_portal_admin() OR auth_id = auth.uid()))
    OR schools.is_platform_admin()
  );

DROP POLICY IF EXISTS "portal_admins_delete_members" ON schools.portal_users;
CREATE POLICY "portal_admins_delete_members"
  ON schools.portal_users FOR DELETE
  USING (
    (school_id = schools.get_portal_school_id() AND schools.is_portal_admin() AND auth_id IS DISTINCT FROM auth.uid())
    OR schools.is_platform_admin()
  );


-- ── schools.school_messages ───────────────────────────────────
DROP POLICY IF EXISTS "portal_users_select_messages" ON schools.school_messages;
CREATE POLICY "portal_users_select_messages"
  ON schools.school_messages FOR SELECT
  USING (school_id = schools.get_portal_school_id() OR schools.is_platform_admin());

DROP POLICY IF EXISTS "portal_users_insert_messages" ON schools.school_messages;
CREATE POLICY "portal_users_insert_messages"
  ON schools.school_messages FOR INSERT
  WITH CHECK (school_id = schools.get_portal_school_id() OR schools.is_platform_admin());

DROP POLICY IF EXISTS "portal_users_update_messages" ON schools.school_messages;
CREATE POLICY "portal_users_update_messages"
  ON schools.school_messages FOR UPDATE
  USING  (school_id = schools.get_portal_school_id() OR schools.is_platform_admin())
  WITH CHECK (school_id = schools.get_portal_school_id() OR schools.is_platform_admin());

DROP POLICY IF EXISTS "portal_users_delete_messages" ON schools.school_messages;
CREATE POLICY "portal_users_delete_messages"
  ON schools.school_messages FOR DELETE
  USING (school_id = schools.get_portal_school_id() OR schools.is_platform_admin());


-- ── schools.school_activities ─────────────────────────────────
DROP POLICY IF EXISTS "portal_users_select_activities" ON schools.school_activities;
CREATE POLICY "portal_users_select_activities"
  ON schools.school_activities FOR SELECT
  USING (school_id = schools.get_portal_school_id() OR schools.is_platform_admin());

DROP POLICY IF EXISTS "portal_users_insert_activities" ON schools.school_activities;
CREATE POLICY "portal_users_insert_activities"
  ON schools.school_activities FOR INSERT
  WITH CHECK (school_id = schools.get_portal_school_id() OR schools.is_platform_admin());

DROP POLICY IF EXISTS "portal_users_update_activities" ON schools.school_activities;
CREATE POLICY "portal_users_update_activities"
  ON schools.school_activities FOR UPDATE
  USING  (school_id = schools.get_portal_school_id() OR schools.is_platform_admin())
  WITH CHECK (school_id = schools.get_portal_school_id() OR schools.is_platform_admin());

DROP POLICY IF EXISTS "portal_users_delete_activities" ON schools.school_activities;
CREATE POLICY "portal_users_delete_activities"
  ON schools.school_activities FOR DELETE
  USING (school_id = schools.get_portal_school_id() OR schools.is_platform_admin());


-- ── schools.school_resources ──────────────────────────────────
DROP POLICY IF EXISTS "portal_users_select_resources" ON schools.school_resources;
CREATE POLICY "portal_users_select_resources"
  ON schools.school_resources FOR SELECT
  USING (school_id = schools.get_portal_school_id() OR schools.is_platform_admin());

DROP POLICY IF EXISTS "portal_users_insert_resources" ON schools.school_resources;
CREATE POLICY "portal_users_insert_resources"
  ON schools.school_resources FOR INSERT
  WITH CHECK (school_id = schools.get_portal_school_id() OR schools.is_platform_admin());

DROP POLICY IF EXISTS "portal_users_update_resources" ON schools.school_resources;
CREATE POLICY "portal_users_update_resources"
  ON schools.school_resources FOR UPDATE
  USING  (school_id = schools.get_portal_school_id() OR schools.is_platform_admin())
  WITH CHECK (school_id = schools.get_portal_school_id() OR schools.is_platform_admin());

DROP POLICY IF EXISTS "portal_users_delete_resources" ON schools.school_resources;
CREATE POLICY "portal_users_delete_resources"
  ON schools.school_resources FOR DELETE
  USING (school_id = schools.get_portal_school_id() OR schools.is_platform_admin());


-- ── schools.tracking_link_clicks ─────────────────────────────
DROP POLICY IF EXISTS "portal_users_select_clicks" ON schools.tracking_link_clicks;
CREATE POLICY "portal_users_select_clicks"
  ON schools.tracking_link_clicks FOR SELECT
  USING (school_id = schools.get_portal_school_id() OR schools.is_platform_admin());


-- ── schools.portal_reports ────────────────────────────────────
DROP POLICY IF EXISTS "portal_users_select_reports" ON schools.portal_reports;
CREATE POLICY "portal_users_select_reports"
  ON schools.portal_reports FOR SELECT
  USING (school_id = schools.get_portal_school_id() OR schools.is_platform_admin());

DROP POLICY IF EXISTS "portal_users_insert_reports" ON schools.portal_reports;
CREATE POLICY "portal_users_insert_reports"
  ON schools.portal_reports FOR INSERT
  WITH CHECK (school_id = schools.get_portal_school_id() OR schools.is_platform_admin());


-- ─────────────────────────────────────────────────────────────
-- 4. Update analytics RPCs to allow platform admins
-- ─────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION schools.get_school_analytics(p_school_id text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
STABLE
SET search_path = schools, public, payment
AS $$
BEGIN
  IF schools.get_portal_school_id() IS DISTINCT FROM p_school_id AND NOT schools.is_platform_admin() THEN
    RAISE EXCEPTION 'Access denied: not a portal user for school %', p_school_id;
  END IF;

  RETURN (
    WITH school_users AS (
      SELECT u.id, u.created_at, u.day_info
      FROM public.users u
      JOIN payment.domain_allowlist dal
        ON u.email ILIKE ('%@' || dal.domain)
      WHERE dal.school_id = p_school_id
        AND u.day_info IS NOT NULL
        AND jsonb_array_length(u.day_info) > 0
    ),
    checkin_stats AS (
      SELECT
        su.id,
        su.created_at,
        COUNT(*) FILTER (
          WHERE jsonb_typeof(elem) = 'object'
        ) AS total_checkins,
        COUNT(*) FILTER (
          WHERE jsonb_typeof(elem) = 'object'
            AND (elem->>'sober')::boolean = true
        ) AS sober_days,
        MAX(
          CASE WHEN jsonb_typeof(elem) = 'string'
            THEN (elem #>> '{}')::date
            ELSE NULL
          END
        ) AS last_checkin_date
      FROM school_users su,
        jsonb_array_elements(su.day_info) AS elem
      GROUP BY su.id, su.created_at
    )
    SELECT jsonb_build_object(
      'total_students',   COUNT(*),
      'total_checkins',   COALESCE(SUM(total_checkins), 0),
      'total_sober_days', COALESCE(SUM(sober_days), 0),
      'active_last_30d',  COUNT(*) FILTER (
                            WHERE last_checkin_date >= CURRENT_DATE - INTERVAL '30 days'
                          )
    )
    FROM checkin_stats
  );
END;
$$;


CREATE OR REPLACE FUNCTION schools.get_school_enrollment_trend(
  p_school_id text,
  p_interval  text DEFAULT 'weekly'
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
STABLE
SET search_path = schools, public, payment
AS $$
BEGIN
  IF schools.get_portal_school_id() IS DISTINCT FROM p_school_id AND NOT schools.is_platform_admin() THEN
    RAISE EXCEPTION 'Access denied: not a portal user for school %', p_school_id;
  END IF;

  IF p_interval = 'monthly' THEN
    RETURN (
      SELECT COALESCE(jsonb_agg(row ORDER BY bucket), '[]'::jsonb)
      FROM (
        SELECT
          date_trunc('month', u.created_at) AS bucket,
          jsonb_build_object(
            'label',    to_char(date_trunc('month', u.created_at), 'Mon YYYY'),
            'students', COUNT(*)
          ) AS row
        FROM public.users u
        JOIN payment.domain_allowlist dal ON u.email ILIKE ('%@' || dal.domain)
        WHERE dal.school_id = p_school_id
        GROUP BY 1
      ) t
    );
  ELSE
    RETURN (
      SELECT COALESCE(jsonb_agg(row ORDER BY bucket), '[]'::jsonb)
      FROM (
        SELECT
          date_trunc('week', u.created_at) AS bucket,
          jsonb_build_object(
            'label',    to_char(date_trunc('week', u.created_at), 'MM/DD'),
            'students', COUNT(*)
          ) AS row
        FROM public.users u
        JOIN payment.domain_allowlist dal ON u.email ILIKE ('%@' || dal.domain)
        WHERE dal.school_id = p_school_id
        GROUP BY 1
      ) t
    );
  END IF;
END;
$$;


CREATE OR REPLACE FUNCTION schools.get_school_checkin_trend(
  p_school_id text,
  p_interval  text DEFAULT 'weekly'
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
STABLE
SET search_path = schools, public, payment
AS $$
BEGIN
  IF schools.get_portal_school_id() IS DISTINCT FROM p_school_id AND NOT schools.is_platform_admin() THEN
    RAISE EXCEPTION 'Access denied: not a portal user for school %', p_school_id;
  END IF;

  IF p_interval = 'monthly' THEN
    RETURN (
      WITH school_users AS (
        SELECT u.id, u.day_info
        FROM public.users u
        JOIN payment.domain_allowlist dal ON u.email ILIKE ('%@' || dal.domain)
        WHERE dal.school_id = p_school_id
          AND u.day_info IS NOT NULL
          AND jsonb_array_length(u.day_info) > 0
      ),
      indexed AS (
        SELECT
          su.id,
          elem,
          jsonb_typeof(elem)                                         AS elem_type,
          LAG(elem) OVER (PARTITION BY su.id ORDER BY idx)          AS prev_elem
        FROM school_users su,
          jsonb_array_elements(su.day_info) WITH ORDINALITY AS t(elem, idx)
      ),
      pairs AS (
        SELECT
          (prev_elem #>> '{}')::date   AS checkin_date,
          (elem->>'sober')::boolean    AS sober
        FROM indexed
        WHERE elem_type = 'object' AND prev_elem IS NOT NULL
      )
      SELECT COALESCE(jsonb_agg(row ORDER BY bucket), '[]'::jsonb)
      FROM (
        SELECT
          date_trunc('month', checkin_date) AS bucket,
          jsonb_build_object(
            'label',     to_char(date_trunc('month', checkin_date), 'Mon YYYY'),
            'checkIns',  COUNT(*),
            'soberDays', COUNT(*) FILTER (WHERE sober = true)
          ) AS row
        FROM pairs
        WHERE checkin_date IS NOT NULL
        GROUP BY 1
      ) t
    );
  ELSE
    RETURN (
      WITH school_users AS (
        SELECT u.id, u.day_info
        FROM public.users u
        JOIN payment.domain_allowlist dal ON u.email ILIKE ('%@' || dal.domain)
        WHERE dal.school_id = p_school_id
          AND u.day_info IS NOT NULL
          AND jsonb_array_length(u.day_info) > 0
      ),
      indexed AS (
        SELECT
          su.id,
          elem,
          jsonb_typeof(elem)                                         AS elem_type,
          LAG(elem) OVER (PARTITION BY su.id ORDER BY idx)          AS prev_elem
        FROM school_users su,
          jsonb_array_elements(su.day_info) WITH ORDINALITY AS t(elem, idx)
      ),
      pairs AS (
        SELECT
          (prev_elem #>> '{}')::date   AS checkin_date,
          (elem->>'sober')::boolean    AS sober
        FROM indexed
        WHERE elem_type = 'object' AND prev_elem IS NOT NULL
      )
      SELECT COALESCE(jsonb_agg(row ORDER BY bucket), '[]'::jsonb)
      FROM (
        SELECT
          date_trunc('week', checkin_date) AS bucket,
          jsonb_build_object(
            'label',     to_char(date_trunc('week', checkin_date), 'MM/DD'),
            'checkIns',  COUNT(*),
            'soberDays', COUNT(*) FILTER (WHERE sober = true)
          ) AS row
        FROM pairs
        WHERE checkin_date IS NOT NULL
        GROUP BY 1
      ) t
    );
  END IF;
END;
$$;


CREATE OR REPLACE FUNCTION schools.get_tracking_link_stats(p_school_id text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
STABLE
SET search_path = schools, public
AS $$
BEGIN
  IF schools.get_portal_school_id() IS DISTINCT FROM p_school_id AND NOT schools.is_platform_admin() THEN
    RAISE EXCEPTION 'Access denied: not a portal user for school %', p_school_id;
  END IF;

  RETURN (
    SELECT COALESCE(
      jsonb_object_agg(link_key, click_count),
      '{}'::jsonb
    )
    FROM (
      SELECT link_key, COUNT(*) AS click_count
      FROM schools.tracking_link_clicks
      WHERE school_id = p_school_id
      GROUP BY link_key
    ) t
  );
END;
$$;


-- ─────────────────────────────────────────────────────────────
-- 5. New RPC: get all schools (platform admins only)
-- ─────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION schools.get_all_schools_for_admin()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
STABLE
SET search_path = schools, public
AS $$
BEGIN
  IF NOT schools.is_platform_admin() THEN
    RETURN '[]'::jsonb;
  END IF;
  RETURN (
    SELECT COALESCE(
      jsonb_agg(row_to_json(s) ORDER BY s.short_name),
      '[]'::jsonb
    )
    FROM schools.schools s
  );
END;
$$;


COMMIT;


-- ─────────────────────────────────────────────────────────────
-- To seed your first platform admin:
--
--   1. Invite the user via Supabase Dashboard:
--      Authentication → Users → Invite User
--
--   2. INSERT the platform_admins row (replace UUID and details):
--
--      INSERT INTO schools.platform_admins (auth_id, email, name)
--      VALUES ('<uuid-from-auth.users>', 'you@clear30.com', 'Your Name');
-- ─────────────────────────────────────────────────────────────
