-- SQL UPDATE statements generated from CSV comparison
-- Table: programs.program_messages
-- Total changes: 30

UPDATE programs.program_messages SET resources = '{"🌌 How a space can improve (or destroy) your life":"https://www.youtube.com/watch?v=ikz3ECL5NEk","💪 ADVICE REMEMBER, YOUR ENVIRONMENT WILL ALWAYS BE STRONGER THAN YOUR WILLPOWER":"https://www.reddit.com/r/getdisciplined/comments/in1mqi/advice_remember_your_environment_will_always_be/"}' WHERE id = 339;
UPDATE programs.program_messages SET resources = '{"🌿 Weed cravings timeline":"https://www.reddit.com/r/trees/comments/83o5qw/i_havent_smoked_in_5_months_but_i_am_really/","🧘 Guided meditation to curb cravings":"https://www.youtube.com/watch?v=1B5YeONdRTk&t=151s","❓ When do weed cravings stop or at least let up?":"https://www.reddit.com/r/recovery/comments/z4arvf/when_do_weed_cravings_stop_or_at_least_let_up/","📘 A Pot-Positive Guide on How to Fight the Urge to Get High All the Time":"https://www.reddit.com/r/eldertrees/comments/i6jfqp/a_potpositive_guide_on_how_to_fight_the_urge_to/","🧠 How Dopamine Influences Cravings: Neuroscientists Explain (MedicalXpress)":"https://medicalxpress.com/news/2024-12-dopamine-neuroscientists.html"}' WHERE id = 353;
UPDATE programs.program_messages SET resources = '{"❓ [Question] How do I find my \"why\"?":"https://www.reddit.com/r/getdisciplined/comments/10c0ll7/question_how_do_i_find_my_why/","🌿 How do you quit weed when you can''t find a reason to?":"https://www.reddit.com/r/Healthygamergg/comments/1dd1a0w/how_do_you_quit_weed_when_you_cant_find_a_reason/","🎙️ Simon Sinek: How To Find Your ''Why?'' In 15 Minutes":"https://www.youtube.com/watch?v=1CuZyq6ckGE","🎯 Find your why: How to stay motivated and reach your goals":"https://www.hprc-online.org/mental-fitness/performance-psychology/find-your-why-how-stay-motivated-and-reach-your-goals","🔑 The Power of Knowing Your Why: How It Can Change Your Life":"https://medium.com/@francesco.saviano87/the-power-of-knowing-your-why-how-it-can-change-your-life-ab9166b8ae1b","💡 [Advice] If you struggle with staying motivated, read this.":"https://www.reddit.com/r/getdisciplined/comments/c6v0l1/advice_if_you_struggle_with_staying_motivated/"}' WHERE id = 367;
UPDATE programs.program_messages SET resources = '{"😣 Learning Acceptance":"https://www.youtube.com/watch?v=-tRwWPzQj9U","😣 Accepting Pain":"https://www.reddit.com/r/Stoicism/comments/mxfzt4/accepting_pain/","🤔 Does Embracing Discomfort Help or Hurt Your Life?":"https://www.psychologytoday.com/us/blog/the-new-resilience/202206/does-embracing-discomfort-help-or-hurt-your-life", "📽️ Get comfortable with being uncomfortable | Luvvie Ajayi Jones | TED":"https://www.youtube.com/watch?v=QijH4UAqGD8"}
' WHERE id = 475;
UPDATE programs.program_messages SET resources = '{"🏋️ Exercise and cravings":"https://www.youtube.com/watch?v=StM10jzbt1k&t=217s","🏋️ Replacing weed with exercise":"https://www.reddit.com/r/IWantToLearn/comments/hjukcj/iwtl_how_to_replace_smoking_weed_with_exercise/","💧Hydration matters, even if you don’t exercise":"https://www.youtube.com/watch?v=-pYY4IcXgHc","🏋️ Go work out":"https://www.reddit.com/r/leaves/comments/pvhdm6/go_work_out/","🏋️ Exercise will help":"https://www.reddit.com/r/leaves/comments/4mc6m1/if_youre_trying_to_quit_exercise_really_helps/","🏋️ Exercise can curb marijuana use and cravings":"https://news.vanderbilt.edu/2011/03/04/exercise-can-curb-marijuana-use-and-cravings/"}
' WHERE id = 389;
UPDATE programs.program_messages SET resources = '{"🤝 How does leaning on friends for support work?":"https://www.reddit.com/r/NoStupidQuestions/comments/1da1kyh/how_does_leaning_on_friends_for_support_work/","🌟 Lean On Your Friends. And Let Them Lean On You.":"https://roundglassliving.com/sunny/articles/lean-on-your-friends","💪 Those who don’t have much of a support system, how do you cope when life is rough?":"https://www.reddit.com/r/Adulting/comments/14yhd45/those_who_dont_have_much_of_a_support_system_how/","🗣️ How do you ask for help and emotional support from your family/friends in a healthy way that prevents you from becoming a burden to them?":"https://www.reddit.com/r/AskWomenOver30/comments/xld8v8/how_do_you_ask_for_help_and_emotional_support/"}' WHERE id = 395;
UPDATE programs.program_messages SET resources = '{"🎨 Hobbies that make everyday life sick":"https://youtu.be/XqMlgXCzgjE?si=8IMe-eVgSI9xUWn3","🚭 Things to do instead of smoking weed":"https://www.reddit.com/r/leaves/comments/jdy7b5/things_to_do_instead_of_smoking_weed/","🔄 More things to do instead of smoking weed":"https://www.reddit.com/r/leaves/comments/djhjw5/a_list_of_things_to_do_instead_of_smoking_weed/","🎯 The trick to a T-break is just distractions":"https://www.reddit.com/r/trees/comments/yh9g70/the_trick_to_a_tbreak_is_just_distraction/","🌿 Advice for distractions while taking a break from weed":"https://www.reddit.com/r/trees/comments/6xufrb/any_advice_how_to_distract_yourself_when_making_a/"}' WHERE id = 400;
UPDATE programs.program_messages SET resources = '{"🌟 The Transformative Power of Small Wins: Rethinking Progress and Potential":"https://mbbshrabdullah.medium.com/the-transformative-power-of-small-wins-rethinking-progress-and-potential-2903a3909292","💬 Discussion How a deep understanding of the ripple effect helped me get disciplined and take charge of my life, after years of procrastinating?":"https://www.reddit.com/r/getdisciplined/comments/es2tnk/discussion_how_a_deep_understanding_of_the_ripple/"}' WHERE id = 406;
UPDATE programs.program_messages SET resources = '{"😴 Bored without weed":"https://www.reddit.com/r/Petioles/comments/v7k1ae/bored_without_weed/","📝 21 Ways to Beat Boredom":"https://www.nationaldaycalendar.com/lists/21-ways-to-beat-boredbome","🔧 Boredom is Your Greatest Tool":"https://lewisflint.substack.com/p/boredom-is-your-greatest-tool","🗣️ Randy Marsh talk about marijuana":"https://youtu.be/Jd4cASkBAp0?si=z4Lcu0NIfPyRV1rk","🎨 Extremely bored in the evening without weed":"https://www.reddit.com/r/leaves/comments/ygi3nz/extremely_bored_in_the_evening_without_weed/","❓ Biggest trigger. What is boredom and why is it turned off with marijuana?":"https://www.reddit.com/r/leaves/comments/tdkwie/biggest_trigger_what_is_boredom_and_why_is_it/","🤔 Why You Feel Bored in Life // How to Overcome Boredom and Live a more exciting life":"https://www.youtube.com/watch?time_continue=1&v=i7rklh9Sxh8&embeds_referring_euri=https%3A%2F%2Fwww.google.com%2Fsearch%3Fq%3Dhow%2Bto%2Bbeat%2Bboredom%26oq%3Dhow%2Bto%2Bbeat+bboredom%mpsonid=UTF-8&source=Mjg6NjY"}' WHERE id = 424;
UPDATE programs.program_messages SET resources = '{"🔍 Become a long-term thinker":"https://www.youtube.com/watch?v=x0izoGt9BK8","🎯 How to focus on long term rewards":"https://www.reddit.com/r/PsychologicalTricks/comments/ej0ldy/pt_how_do_i_focus_on_long_term_rewards_rather/","🧠 Struggling with delaying gratification":"https://www.reddit.com/r/productivity/comments/nvd4u0/tips_for_those_who_suck_at_delaying_gratification/","🔑 Delaying gratification is the key to a happy life":"https://www.reddit.com/r/getdisciplined/comments/gs12al/advice_master_delayed_gratification_is_the_secret/"}' WHERE id = 431;
UPDATE programs.program_messages SET resources = '{"Cannabis and mental health overview": "https://www.youtube.com/watch?v=hXMQYFcjLG8&t=576s",
"🧬 Neuroscientist Explains how weed effects your brain": "https://www.youtube.com/watch?v=bMvOqntD0Yg",
"👶 Cannabis and mental health for children and young people": "https://jamanetwork.com/journals/jama-health-forum/fullarticle/2845356",
"🧠 Slow and stealth?": "https://www.pbs.org/video/high-riskthe-truth-about-weed-iaew5b/"}' WHERE id = 436;
UPDATE programs.program_messages SET resources = '{"🚬 Quitting while all your friends smoke":"","🌿 Don''t throw your “weed friends” away !":"","🤔 My Friends Smoke Weed, But I QUIT smoking (now what??)":"https://youtu.be/z0zOpVcGZHw?si=H3L964GB4LAZOQBi","🚭 Dealing with being the only one in a friend group who doesn''t smoke":""}' WHERE id = 445;
UPDATE programs.program_messages SET resources = '{"⚡ The Power of Positive Thinking":"https://youtu.be/M2tgKZLRq3s?si=SW4odfh67HsXKqrN","🌟 How to have a positive mindset":"https://www.reddit.com/r/IWantToLearn/comments/o708e4/iwtl_how_to_have_a_more_positive_mindset/","💪 Positive thinking for self improvement":"https://www.reddit.com/r/selfimprovement/comments/bj2qo4/can_small_positive_habits_and_positive_thinking/","😊 How To Start Thinking Only Positive Thoughts":"https://www.reddit.com/r/selfhelp/comments/elya94/how_to_start_thinking_only_positive_thoughts/","🔍 Enhance your life with applied positive psychology":"https://lpsonline.sas.upenn.edu/features/enhance-your-life-applied-positive-psychology"}' WHERE id = 449;
UPDATE programs.program_messages SET resources = '{"🔄 How To Reinvent Yourself":"https://youtu.be/s7MyoeyBjjY?si=oTsEWoCiulavVUDe","✨ Identity Shifting: The ONE thing that changed my life":"https://www.youtube.com/watch?v=SEGqHSXjCuo","🎯 Identity-Based Habits: How to Actually Stick to Your Goals This Year":"https://jamesclear.com/identity-based-habits","🔄 Identity Shifting: Your New Way to Reinvent Yourself (in 3-6 months)":"https://www.youtube.com/watch?v=hmDUePZNxGc","📖 Be Careful of the Story You Tell Yourself Because It Will Become Your Identity":"https://introvertdear.com/news/story-tell-yourself-identity/"}' WHERE id = 456;
UPDATE programs.program_messages SET resources = '{"🔄 Changing from a fixed mindset to a growth mindset.":"https://www.reddit.com/r/getdisciplined/comments/3efgvn/needadvice_changing_from_a_fixed_mindset_to_a/","📚 Carol Dweck: A Summary of Growth and Fixed Mindsets":"https://fs.blog/carol-dweck-mindset/","🧠 Adults that have ACTUALLY developed a growth mindset, how?":"https://www.reddit.com/r/getdisciplined/comments/14jkxho/method_adults_that_have_actually_developed_a/","📈 Dr. David Yeager: How to Master Growth Mindset to Improve Performance":"https://www.youtube.com/watch?v=etEJrznE-c0","🎥 How Your Thoughts Can Affect Your Life - Fixed Mindset VS Growth Mindset (Animated video)":"https://www.youtube.com/watch?v=GwLcOuSefqA"}' WHERE id = 462;
UPDATE programs.program_messages SET resources = '{"💪 Discipline Over Motivation":"https://youtu.be/ymhnN2SbQdc?si=uFeAS8_kq9Fnldi3","🔄 Lack of Consistency Comes from....":"https://www.reddit.com/r/getdisciplined/comments/d2qkbf/advice_your_lack_of_consistency_comes_from_your/","😞 Stopping for 3 months - lost motivation":"https://www.reddit.com/r/leaves/comments/19dy9f/stopped_smoking_weed_for_3_months_nowlost/","🚀 How to Stay Persistent with Sustained Motivation":"https://devoutly.org/journal/how-to-stay-persistent-with-sustained-motivation/","🔥 What keeps you guys motivated to stay on your T-break/stay sober?":"https://www.reddit.com/r/Petioles/comments/8p5apl/what_keeps_you_guys_motivated_to_stay_on_your/"}' WHERE id = 468;
UPDATE programs.program_messages SET resources = '{"🐒 Monkey Mind? Stop it!":"https://www.reddit.com/r/Meditation/comments/x6ag7r/monkey_mind_stop_it/","🐒 Monkey mind, what is it?":"https://www.reddit.com/r/Buddhism/comments/7xz16w/monkey_mind_what_is_it/","📜 The Buddhist Story of the Monkey Mind":"https://www.namchak.org/community/blog/the-buddhist-story-of-the-monkey-mind/","🧘 Training the Monkey Mind | Headspace | Meditation":"https://youtu.be/qxyVCjp48S4?si=ooV8KUcQzh95wRNJ","💡 Personification: What it is and Why it works. [Method]":"https://www.reddit.com/r/getdisciplined/comments/iehp3m/personification_what_it_is_and_why_it_works_method/","🧠 Understanding the Monkey Mind with Yongey Mingyur Rinpoche":"https://www.youtube.com/watch?v=t-JiQubfMPg","🤔 Is there anyway to calm the monkey mind? I''m really frustrated with overthinking":"https://www.reddit.com/r/Buddhism/comments/15olvts/is_there_anyway_to_calm_the_monkey_mind_im_really/","🚫 How to STOP Drinking, taking drugs, Alcohol - Your addictive voice - AVRT - Addiction technique":"https://www.youtube.com/watch?v=0CNM3MEmWRQ"}' WHERE id = 471;
UPDATE programs.program_messages SET resources = '{"📊 How To Use Your Money Wisely":"https://www.youtube.com/watch?v=wsT2bBo4XT8&t=19s","💵 Saving $200/month—now what?!":"https://www.reddit.com/r/leaves/comments/1k6s0ha/im_saving_200mo_by_not_smoking_weed_and_i_find_it/","🤔 What do normal people do with extra money?":"https://www.reddit.com/r/NoStupidQuestions/comments/1m2kgq0/what_do_normal_people_do_with_extra_money/","💰 How much money have you saved since you quit weed?":"https://www.reddit.com/r/leaves/comments/s7upgz/how_much_money_have_you_saved_since_you_quit_weed/"}' WHERE id = 537;
UPDATE programs.program_messages SET resources = '{"🌿 Mindfulness and Weed":"https://www.reddit.com/r/Mindfulness/comments/azit4w/mindfulness_and_weed/","🍃 Marijuana and Meditation":"https://www.youtube.com/watch?v=MtZmR6oK9tg&feature=youtu.be","🔍 How to Tackle Your Cravings with Mindfulness":"https://greatergood.berkeley.edu/article/item/how_to_tackle_your_cravings_with_mindfulness","🧘 Experiences on using meditation to stop smoking":"https://www.reddit.com/r/Meditation/comments/rplucw/have_you_experience_with_using_meditation_to_stop/","🧠 Turn Off Mental Cravings Using This Mindfulness Technique":"https://youtu.be/7Lkw6fEZ3IA?si=KrmrffP-4HfsXS6l","🧘 Have you experience with using meditation to stop smoking weed (or other substance)?":"https://www.reddit.com/r/Meditation/comments/rplucw/have_you_experience_with_using_meditation_to_stop/"}' WHERE id = 476;
UPDATE programs.program_messages SET resources = '{"💪 Deal Better with Hard Times":"https://www.mhanational.org/deal-better-hard-times","🌿 Weed addiction and coping with emotion":"https://www.reddit.com/r/infp/comments/195nwqs/weed_addiction_and_coping_with_emotion/"}' WHERE id = 483;
UPDATE programs.program_messages SET resources = '{"📈 Simon Sinek on How Reflection Informs Personal Growth":"https://youtu.be/_Ky-mKuhKgU?si=CQ1PSIWVXZDYF86Y","🔍 Get to know yourself through the act of self-reflection":"https://www.betterup.com/blog/self-reflectionn","💡 What was your deepest realization during self reflection?":"https://www.reddit.com/r/AskOldPeople/comments/1ddyl4p/what_was_your_deepest_realization_during_self/"}' WHERE id = 488;
UPDATE programs.program_messages SET resources = '{"🔍 How to self-examine life daily.":"https://www.reddit.com/r/Stoicism/comments/115sas7/how_to_selfexamine_life_daily/","🛑 How to stop your blind spots from tripping you up":"https://www.listeningpartnership.com/insight/how-to-stop-your-blind-spots-from-tripping-you-up/","💭 How has realising your most harmful negative core belief changed you/your life?":"https://www.reddit.com/r/AskWomenOver30/comments/168t5lm/how_has_realising_your_most_harmful_negative_core/"}' WHERE id = 495;
UPDATE programs.program_messages SET resources = '{"⌛ Real Change Takes Time":"https://possibilitychange.com/real-change-takes-time/","⏳ Accepting slow progress":"https://www.reddit.com/r/getdisciplined/comments/c46waw/advice_3_ways_to_be_more_accepting_of_slow/","🐢 Slow progress is better than no progress":"https://www.reddit.com/r/selfimprovement/comments/mtwksm/slow_progress_is_better_than_no_progress/","🌱 Embracing the Slow Journey of Real Change":"https://www.psychologytoday.com/us/blog/your-emotional-meter/202407/embracing-the-slow-journey-of-real-change","🧠 The mindset that changed my life IMMEDIATELY":"https://youtu.be/Vp-TVkqaCrQ?si=BuQjNJT4GBJi6HHL","💪 Self Improvement when you feel like you’re getting worse":"https://www.reddit.com/r/selfimprovement/comments/rgztkm/why_is_it_that_since_ive_started_trying_to/"}' WHERE id = 499;
UPDATE programs.program_messages SET resources = '{"🎨 Creativity without marijuana?":"https://www.reddit.com/r/leaves/comments/sf636k/creativity_without_marijuana/","💪 How to Strengthen Your Curiosity Muscle":"https://hbr.org/2023/11/how-to-strengthen-your-curiosity-muscle","🔍 How to be a more curious person, who is always seeking to learn more?":"https://www.reddit.com/r/getdisciplined/comments/t13hfn/need_advice_how_to_be_a_more_curious_person_who/","📅 Daily Habits to Foster Creativity: Building a Routine that Encourages Fresh Ideas":"https://jennarainey.com/daily-habits-to-foster-creativity-building-a-routine-that-encourages-fresh-ideas/","🧠 IWTL How to train myself to want mental stimulation as I’m not a very curious person?":"https://www.reddit.com/r/IWantToLearn/comments/yc8jgj/iwtl_how_to_train_myself_to_want_mental/"}' WHERE id = 503;
UPDATE programs.program_messages SET resources = '{"⚠️ What actually is “vice” and why should it be avoided?":"https://www.reddit.com/r/Stoicism/comments/1bs3dcu/what_actually_is_vice_and_why_should_it_be_avoided/"}' WHERE id = 509;
UPDATE programs.program_messages SET resources = '{"🌿 I Relapsed Quitting Weed !":"https://www.youtube.com/watch?v=KFAwb0py9ro","🔄 So I relapsed after 4 months...here''s what I learned :)":"https://www.reddit.com/r/leaves/comments/raphbx/so_i_relapsed_after_4_monthsheres_what_i_learned/"}' WHERE id = 510;
UPDATE programs.program_messages SET resources = '{"🧑‍⚕️ Dr. Fred''s Presentation":"https://www.youtube.com/watch?v=QVUrMXJ3wZ8","🌿 100 Days Without Marijuana. Here is What I Learned":"https://www.youtube.com/watch?v=nXnr1eWP_uQ"}' WHERE id = 513;
UPDATE programs.program_messages SET resources = '{"🍹 How to decide between sobriety and moderation":"https://www.reddit.com/r/Petioles/comments/epez3l/how_to_decide_between_sobriety_and_moderation/","🌿 New system for moderating cannabis use: not moderating":"https://www.reddit.com/r/Petioles/comments/1fzrymw/new_system_for_moderating_cannabis_use_not/"}' WHERE id = 520;
UPDATE programs.program_messages SET resources = '{"🌟 Acceptance Motivation":"https://www.youtube.com/watch?v=-lc3EDum9sc","🔄 The paradox of control":"https://www.youtube.com/watch?v=koo59KK43YA","❤️ Self-Love brings freedom":"https://www.youtube.com/watch?v=vj0JDwQLof4","🤗 How to Embrace Self-Acceptance":"https://www.verywellmind.com/self-acceptance-characteristics-importance-and-tips-for-improvement-6544468","🎯 Prioritize self-acceptance over self-improvement":"https://www.reddit.com/r/selfimprovement/comments/lekofw/prioritize_selfacceptance_over_selfimprovement/","💙 A practical way to practice self-acceptance 💙":"https://www.reddit.com/r/DecidingToBeBetter/comments/175qvzf/a_practical_way_to_practice_selfacceptance/","🙌 Accept Yourself Unconditionally (Even When You’re Struggling)":"https://tinybuddha.com/blog/accept-unconditionally-even-youre-struggling/"}' WHERE id = 524;
UPDATE programs.program_messages SET resources = '{"🎉 How do you celebrate!":"https://www.reddit.com/r/simpleliving/comments/1hkbv8z/how_do_you_celebrate/"}' WHERE id = 525;
