#!/usr/bin/env python3
"""
Generate seed SQL files from CSV backups.
Run from ~/Developer/clear30/Backend/
"""

import csv
import json
import os
import sys

BACKUPS = os.path.expanduser("~/Developer/clear30/Backend/backups/CSVs")
SEEDS = os.path.expanduser("~/Developer/clear30/Backend/supabase/seeds")


def q(val):
    """SQL-escape a value. Returns NULL for empty, or a properly quoted string."""
    if val is None or val == "":
        return "NULL"
    # Escape single quotes by doubling them
    escaped = str(val).replace("'", "''")
    return f"'{escaped}'"


def q_bool(val):
    """Convert CSV boolean string to SQL boolean."""
    if val is None or val == "":
        return "NULL"
    if str(val).lower() in ("true", "t", "1", "yes"):
        return "TRUE"
    if str(val).lower() in ("false", "f", "0", "no"):
        return "FALSE"
    return "NULL"


def q_int(val):
    """Convert to integer or NULL."""
    if val is None or val == "":
        return "NULL"
    try:
        return str(int(val))
    except (ValueError, TypeError):
        return "NULL"


def q_json(val):
    """Quote a JSON value — validate it's valid JSON, return NULL if empty."""
    if val is None or val == "":
        return "NULL"
    val = str(val).strip()
    if val == "" or val == "null":
        return "NULL"
    # Validate JSON
    try:
        json.loads(val)
    except json.JSONDecodeError:
        # If it's not valid JSON, return NULL rather than crashing
        print(f"  ⚠️  Invalid JSON skipped: {val[:80]}", file=sys.stderr)
        return "NULL"
    escaped = val.replace("'", "''")
    return f"'{escaped}'"


def write_header(f, table, source_csv):
    f.write(f"-- Seed: {table}\n")
    f.write(f"-- Source: {source_csv}\n")
    f.write(f"-- Generated by generate_seeds.py\n\n")


# ─────────────────────────────────────────────────────────────────────────────
# 20 — program_messages
# ─────────────────────────────────────────────────────────────────────────────

def gen_program_messages():
    src = os.path.join(BACKUPS, "2026_02_16_messages_all.csv")
    out = os.path.join(SEEDS, "20_program_messages.sql")
    # 'tutorial' program is NOT in the programs table — omit to avoid FK violation
    valid_programs = {"clear30", "clear30-start-soon", "life"}

    print(f"  Generating {out}...")
    rows_written = 0

    with open(src, newline="", encoding="utf-8") as csvfile, \
         open(out, "w", encoding="utf-8") as f:

        write_header(f, "programs.program_messages", os.path.basename(src))
        # Bypass FK checks during seeding — some guide_ids may not exist in the guides CSV
        f.write("SET session_replication_role = replica;\n\n")
        f.write("TRUNCATE programs.program_messages CASCADE;\n\n")

        reader = csv.DictReader(csvfile)
        for row in reader:
            prog = row.get("program", "").strip()
            # Only import rows belonging to known programs
            if prog not in valid_programs:
                continue

            vals = ", ".join([
                q_int(row.get("id")),
                q_int(row.get("day")),
                q(row.get("title")),
                q(row.get("subtitle")),
                q(row.get("body")),
                q(row.get("program")),
                q(row.get("question_id")),
                q(row.get("question_response")),
                q_json(row.get("resources")),
                q_json(row.get("claire_prompts")),
                q_json(row.get("journal_prompts")),
                q_json(row.get("meditation")),
                q_json(row.get("page_info")),
                q(row.get("stage")),
                q(row.get("guide_id")),
                q(row.get("notification_body")),
                q(row.get("notification_title")),
                q(row.get("thumbnail_url")),
                q(row.get("video_url")),
                q_json(row.get("instagram_videos")),
                q_json(row.get("carousel_images")),
                q_json(row.get("member_perks")),
                q_json(row.get("claire_prompts_json")),
            ])
            f.write(
                f"INSERT INTO programs.program_messages "
                f"(id, day, title, subtitle, body, program, question_id, question_response, "
                f"resources, claire_prompts, journal_prompts, meditation, page_info, stage, "
                f"guide_id, notification_body, notification_title, thumbnail_url, video_url, "
                f"instagram_videos, carousel_images, member_perks, claire_prompts_json) "
                f"VALUES ({vals}) ON CONFLICT (id) DO NOTHING;\n"
            )
            rows_written += 1

        f.write("\nSET session_replication_role = DEFAULT;\n")

    print(f"    ✅ {rows_written} rows")


# ─────────────────────────────────────────────────────────────────────────────
# 21 — program_guides (now 19_ — renamed for load order)
# ─────────────────────────────────────────────────────────────────────────────

def gen_program_guides():
    src = os.path.join(BACKUPS, "2025_10_01_guides.csv")
    out = os.path.join(SEEDS, "19_program_guides.sql")  # renamed: must seed before program_messages

    print(f"  Generating {out}...")
    rows_written = 0

    with open(src, newline="", encoding="utf-8") as csvfile, \
         open(out, "w", encoding="utf-8") as f:

        write_header(f, "programs.program_guides", os.path.basename(src))
        f.write("TRUNCATE programs.program_guides CASCADE;\n\n")

        reader = csv.DictReader(csvfile)
        for row in reader:
            vals = ", ".join([
                q(row.get("id")),
                q(row.get("title")),
                q(row.get("subtitle")),
                q(row.get("published_on")) if row.get("published_on") else "NULL",
                q(row.get("thumbnail")),
                q_json(row.get("resources")),
                q(row.get("section_1_title")),
                q(row.get("section_1_content")),
                q(row.get("section_2_title")),
                q(row.get("section_2_content")),
                q(row.get("section_3_title")),
                q(row.get("section_3_content")),
                q(row.get("section_4_title")),
                q(row.get("section_4_content")),
                q(row.get("section_5_title")),
                q(row.get("section_5_content")),
                q(row.get("section_6_title")),
                q(row.get("section_6_content")),
                q(row.get("section_7_title")),
                q(row.get("section_7_content")),
                q(row.get("section_8_title")),
                q(row.get("section_8_content")),
                q(row.get("section_9_title")),
                q(row.get("section_9_content")),
            ])
            f.write(
                f"INSERT INTO programs.program_guides "
                f"(id, title, subtitle, published_on, thumbnail, resources, "
                f"section_1_title, section_1_content, section_2_title, section_2_content, "
                f"section_3_title, section_3_content, section_4_title, section_4_content, "
                f"section_5_title, section_5_content, section_6_title, section_6_content, "
                f"section_7_title, section_7_content, section_8_title, section_8_content, "
                f"section_9_title, section_9_content) "
                f"VALUES ({vals}) ON CONFLICT (id) DO NOTHING;\n"
            )
            rows_written += 1

    print(f"    ✅ {rows_written} rows")


# ─────────────────────────────────────────────────────────────────────────────
# 22 — program_pop_ups
# ─────────────────────────────────────────────────────────────────────────────

def gen_program_popups():
    src = os.path.join(BACKUPS, "2025_08_23_program_popups.csv")
    out = os.path.join(SEEDS, "22_program_popups.sql")

    print(f"  Generating {out}...")
    rows_written = 0

    with open(src, newline="", encoding="utf-8") as csvfile, \
         open(out, "w", encoding="utf-8") as f:

        write_header(f, "programs.program_pop_ups", os.path.basename(src))
        f.write("TRUNCATE programs.program_pop_ups CASCADE;\n\n")

        reader = csv.DictReader(csvfile)
        for row in reader:
            vals = ", ".join([
                q_int(row.get("id")),
                q(row.get("program")),
                q_int(row.get("day")),
                q_bool(row.get("active")),
                q(row.get("created_at")) if row.get("created_at") else "NOW()",
                q_json(row.get("popup")),
                # existing_sheet_type not in CSV — skip
            ])
            f.write(
                f"INSERT INTO programs.program_pop_ups "
                f"(id, program, day, active, created_at, popup) "
                f"VALUES ({vals}) ON CONFLICT (id) DO NOTHING;\n"
            )
            rows_written += 1

    print(f"    ✅ {rows_written} rows")


# ─────────────────────────────────────────────────────────────────────────────
# 23 — support_items
# ─────────────────────────────────────────────────────────────────────────────

def gen_support_items():
    src = os.path.join(BACKUPS, "2025_08_23_support_items.csv")
    out = os.path.join(SEEDS, "23_support_items.sql")

    print(f"  Generating {out}...")
    rows_written = 0

    with open(src, newline="", encoding="utf-8") as csvfile, \
         open(out, "w", encoding="utf-8") as f:

        write_header(f, "library.support_items", os.path.basename(src))
        f.write("TRUNCATE library.support_items CASCADE;\n\n")

        reader = csv.DictReader(csvfile)
        for row in reader:
            vals = ", ".join([
                q_int(row.get("id")),
                q(row.get("button_title")),
                q(row.get("button_symbol")),
                q(row.get("color1")),
                q(row.get("color2")),
                q_json(row.get("sheet_info")),
            ])
            f.write(
                f"INSERT INTO library.support_items "
                f"(id, button_title, button_symbol, color1, color2, sheet_info) "
                f"VALUES ({vals}) ON CONFLICT (id) DO NOTHING;\n"
            )
            rows_written += 1

    print(f"    ✅ {rows_written} rows")


# ─────────────────────────────────────────────────────────────────────────────
# 24 — craving_resources
# ─────────────────────────────────────────────────────────────────────────────

def gen_craving_resources():
    src = os.path.join(BACKUPS, "2025_10_20_craving_resources.csv")
    out = os.path.join(SEEDS, "24_craving_resources.sql")

    print(f"  Generating {out}...")
    rows_written = 0

    with open(src, newline="", encoding="utf-8") as csvfile, \
         open(out, "w", encoding="utf-8") as f:

        write_header(f, "library.craving_resources", os.path.basename(src))
        f.write("TRUNCATE library.craving_resources CASCADE;\n\n")

        reader = csv.DictReader(csvfile)
        for row in reader:
            vals = ", ".join([
                q_int(row.get("id")),
                q(row.get("type")),
                q_json(row.get("data")),
            ])
            f.write(
                f"INSERT INTO library.craving_resources (id, type, data) "
                f"VALUES ({vals}) ON CONFLICT (id) DO NOTHING;\n"
            )
            rows_written += 1

    print(f"    ✅ {rows_written} rows")


# ─────────────────────────────────────────────────────────────────────────────
# 25 — onboarding_reviews
# ─────────────────────────────────────────────────────────────────────────────

def gen_onboarding_reviews():
    src = os.path.join(BACKUPS, "2025_04_28_onboarding_reviews.csv")
    out = os.path.join(SEEDS, "25_onboarding_reviews.sql")

    print(f"  Generating {out}...")
    rows_written = 0

    with open(src, newline="", encoding="utf-8") as csvfile, \
         open(out, "w", encoding="utf-8") as f:

        write_header(f, "library.onboarding_reviews", os.path.basename(src))
        f.write("TRUNCATE library.onboarding_reviews CASCADE;\n\n")

        reader = csv.DictReader(csvfile)
        for row in reader:
            vals = ", ".join([
                q_int(row.get("id")),
                q(row.get("title")),
                q(row.get("body")),
                q_int(row.get("priority")),
                q(row.get("created_at")) if row.get("created_at") else "NOW()",
                q(row.get("author")),
            ])
            f.write(
                f"INSERT INTO library.onboarding_reviews (id, title, body, priority, created_at, author) "
                f"VALUES ({vals}) ON CONFLICT (id) DO NOTHING;\n"
            )
            rows_written += 1

    print(f"    ✅ {rows_written} rows")


# ─────────────────────────────────────────────────────────────────────────────
# 26 — push_check_in
# ─────────────────────────────────────────────────────────────────────────────

def gen_push_check_in():
    src = os.path.join(BACKUPS, "2025_03_03_push_check_in.csv")
    out = os.path.join(SEEDS, "26_push_check_in.sql")

    print(f"  Generating {out}...")
    rows_written = 0

    with open(src, newline="", encoding="utf-8") as csvfile, \
         open(out, "w", encoding="utf-8") as f:

        write_header(f, "library.push_check_in", os.path.basename(src))
        f.write("TRUNCATE library.push_check_in CASCADE;\n\n")

        reader = csv.DictReader(csvfile)
        for row in reader:
            vals = ", ".join([
                q_int(row.get("id")),
                q(row.get("title")),
                q(row.get("body")),
                q(row.get("question_id")),
                q(row.get("question_response")),
            ])
            f.write(
                f"INSERT INTO library.push_check_in (id, title, body, question_id, question_response) "
                f"VALUES ({vals}) ON CONFLICT (id) DO NOTHING;\n"
            )
            rows_written += 1

    print(f"    ✅ {rows_written} rows")


# ─────────────────────────────────────────────────────────────────────────────
# 27 — push_abandoned_onboarding
# ─────────────────────────────────────────────────────────────────────────────

def gen_push_abandoned_onboarding():
    # Use the most recent version (2025_10_27 has metadata + active columns)
    src = os.path.join(BACKUPS, "2025_10_27_abandoned_onboarding_notis.csv")
    out = os.path.join(SEEDS, "27_push_abandoned_onboarding.sql")

    print(f"  Generating {out}...")
    rows_written = 0

    with open(src, newline="", encoding="utf-8") as csvfile, \
         open(out, "w", encoding="utf-8") as f:

        write_header(f, "library.push_abandoned_onboarding", os.path.basename(src))
        f.write("TRUNCATE library.push_abandoned_onboarding CASCADE;\n\n")

        reader = csv.DictReader(csvfile)
        for row in reader:
            vals = ", ".join([
                q_int(row.get("id")),
                q(row.get("title")),
                q(row.get("body")),
                q(row.get("question_id")),
                q(row.get("question_response")),
                q_json(row.get("metadata")),
                q_bool(row.get("active")),
            ])
            f.write(
                f"INSERT INTO library.push_abandoned_onboarding "
                f"(id, title, body, question_id, question_response, metadata, active) "
                f"VALUES ({vals}) ON CONFLICT (id) DO NOTHING;\n"
            )
            rows_written += 1

    print(f"    ✅ {rows_written} rows")


# ─────────────────────────────────────────────────────────────────────────────
# 28 — remote_assessment_questions
# ─────────────────────────────────────────────────────────────────────────────

def gen_remote_assessment_questions():
    src = os.path.join(BACKUPS, "2025_07_17_assessment_remote.csv")
    out = os.path.join(SEEDS, "28_remote_assessment_questions.sql")

    print(f"  Generating {out}...")
    rows_written = 0

    with open(src, newline="", encoding="utf-8") as csvfile, \
         open(out, "w", encoding="utf-8") as f:

        write_header(f, "programs.remote_assessment_questions", os.path.basename(src))
        f.write("TRUNCATE programs.remote_assessment_questions CASCADE;\n\n")

        reader = csv.DictReader(csvfile)
        for row in reader:
            # prompt1/prompt2 are NOT NULL in schema — use empty string as default
            def qq(val):
                return q(val) if val else "''"

            vals = ", ".join([
                q_int(row.get("id")),
                q(row.get("after_question_id")),
                qq(row.get("stripped_prompt")),
                qq(row.get("prompt1")),
                qq(row.get("prompt2")),
                q_json(row.get("options")),
                q_json(row.get("displayed_options")),
                q_json(row.get("image_names")),
                q_json(row.get("badges")),
                q_json(row.get("subtexts")),
                q_int(row.get("min")),
                q_int(row.get("max")),
                q_bool(row.get("enabled")),
                q(row.get("created_at")) if row.get("created_at") else "NOW()",
                q_bool(row.get("randomize_options")),
            ])
            f.write(
                f"INSERT INTO programs.remote_assessment_questions "
                f"(id, after_question_id, stripped_prompt, prompt1, prompt2, options, "
                f"displayed_options, image_names, badges, subtexts, min, max, enabled, "
                f"created_at, randomize_options) "
                f"VALUES ({vals}) ON CONFLICT (id) DO NOTHING;\n"
            )
            rows_written += 1

    print(f"    ✅ {rows_written} rows")


# ─────────────────────────────────────────────────────────────────────────────
# 29 — symptom_resources
# ─────────────────────────────────────────────────────────────────────────────

def gen_symptom_resources():
    src = os.path.join(BACKUPS, "2025_12_16_symptom_resources.csv")
    out = os.path.join(SEEDS, "29_symptom_resources.sql")

    print(f"  Generating {out}...")
    rows_written = 0

    with open(src, newline="", encoding="utf-8") as csvfile, \
         open(out, "w", encoding="utf-8") as f:

        write_header(f, "symptoms.symptom_resources", os.path.basename(src))
        # symptoms.symptoms table is empty locally (data lives in library.cache).
        # Bypass FK to allow seeding symptom_resources without parent symptom rows.
        f.write("SET session_replication_role = replica;\n\n")
        f.write("TRUNCATE symptoms.symptom_resources CASCADE;\n\n")

        reader = csv.DictReader(csvfile)
        for row in reader:
            vals = ", ".join([
                q_int(row.get("id")),
                q(row.get("symptom")),
                q(row.get("title")),
                q(row.get("subtitle")),
                q(row.get("image_url")),
                q(row.get("type")),
                q_json(row.get("extra_info")),
                q_bool(row.get("enabled")),
                q(row.get("created_at")) if row.get("created_at") else "NOW()",
                q(row.get("local_image_name")),
            ])
            f.write(
                f"INSERT INTO symptoms.symptom_resources "
                f"(id, symptom, title, subtitle, image_url, type, extra_info, enabled, created_at, local_image_name) "
                f"VALUES ({vals}) ON CONFLICT (id) DO NOTHING;\n"
            )
            rows_written += 1

        f.write("\nSET session_replication_role = DEFAULT;\n")

    print(f"    ✅ {rows_written} rows")


# ─────────────────────────────────────────────────────────────────────────────
# 30 — events
# ─────────────────────────────────────────────────────────────────────────────

def gen_events():
    src = os.path.join(BACKUPS, "2025_04_10/events.csv")
    out = os.path.join(SEEDS, "30_events.sql")

    print(f"  Generating {out}...")
    rows_written = 0

    with open(src, newline="", encoding="utf-8") as csvfile, \
         open(out, "w", encoding="utf-8") as f:

        write_header(f, "events.events", os.path.basename(src))
        f.write("-- NOTE: Events are time-limited; these are April 2025 events for local dev/testing.\n")
        f.write("TRUNCATE events.events CASCADE;\n\n")

        reader = csv.DictReader(csvfile)
        for row in reader:
            vals = ", ".join([
                q(row.get("id")),
                q(row.get("name")),
                q(row.get("short_name")),
                q_int(row.get("num_waiting")),
                q(row.get("onboarding_start_date")) if row.get("onboarding_start_date") else "NULL",
                q(row.get("onboarding_end_date")) if row.get("onboarding_end_date") else "NULL",
                q(row.get("program_day_1")) if row.get("program_day_1") else "NULL",
                q(row.get("app_unlock_date")) if row.get("app_unlock_date") else "NULL",
                q(row.get("color1")),
                q(row.get("color2")),
                q(row.get("sms_id")),
                q(row.get("lobby_community_tag")) if row.get("lobby_community_tag") else "NULL",
                q(row.get("community_tag")) if row.get("community_tag") else "NULL",
                q(row.get("end_date")) if row.get("end_date") else "NULL",
            ])
            f.write(
                f"INSERT INTO events.events "
                f"(id, name, short_name, num_waiting, onboarding_start_date, onboarding_end_date, "
                f"program_day_1, app_unlock_date, color1, color2, sms_id, lobby_community_tag, "
                f"community_tag, end_date) "
                f"VALUES ({vals}) ON CONFLICT (id) DO NOTHING;\n"
            )
            rows_written += 1

    print(f"    ✅ {rows_written} rows")


# ─────────────────────────────────────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    print("🌱 Generating seed SQL files from CSV backups...\n")

    generators = [
        gen_program_messages,
        gen_program_guides,
        gen_program_popups,
        gen_support_items,
        gen_craving_resources,
        gen_onboarding_reviews,
        gen_push_check_in,
        gen_push_abandoned_onboarding,
        gen_remote_assessment_questions,
        gen_symptom_resources,
        gen_events,
    ]

    for gen in generators:
        try:
            gen()
        except Exception as e:
            print(f"  ❌ {gen.__name__} failed: {e}")
            import traceback
            traceback.print_exc()

    print("\n✅ Done. Run: supabase db reset")
