create table "comms"."dr_fred" (
    "id" bigint generated by default as identity not null,
    "user_id" text not null,
    "message" text not null,
    "outbound" boolean not null,
    "timestamp" timestamp with time zone not null default now()
);


alter table "comms"."dr_fred" enable row level security;

CREATE UNIQUE INDEX dr_fred_pkey ON comms.dr_fred USING btree (id);

alter table "comms"."dr_fred" add constraint "dr_fred_pkey" PRIMARY KEY using index "dr_fred_pkey";

alter table "comms"."dr_fred" add constraint "dr_fred_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "comms"."dr_fred" validate constraint "dr_fred_user_id_fkey";

create policy "Disable access for all"
on "comms"."dr_fred"
as permissive
for all
to public
using (false);



drop function if exists "public"."get_group"(group_id uuid);

drop function if exists "public"."update_group"(group_data json);

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.dr_fred_get_messages()
 RETURNS text[]
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$DECLARE
    v_user_id text;
    v_messages text[];
BEGIN
    -- Get the user_id from the users table based on the authenticated user's auth.uid()
    SELECT id INTO v_user_id
    FROM public.users
    WHERE auth_id = auth.uid();

    -- If no user found, raise an exception
    IF v_user_id IS NULL THEN
        RAISE EXCEPTION 'User not found';
    END IF;

    -- Get messages and store them in array
    SELECT array_agg(message ORDER BY timestamp)
    INTO v_messages
    FROM comms.dr_fred
    WHERE user_id = v_user_id
    AND outbound = true;  -- Only get messages from Dr. Fred (outbound = true)

    -- Return empty array if no messages found
    RETURN COALESCE(v_messages, ARRAY[]::text[]);
END;$function$
;

CREATE OR REPLACE FUNCTION public.dr_fred_send_message(message text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$DECLARE
    v_user_id text;
BEGIN
    -- Get the user_id from the users table based on the authenticated user's auth.uid()
    SELECT id INTO v_user_id
    FROM public.users
    WHERE auth_id = auth.uid();

    -- If no user found, raise an exception
    IF v_user_id IS NULL THEN
        RAISE EXCEPTION 'User not found';
    END IF;

    -- Insert the message
    INSERT INTO comms.dr_fred (
        user_id,
        message,
        outbound
    ) VALUES (
        v_user_id,
        message,
        false
    );
END;$function$
;

CREATE OR REPLACE FUNCTION public.group_add_mem(group_id uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$DECLARE
    current_user_id text;
BEGIN
    -- Get the user_id from the users table using the auth_id
    SELECT id INTO current_user_id
    FROM public.users
    WHERE auth_id = auth.uid();
    
    -- If no user_id found, raise an exception
    IF current_user_id IS NULL THEN
        RAISE EXCEPTION 'No user found for the current auth_id';
    END IF;

    -- Insert a new row into the group_members table
    INSERT INTO groups.group_members (user_id, group_id)
    VALUES (current_user_id, group_add_mem.group_id)
    ON CONFLICT DO NOTHING;  -- Avoid inserting duplicate records

    -- Insert a new row into the group_activity table with the "joined" activity
    INSERT INTO groups.group_activity (group_id, user_id, activity)
    VALUES (group_add_mem.group_id, current_user_id, 'joined');
END;$function$
;

CREATE OR REPLACE FUNCTION public.group_add_note(group_id uuid, to_member_id text, message text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$DECLARE
    current_user_id text;
BEGIN
    -- Get the user_id from the users table using the auth_id
    SELECT id INTO current_user_id
    FROM public.users
    WHERE auth_id = auth.uid();
    
    -- If no user_id found, raise an exception
    IF current_user_id IS NULL THEN
        RAISE EXCEPTION 'No user found for the current auth_id';
    END IF;

    -- Check if both to_member_id and from_member_id (current user) are in the group
    IF EXISTS (
        SELECT 1 FROM groups.group_members gm
        WHERE gm.group_id = group_add_note.group_id
          AND gm.user_id = to_member_id
    )
    AND EXISTS (
        SELECT 1 FROM groups.group_members gm
        WHERE gm.group_id = group_add_note.group_id
          AND gm.user_id = current_user_id
    ) THEN
        -- Insert the note into the group_notes table
        INSERT INTO groups.group_notes (
            group_id, 
            to_member_id, 
            from_member_id, 
            message, 
            timestamp
        )
        VALUES (
            group_id, 
            to_member_id, 
            current_user_id, 
            message, 
            NOW()
        );

        -- Insert a new row into the group_activity table with the "note" activity
        INSERT INTO groups.group_activity (
            group_id, 
            user_id, 
            activity
        )
        VALUES (
            group_id, 
            current_user_id, 
            'message'
        );
    END IF;
END;$function$
;

CREATE OR REPLACE FUNCTION public.group_add_ping(group_id uuid, to_user_id text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$DECLARE
    current_user_id text;
BEGIN
    -- Get the user_id from the users table using the auth_id
    SELECT id INTO current_user_id
    FROM public.users
    WHERE auth_id = auth.uid();
    
    -- If no user_id found, raise an exception
    IF current_user_id IS NULL THEN
        RAISE EXCEPTION 'No user found for the current auth_id';
    END IF;

    -- Check if both to_user_id and current user are in the group
    IF EXISTS (
        SELECT 1 FROM groups.group_members gm
        WHERE gm.group_id = group_add_ping.group_id
          AND gm.user_id = to_user_id
    )
    AND EXISTS (
        SELECT 1 FROM groups.group_members gm
        WHERE gm.group_id = group_add_ping.group_id
          AND gm.user_id = current_user_id
    ) THEN
        -- Insert the ping into the group_pings table
        INSERT INTO groups.group_pings (
            group_id, 
            from_user_id, 
            to_user_id
        )
        VALUES (
            group_id, 
            current_user_id, 
            to_user_id
        );
    END IF;
END;$function$
;

CREATE OR REPLACE FUNCTION public.group_delete(group_id uuid)
 RETURNS void
 LANGUAGE plpgsql
AS $function$BEGIN
    -- Delete all records from the group_notes table for the specified group
    DELETE FROM groups.group_notes
    WHERE groups.group_notes.group_id = group_delete.group_id;

    -- Delete all records from the group_activity table for the specified group
    DELETE FROM groups.group_activity
    WHERE groups.group_activity.group_id = group_delete.group_id;

    -- Delete all records from the group_members table for the specified group
    DELETE FROM groups.group_members
    WHERE groups.group_members.group_id = group_delete.group_id;

    -- Finally, delete the group itself from the groups table
    DELETE FROM groups.groups
    WHERE groups.groups.id = group_delete.group_id;

END;$function$
;

CREATE OR REPLACE FUNCTION public.group_get(group_id uuid)
 RETURNS json
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$DECLARE
    current_user_id text;
BEGIN
    -- Get the user_id from the users table using the auth_id
    SELECT id INTO current_user_id
    FROM public.users
    WHERE auth_id = auth.uid();
    
    -- If no user_id found, raise an exception
    IF current_user_id IS NULL THEN
        RAISE EXCEPTION 'No user found for the current auth_id';
    END IF;

    -- Step 1: Check if the user is part of the group
    IF NOT EXISTS (
        SELECT 1
        FROM groups.group_members gm
        WHERE gm.group_id = group_get.group_id
          AND gm.user_id = current_user_id
    ) THEN
        -- Raise a custom exception with a custom SQLSTATE
        RAISE EXCEPTION 'User % is not part of the group %', current_user_id, group_get.group_id
            USING ERRCODE = 'P0001';
    END IF;

    -- Step 2: Return group details if the user is part of the group
    RETURN (
        SELECT json_build_object(
            'id', g.id,
            'name', g.name,
            'hue', g.hue,
            'members', (
                SELECT COALESCE(json_agg(
                    json_build_object(
                        'memberID', u.id,
                        'name', u.name,
                        'emoji', u.emoji,
                        'daysSober', COALESCE(
                            (SELECT days_sober FROM programs.convert_day_info_to_legacy(u.day_info)),
                            ARRAY[]::boolean[]
                        ),
                        'initialFrequency', 0.5,
                        'showInRank', u.show_in_group_rank,
                        'startDate', (SELECT start_date FROM programs.convert_day_info_to_legacy(u.day_info)),
                        '_dayInfo', (
                            SELECT jsonb_object_agg(
                                key,
                                value
                            )
                            FROM (
                                SELECT 
                                    (day_info->>(i*2)) as key,
                                    day_info->(i*2 + 1) as value
                                FROM generate_series(0, jsonb_array_length(u.day_info)/2 - 1) as i
                                WHERE i*2 < jsonb_array_length(u.day_info)
                            ) as pairs
                        ),
                        'notes', COALESCE((
                            SELECT json_agg(
                                json_build_object(
                                    'fromMemberID', gn.from_member_id,
                                    'message', gn.message,
                                    'timestamp', date_trunc('second', gn.timestamp)
                                )
                            )
                            FROM groups.group_notes gn
                            WHERE gn.to_member_id = u.id
                            AND gn.group_id = g.id
                        ), '[]'::json)
                    )
                ), '[]'::json)
                FROM groups.group_members gm
                JOIN users u ON gm.user_id = u.id
                WHERE gm.group_id = g.id
            ),
            'activity', COALESCE((
                SELECT json_agg(
                    json_build_object(
                        'memberID', ga.user_id,
                        'type', ga.activity,
                        'timestamp', date_trunc('second', ga.timestamp)  -- Truncate to seconds
                    )
                )
                FROM groups.group_activity ga
                WHERE ga.group_id = g.id
            ), '[]'::json),
            'subscribed', (
                SELECT COALESCE(json_agg(
                    json_build_object(
                        'subscribedTo', gs.subscribed_to
                    )
                ), '[]'::json)
                FROM groups.group_subscriptions gs
                WHERE gs.group_id = group_get.group_id
                AND gs.user_id = current_user_id
            )
        )
        FROM groups.groups g
        WHERE g.id = group_get.group_id
    );
END;$function$
;

CREATE OR REPLACE FUNCTION public.group_rem_mem(user_id text, group_id uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$DECLARE
    current_user_id text;
BEGIN
    -- Get the current user's ID from their auth ID
    SELECT id INTO current_user_id
    FROM public.users
    WHERE auth_id = auth.uid();

    -- Check if the current user is in the group
    IF NOT EXISTS (
        SELECT 1 FROM groups.group_members gm
        WHERE gm.group_id = group_rem_mem.group_id
        AND gm.user_id = current_user_id
    ) THEN
        RAISE EXCEPTION 'You must be a member of the group to remove members';
    END IF;

    -- Step 1: Remove all activities related to the user and group
    DELETE FROM groups.group_activity ga
    WHERE ga.user_id = group_rem_mem.user_id
      AND ga.group_id = group_rem_mem.group_id;

    -- Step 2: Remove the user from the group_members table
    DELETE FROM groups.group_members gm
    WHERE gm.user_id = group_rem_mem.user_id
      AND gm.group_id = group_rem_mem.group_id;

    -- Step 3: Remove all subscriptions for the user and group
    DELETE FROM groups.group_subscriptions gs
    WHERE gs.user_id = group_rem_mem.user_id
      AND gs.group_id = group_rem_mem.group_id;

    -- Step 4: Remove all related group notes (sent or received by the user)
    DELETE FROM groups.group_notes gn
    WHERE gn.group_id = group_rem_mem.group_id
      AND (gn.to_member_id = group_rem_mem.user_id OR gn.from_member_id = group_rem_mem.user_id);

    -- Step 5: Check if the user was the last member of the group
    IF NOT EXISTS (
        SELECT 1 FROM groups.group_members gm
        WHERE gm.group_id = group_rem_mem.group_id
    ) THEN
        -- Call the delete_group function to delete the group if no members remain
        PERFORM group_delete(group_rem_mem.group_id);
    END IF;
END;$function$
;

CREATE OR REPLACE FUNCTION public.group_update_activity(group_id uuid, activity_data jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$DECLARE
    current_user_id text;
BEGIN
    -- Get the user_id from the users table using the auth_id
    SELECT id INTO current_user_id
    FROM public.users
    WHERE auth_id = auth.uid();
    
    -- If no user_id found, raise an exception
    IF current_user_id IS NULL THEN
        RAISE EXCEPTION 'No user found for the current auth_id';
    END IF;

    WITH json_activities AS (
        -- Step 1: Unnest the JSONB array into a table format for easy comparison
        SELECT 
            -- Associate all activities with the current user
            current_user_id AS user_id,
            -- Map string values to the corresponding enum type
            CASE
                WHEN activity->>'type' = 'smoked' THEN 'smoked'::group_activity_type
                WHEN activity->>'type' = 'sober' THEN 'sober'::group_activity_type
                WHEN activity->>'type' = 'joined' THEN 'joined'::group_activity_type
                WHEN activity->>'type' = 'message' THEN 'message'::group_activity_type
                ELSE NULL
            END AS activity_type,
            (activity->>'timestamp')::timestamptz AS activity_timestamp
        FROM jsonb_array_elements(activity_data) AS activity
    ),
    -- Step 2: Delete activities for the current user that are in the table but not in the provided JSON
    delete_activities AS (
        DELETE FROM groups.group_activity ga
        WHERE ga.group_id = group_update_activity.group_id
          AND ga.user_id = current_user_id
          AND NOT EXISTS (
              SELECT 1 FROM json_activities ja
              WHERE ja.user_id = ga.user_id
                AND ja.activity_type = ga.activity
                AND ja.activity_timestamp = ga.timestamp
          )
        RETURNING *
    )
    -- Step 3: Insert activities from JSON if they don't already exist in the table
    INSERT INTO groups.group_activity (group_id, user_id, activity, timestamp)
    SELECT group_update_activity.group_id, ja.user_id, ja.activity_type, ja.activity_timestamp
    FROM json_activities ja
    WHERE ja.activity_type IS NOT NULL  -- Only insert valid activity types
      AND NOT EXISTS (
        SELECT 1 FROM groups.group_activity ga
        WHERE ga.group_id = group_update_activity.group_id
          AND ga.user_id = current_user_id
          AND ga.activity = ja.activity_type
          AND ga.timestamp = ja.activity_timestamp
    );
END;$function$
;

CREATE OR REPLACE FUNCTION public.group_update_subscriptions(group_id uuid, subscriptions jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$DECLARE
    current_user_id text;
BEGIN
    -- Get the user_id from the users table using the auth_id
    SELECT id INTO current_user_id
    FROM public.users
    WHERE auth_id = auth.uid();
    
    -- If no user_id found, raise an exception
    IF current_user_id IS NULL THEN
        RAISE EXCEPTION 'No user found for the current auth_id';
    END IF;

    -- 1. Check if the user is in the group
    IF NOT EXISTS (
        SELECT 1 
        FROM groups.group_members
        WHERE group_members.group_id = group_update_subscriptions.group_id
        AND group_members.user_id = current_user_id
    ) THEN
        RAISE EXCEPTION 'User is not a member of the group';
    END IF;

    -- 2. Remove all existing rows in group_subscriptions for the group_id and user_id
    DELETE FROM groups.group_subscriptions
    WHERE group_subscriptions.group_id = group_update_subscriptions.group_id
    AND group_subscriptions.user_id = current_user_id;

    -- 3. Insert new subscriptions into group_subscriptions
    INSERT INTO groups.group_subscriptions (group_id, user_id, subscribed_to)
    SELECT 
        group_update_subscriptions.group_id, 
        current_user_id, 
        value::TEXT
    FROM jsonb_array_elements_text(group_update_subscriptions.subscriptions) AS value;

END;$function$
;

CREATE OR REPLACE FUNCTION public.group_upsert(group_data jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$DECLARE
    current_user_id text;
BEGIN
    -- Get the user_id from the users table using the auth_id
    SELECT id INTO current_user_id
    FROM public.users
    WHERE auth_id = auth.uid();
    
    -- If no user_id found, raise an exception
    IF current_user_id IS NULL THEN
        RAISE EXCEPTION 'No user found for the current auth_id';
    END IF;

    -- If an 'id' is provided, check if the group exists and the user is part of the group
    IF group_data ? 'id' THEN
        -- Check if the group exists
        IF EXISTS (SELECT 1 FROM groups.groups WHERE id = (group_data->>'id')::uuid) THEN
            -- Check if the user is part of the group
            IF NOT EXISTS (
                SELECT 1
                FROM groups.group_members gm
                WHERE gm.group_id = (group_data->>'id')::uuid
                  AND gm.user_id = current_user_id
            ) THEN
                -- Raise an exception if the user is not part of the group
                RAISE EXCEPTION 'User % is not a member of the group %', current_user_id, group_data->>'id';
            END IF;
        END IF;

        -- Insert or update the group with the provided 'id'
        INSERT INTO groups.groups (
            id, 
            name, 
            hue
        )
        VALUES (
            (group_data->>'id')::uuid,    -- Use the provided 'id'
            group_data->>'name',          -- Name must be provided for creation
            (group_data->>'hue')::numeric -- Hue must be provided for creation
        )
        ON CONFLICT (id)
        DO UPDATE
        SET name = COALESCE(group_data->>'name', groups.name),
            hue = COALESCE((group_data->>'hue')::numeric, groups.hue);

    ELSE
        -- Insert without 'id', letting Supabase generate the UUID
        INSERT INTO groups.groups (
            name, 
            hue
        )
        VALUES (
            group_data->>'name',          -- Name must be provided for creation
            (group_data->>'hue')::numeric -- Hue must be provided for creation
        );
    END IF;
END;$function$
;

CREATE OR REPLACE FUNCTION public.get_school_data(school_id text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$DECLARE
    result JSONB;
    cached_result JSONB;
BEGIN
    -- Step 1: Check if there's a cached result for this school_id
    SELECT json INTO cached_result
    FROM library.cache
    WHERE type = school_id;

    -- Step 2: If cached result exists and is not NULL, return it
    IF cached_result IS NOT NULL THEN
        RETURN cached_result;
    END IF;

    -- Step 3: If no cached result, compute the result
    WITH aggregated_resources AS (
        SELECT r.school_id,
               r.section_title,
               jsonb_agg(
                   jsonb_build_object(
                       'title', r.title,
                       'subtitle', r.subtitle,
                       'description', r.description,
                       'phone_number', r.phone_number,
                       'location', r.location,
                       'link', r.link,
                       'badge', r.badge
                   )
               ) AS resources_array
        FROM schools.school_resources r
        WHERE r.school_id = $1
        GROUP BY r.school_id, r.section_title
    ),
    final_resources AS (
        SELECT ar.school_id,
               jsonb_object_agg(ar.section_title, ar.resources_array) AS resources
        FROM aggregated_resources ar
        GROUP BY ar.school_id
    ),
    aggregated_messages AS (
        SELECT jsonb_agg(
               jsonb_build_object(
                   'day', m.day,
                   'title', m.title,
                   'subtitle', m.subtitle,
                   'message', m.message,
                   'meditation_name', (
                       SELECT key
                       FROM jsonb_object_keys(m.meditation) key
                       LIMIT 1
                   ),
                   'meditation_link', (
                       SELECT m.meditation->key
                       FROM jsonb_object_keys(m.meditation) key
                       LIMIT 1
                   ),
                   'prompts', COALESCE(m.claire_prompts, '{}'::jsonb),
                   'journal_prompts', COALESCE(m.journal_prompts, '[]'::jsonb),
                   'resources', COALESCE(m.resources, '{}'::jsonb)
               )
           ) AS messages_array
        FROM schools.school_messages m
        WHERE m.school_id = $1
    )
    
    -- Step 4: Build the JSON result
    SELECT jsonb_build_object(
        'school_id', s.school_id,
        'short_name', s.short_name,
        'long_name', s.long_name,
        'reddit_flair', COALESCE(s.reddit_flair, NULL),
        'color1', s.color1,
        'color2', s.color2,
        'activities', COALESCE(
            jsonb_agg(
                jsonb_build_object(
                    'title', a.title,
                    'org_name', a.org_name,
                    'location', a.location,
                    'subtitle', a.subtitle,
                    'description', a.description,
                    'date_time', a.date_time,
                    'repeats', a.repeats,
                    'link', a.link,
                    'facilitated_by', a.facilitated_by,
                    'phone_number', a.phone_number,
                    'email', a.email,
                    'sub_links', a.sub_links
                )
            ) FILTER (WHERE a.school_id IS NOT NULL), '[]'::jsonb
        ),
        'resources', COALESCE(fr.resources, '{}'::jsonb),
        'messages', COALESCE(am.messages_array, '[]'::jsonb)
    )
    INTO result
    FROM schools.schools s
    LEFT JOIN schools.school_activities a ON s.school_id = a.school_id
    LEFT JOIN final_resources fr ON s.school_id = fr.school_id
    LEFT JOIN aggregated_messages am ON TRUE  -- Ensure that all messages for this school are selected
    WHERE s.school_id = $1
    GROUP BY s.school_id, fr.resources, am.messages_array;

    -- Step 5: Insert the computed result into the cache table
    INSERT INTO library.cache (type, json, last_updated)
    VALUES ($1, result, NOW())
    ON CONFLICT (type) DO UPDATE
    SET json = EXCLUDED.json, last_updated = NOW();
    
    -- Step 6: Return the computed result
    RETURN result;
END;$function$
;

CREATE OR REPLACE FUNCTION public.rem_group_mem(user_id text, group_id uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$BEGIN
    -- Step 1: Remove all activities related to the user and group
    DELETE FROM groups.group_activity ga
    WHERE ga.user_id = rem_group_mem.user_id
      AND ga.group_id = rem_group_mem.group_id;

    -- Step 2: Remove the user from the group_members table
    DELETE FROM groups.group_members gm
    WHERE gm.user_id = rem_group_mem.user_id
      AND gm.group_id = rem_group_mem.group_id;

    -- Step 3: Remove all subscriptions for the user and group
    DELETE FROM groups.group_subscriptions gs
    WHERE gs.user_id = rem_group_mem.user_id
      AND gs.group_id = rem_group_mem.group_id;

    -- Step 4: Remove all related group notes (sent or received by the user)
    DELETE FROM groups.group_notes gn
    WHERE gn.group_id = rem_group_mem.group_id
      AND (gn.to_member_id = rem_group_mem.user_id OR gn.from_member_id = rem_group_mem.user_id);

    -- Step 5: Check if the user was the last member of the group
    IF NOT EXISTS (
        SELECT 1 FROM groups.group_members gm
        WHERE gm.group_id = rem_group_mem.group_id
    ) THEN
        -- Call the delete_group function to delete the group if no members remain
        PERFORM group_delete(rem_group_mem.group_id);
    END IF;
END;$function$
;


alter table "schools"."school_messages" add column "claire_prompts" jsonb;

alter table "schools"."school_messages" add column "journal_prompts" jsonb;

alter table "schools"."school_messages" add column "meditation" jsonb;

alter table "schools"."school_messages" add column "resources" jsonb;


