create table "programs"."program_assessment_responses" (
    "id" bigint generated by default as identity not null,
    "user_id" text not null default ''::text,
    "assessment" text not null,
    "responses" jsonb not null,
    "timestamp" timestamp with time zone not null default now()
);


alter table "programs"."program_assessment_responses" enable row level security;

create table "programs"."program_assessments" (
    "id" text not null,
    "desc" text not null,
    "program" text not null,
    "created_at" timestamp with time zone not null default now(),
    "question_ids" jsonb not null
);


alter table "programs"."program_assessments" enable row level security;

create table "programs"."program_feedback" (
    "id" bigint generated by default as identity not null,
    "title" text not null,
    "body" text not null,
    "program" text not null,
    "question_id" text,
    "question_response" text,
    "order" bigint,
    "links" jsonb
);


alter table "programs"."program_feedback" enable row level security;

create table "programs"."program_message_claire_prompts" (
    "id" bigint generated by default as identity not null,
    "message_id" bigint not null,
    "prompt_id" bigint not null
);


alter table "programs"."program_message_claire_prompts" enable row level security;

create table "programs"."program_message_journal_prompts" (
    "id" bigint generated by default as identity not null,
    "message_id" bigint not null,
    "prompt_id" bigint not null
);


alter table "programs"."program_message_journal_prompts" enable row level security;

create table "programs"."program_message_meditations" (
    "id" bigint generated by default as identity not null,
    "message_id" bigint not null,
    "meditation_id" bigint not null
);


alter table "programs"."program_message_meditations" enable row level security;

create table "programs"."program_message_page_info" (
    "id" bigint generated by default as identity not null,
    "title" text not null,
    "body" text not null,
    "message_id" bigint not null,
    "order" bigint not null
);


alter table "programs"."program_message_page_info" enable row level security;

create table "programs"."program_message_resources" (
    "id" bigint generated by default as identity not null,
    "message_id" bigint not null,
    "resource_id" bigint not null
);


alter table "programs"."program_message_resources" enable row level security;

create table "programs"."program_messages" (
    "id" bigint generated by default as identity not null,
    "day" bigint not null,
    "title" text not null,
    "subtitle" text not null,
    "body" text not null,
    "program" text not null,
    "question_id" text,
    "question_response" text
);


alter table "programs"."program_messages" enable row level security;

alter table "programs"."programs" enable row level security;

CREATE UNIQUE INDEX program_assessment_responses_pkey ON programs.program_assessment_responses USING btree (id);

CREATE UNIQUE INDEX program_assessments_pkey ON programs.program_assessments USING btree (id);

CREATE UNIQUE INDEX program_feedback_pkey ON programs.program_feedback USING btree (id);

CREATE UNIQUE INDEX program_message_claire_prompts_pkey ON programs.program_message_claire_prompts USING btree (id);

CREATE UNIQUE INDEX program_message_journal_prompts_pkey ON programs.program_message_journal_prompts USING btree (id);

CREATE UNIQUE INDEX program_message_meditations_pkey ON programs.program_message_meditations USING btree (id);

CREATE UNIQUE INDEX program_message_page_info_pkey ON programs.program_message_page_info USING btree (id);

CREATE UNIQUE INDEX program_message_resources_pkey ON programs.program_message_resources USING btree (id);

CREATE UNIQUE INDEX program_messages_pkey ON programs.program_messages USING btree (id);

alter table "programs"."program_assessment_responses" add constraint "program_assessment_responses_pkey" PRIMARY KEY using index "program_assessment_responses_pkey";

alter table "programs"."program_assessments" add constraint "program_assessments_pkey" PRIMARY KEY using index "program_assessments_pkey";

alter table "programs"."program_feedback" add constraint "program_feedback_pkey" PRIMARY KEY using index "program_feedback_pkey";

alter table "programs"."program_message_claire_prompts" add constraint "program_message_claire_prompts_pkey" PRIMARY KEY using index "program_message_claire_prompts_pkey";

alter table "programs"."program_message_journal_prompts" add constraint "program_message_journal_prompts_pkey" PRIMARY KEY using index "program_message_journal_prompts_pkey";

alter table "programs"."program_message_meditations" add constraint "program_message_meditations_pkey" PRIMARY KEY using index "program_message_meditations_pkey";

alter table "programs"."program_message_page_info" add constraint "program_message_page_info_pkey" PRIMARY KEY using index "program_message_page_info_pkey";

alter table "programs"."program_message_resources" add constraint "program_message_resources_pkey" PRIMARY KEY using index "program_message_resources_pkey";

alter table "programs"."program_messages" add constraint "program_messages_pkey" PRIMARY KEY using index "program_messages_pkey";

alter table "programs"."program_assessment_responses" add constraint "program_assessment_responses_assessment_fkey" FOREIGN KEY (assessment) REFERENCES programs.program_assessments(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "programs"."program_assessment_responses" validate constraint "program_assessment_responses_assessment_fkey";

alter table "programs"."program_assessment_responses" add constraint "program_assessment_responses_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "programs"."program_assessment_responses" validate constraint "program_assessment_responses_user_id_fkey";

alter table "programs"."program_assessments" add constraint "program_assessments_program_fkey" FOREIGN KEY (program) REFERENCES programs.programs(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "programs"."program_assessments" validate constraint "program_assessments_program_fkey";

alter table "programs"."program_feedback" add constraint "program_feedback_program_fkey" FOREIGN KEY (program) REFERENCES programs.programs(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "programs"."program_feedback" validate constraint "program_feedback_program_fkey";

alter table "programs"."program_message_claire_prompts" add constraint "program_message_claire_prompts_message_id_fkey" FOREIGN KEY (message_id) REFERENCES programs.program_messages(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "programs"."program_message_claire_prompts" validate constraint "program_message_claire_prompts_message_id_fkey";

alter table "programs"."program_message_claire_prompts" add constraint "program_message_claire_prompts_prompt_id_fkey" FOREIGN KEY (prompt_id) REFERENCES library.claire_prompts(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "programs"."program_message_claire_prompts" validate constraint "program_message_claire_prompts_prompt_id_fkey";

alter table "programs"."program_message_journal_prompts" add constraint "program_message_journal_prompts_message_id_fkey" FOREIGN KEY (message_id) REFERENCES programs.program_messages(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "programs"."program_message_journal_prompts" validate constraint "program_message_journal_prompts_message_id_fkey";

alter table "programs"."program_message_journal_prompts" add constraint "program_message_journal_prompts_prompt_id_fkey" FOREIGN KEY (prompt_id) REFERENCES library.journal_prompts(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "programs"."program_message_journal_prompts" validate constraint "program_message_journal_prompts_prompt_id_fkey";

alter table "programs"."program_message_meditations" add constraint "program_message_meditations_meditation_id_fkey" FOREIGN KEY (meditation_id) REFERENCES library.meditations(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "programs"."program_message_meditations" validate constraint "program_message_meditations_meditation_id_fkey";

alter table "programs"."program_message_meditations" add constraint "program_message_meditations_message_id_fkey" FOREIGN KEY (message_id) REFERENCES programs.program_messages(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "programs"."program_message_meditations" validate constraint "program_message_meditations_message_id_fkey";

alter table "programs"."program_message_page_info" add constraint "program_message_page_info_message_id_fkey" FOREIGN KEY (message_id) REFERENCES programs.program_messages(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "programs"."program_message_page_info" validate constraint "program_message_page_info_message_id_fkey";

alter table "programs"."program_message_resources" add constraint "program_message_resources_message_id_fkey" FOREIGN KEY (message_id) REFERENCES programs.program_messages(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "programs"."program_message_resources" validate constraint "program_message_resources_message_id_fkey";

alter table "programs"."program_message_resources" add constraint "program_message_resources_resource_id_fkey" FOREIGN KEY (resource_id) REFERENCES library.resources(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "programs"."program_message_resources" validate constraint "program_message_resources_resource_id_fkey";

alter table "programs"."program_messages" add constraint "program_messages_program_fkey" FOREIGN KEY (program) REFERENCES programs.programs(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "programs"."program_messages" validate constraint "program_messages_program_fkey";

create policy "Disable access for all"
on "programs"."program_assessment_responses"
as permissive
for all
to public
using (false);


create policy "Disable access for all"
on "programs"."program_assessments"
as permissive
for all
to public
using (false);


create policy "Disable access for all"
on "programs"."program_feedback"
as permissive
for select
to public
using (false);


create policy "Disable access for all"
on "programs"."program_message_claire_prompts"
as permissive
for select
to public
using (false);


create policy "Disable access for all"
on "programs"."program_message_journal_prompts"
as permissive
for select
to public
using (false);


create policy "Disable access for all"
on "programs"."program_message_meditations"
as permissive
for select
to public
using (false);


create policy "Disable access for all"
on "programs"."program_message_page_info"
as permissive
for select
to public
using (false);


create policy "Disable access for all"
on "programs"."program_message_resources"
as permissive
for select
to public
using (false);


create policy "Disable access for all"
on "programs"."program_messages"
as permissive
for select
to public
using (false);


create policy "Disable access for all"
on "programs"."programs"
as permissive
for select
to public
using (false);



set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.get_feedback(user_id text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    recent_assessment RECORD;
    feedback JSONB := '[]';
BEGIN
    -- Step 1: Find the most recent assessment response for the user
    SELECT ar.assessment, pa.program, ar.responses
    INTO recent_assessment
    FROM programs.program_assessment_responses ar
    JOIN programs.program_assessments pa ON ar.assessment = pa.id
    WHERE ar.user_id = get_feedback.user_id
    ORDER BY ar.timestamp DESC
    LIMIT 1;

    -- Ensure a recent assessment exists
    IF recent_assessment IS NULL THEN
        RAISE EXCEPTION 'No assessments found for user %', user_id;
    END IF;

    -- Step 2: Fetch feedback for the associated program, applying filters and ordering
    SELECT jsonb_agg(feedback_data)
    INTO feedback
    FROM (
        SELECT jsonb_build_object(
            'title', af.title,
            'body', af.body,
            'links', af.links
        ) AS feedback_data
        FROM programs.program_feedback af
        WHERE af.program = recent_assessment.program
        AND (
            af.question_id IS NULL
            OR (
                af.question_id IS NOT NULL
                AND (
                    jsonb_typeof(recent_assessment.responses -> af.question_id) = 'string'
                    AND af.question_response = recent_assessment.responses ->> af.question_id
                )
                OR (
                    jsonb_typeof(recent_assessment.responses -> af.question_id) = 'array'
                    AND af.question_response = ANY (
                        SELECT jsonb_array_elements_text(recent_assessment.responses -> af.question_id)
                    )
                )
            )
        )
        ORDER BY af.order ASC
    ) subquery;

    -- Return the formatted feedback
    RETURN jsonb_build_object('feedback', COALESCE(feedback, '[]'::JSONB));
END;
$function$
;

CREATE OR REPLACE FUNCTION public.get_messages(user_id text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    recent_assessment RECORD;
    messages JSONB := '[]';
BEGIN
    -- Step 1: Find the most recent assessment response for the user
    SELECT ar.assessment, pa.program, ar.responses
    INTO recent_assessment
    FROM programs.program_assessment_responses ar
    JOIN programs.program_assessments pa ON ar.assessment = pa.id
    WHERE ar.user_id = get_messages.user_id
    ORDER BY ar.timestamp DESC
    LIMIT 1;

    -- Ensure a recent assessment exists
    IF recent_assessment IS NULL THEN
        RAISE EXCEPTION 'No assessments found for user %', user_id;
    END IF;

    -- Step 2: Fetch program messages for the associated program, applying filters and ordering
    SELECT jsonb_agg(message_data)
    INTO messages
    FROM (
        SELECT jsonb_build_object(
            'day', pm.day,
            'title', pm.title,
            'subtitle', pm.subtitle,
            'body', pm.body,
            'claire_prompts', (
                SELECT COALESCE(
                    jsonb_object_agg(cp.title, cp.prompt),
                    '{}'
                )
                FROM programs.program_message_claire_prompts pmcp
                JOIN library.claire_prompts cp ON pmcp.prompt_id = cp.id
                WHERE pmcp.message_id = pm.id
            ),
            'journal_prompts', (
                SELECT COALESCE(
                    jsonb_agg(jp.prompt),
                    '[]'
                )
                FROM programs.program_message_journal_prompts pmjp
                JOIN library.journal_prompts jp ON pmjp.prompt_id = jp.id
                WHERE pmjp.message_id = pm.id
            ),
            'resources', (
                SELECT COALESCE(
                    jsonb_object_agg(r.title, r.url),
                    '{}'
                )
                FROM programs.program_message_resources pmr
                JOIN library.resources r ON pmr.resource_id = r.id
                WHERE pmr.message_id = pm.id
            ),
            'meditation', (
                SELECT COALESCE(
                    jsonb_build_object(
                        'meditation_title', m.title,
                        'meditation_link', m.url
                    ),
                    '{}'
                )
                FROM programs.program_message_meditations pmm
                JOIN library.meditations m ON pmm.meditation_id = m.id
                WHERE pmm.message_id = pm.id
            )
        ) AS message_data
        FROM programs.program_messages pm
        WHERE pm.program = recent_assessment.program
        AND (
            pm.question_id IS NULL
            OR (
                pm.question_id IS NOT NULL
                AND (
                    -- Case 1: The response is a string and matches question_response
                    jsonb_typeof(recent_assessment.responses -> pm.question_id) = 'string'
                    AND pm.question_response = recent_assessment.responses ->> pm.question_id
                )
                OR (
                    -- Case 2: The response is an array and contains question_response
                    jsonb_typeof(recent_assessment.responses -> pm.question_id) = 'array'
                    AND pm.question_response = ANY (
                        SELECT jsonb_array_elements_text(recent_assessment.responses -> pm.question_id)
                    )
                )
            )
        )
        ORDER BY pm.day ASC, 
                 pm.question_id IS NOT NULL -- NULLs come first
    ) subquery;

    -- Return the formatted messages
    RETURN jsonb_build_object('messages', COALESCE(messages, '[]'::JSONB));
END;
$function$
;

CREATE OR REPLACE FUNCTION public.submit_assessment_response(user_id text, assessment_id text, responses jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    valid_question_ids JSONB;
    filtered_responses JSONB := '{}';
BEGIN
    -- Ensure the user_id exists
    IF NOT EXISTS (SELECT 1 FROM public.users WHERE id = user_id) THEN
        RAISE EXCEPTION 'User with ID % does not exist', user_id;
    END IF;

    -- Ensure the assessment exists
    IF NOT EXISTS (SELECT 1 FROM programs.program_assessments WHERE id = assessment_id) THEN
        RAISE EXCEPTION 'Assessment with ID % does not exist', assessment_id;
    END IF;

    -- Get valid question IDs from the programs.program_assessments table
    SELECT question_ids
    INTO valid_question_ids
    FROM programs.program_assessments
    WHERE id = assessment_id;

    -- Filter the input JSON for valid question IDs
    SELECT jsonb_object_agg(key, value)
    INTO filtered_responses
    FROM jsonb_each(responses)
    WHERE key = ANY (SELECT jsonb_array_elements_text(valid_question_ids));

    -- Insert into the AssessmentResponses table
    INSERT INTO programs.program_assessment_responses (
        user_id, assessment, responses
    )
    VALUES (
        user_id, assessment_id, filtered_responses
    );

END;
$function$
;


