create schema if not exists "library";

create table "library"."cache" (
    "type" text not null,
    "json" json not null,
    "last_updated" timestamp with time zone not null default now()
);


alter table "library"."cache" enable row level security;

create table "library"."claire_prompts" (
    "id" bigint generated by default as identity not null,
    "title" text not null,
    "prompt" text not null
);


alter table "library"."claire_prompts" enable row level security;

create table "library"."journal_prompts" (
    "id" bigint generated by default as identity not null,
    "prompt" text not null
);


alter table "library"."journal_prompts" enable row level security;

create table "library"."meditations" (
    "id" bigint generated by default as identity not null,
    "title" text not null,
    "url" text not null
);


alter table "library"."meditations" enable row level security;

create table "library"."resources" (
    "id" bigint generated by default as identity not null,
    "title" text not null,
    "url" text not null
);


alter table "library"."resources" enable row level security;

CREATE UNIQUE INDEX cache_pkey ON library.cache USING btree (type);

CREATE UNIQUE INDEX claire_prompts_pkey ON library.claire_prompts USING btree (id);

CREATE UNIQUE INDEX journal_prompts_pkey ON library.journal_prompts USING btree (id);

CREATE UNIQUE INDEX meditations_pkey ON library.meditations USING btree (id);

CREATE UNIQUE INDEX resources_pkey ON library.resources USING btree (id);

alter table "library"."cache" add constraint "cache_pkey" PRIMARY KEY using index "cache_pkey";

alter table "library"."claire_prompts" add constraint "claire_prompts_pkey" PRIMARY KEY using index "claire_prompts_pkey";

alter table "library"."journal_prompts" add constraint "journal_prompts_pkey" PRIMARY KEY using index "journal_prompts_pkey";

alter table "library"."meditations" add constraint "meditations_pkey" PRIMARY KEY using index "meditations_pkey";

alter table "library"."resources" add constraint "resources_pkey" PRIMARY KEY using index "resources_pkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION library.get_symptom_infos()
 RETURNS json
 LANGUAGE plpgsql
AS $function$
DECLARE
    result TEXT := '{';  -- Initialize result as a JSON string starting with an opening brace
    first_entry BOOLEAN := TRUE;  -- To track whether it's the first entry to avoid trailing commas
    record RECORD;
    tip_record RECORD;  -- Declare tip_record as a RECORD
    section_record RECORD;  -- Declare section_record as a RECORD
    reddit_record RECORD;  -- Declare reddit_record as a RECORD
    prompt_record RECORD;  -- Declare prompt_record as a RECORD
    tips_array TEXT;
    sections_array TEXT;
    reddits TEXT;
    prompts TEXT;
    first_tip BOOLEAN;
    first_section BOOLEAN;
    first_reddit BOOLEAN;
    first_prompt BOOLEAN;
    cached_result JSONB;  -- Holds the cached JSON from the cache table
    cache_key CONSTANT TEXT := 'symptom_infos';  -- Key for this cache entry
BEGIN
    -- Step 1: Check if the cache already has a value for "symptom_infos"
    SELECT json INTO cached_result
    FROM library.cache
    WHERE type = cache_key;

    -- Step 2: If the cached JSON is not NULL, return the cached result
    IF cached_result IS NOT NULL THEN
        RETURN cached_result;
    END IF;

    -- Step 3: If no cached result or it's NULL, compute the new JSON result
    -- Loop through each symptom and gather the colors, tips, reddit threads, and prompts for that symptom
    FOR record IN 
        SELECT s.emoji || ' ' || s.symptom AS symptom_key, s.symptom, s.color1, s.color2
        FROM symptoms.symptoms s
        LEFT JOIN symptoms.symptom_tips st ON s.symptom = st.symptom
        GROUP BY s.emoji, s.symptom, st.color1, st.color2
        ORDER BY s.symptom
    LOOP
        -- Initialize tips array for the current symptom
        tips_array := '[';
        first_tip := TRUE;

        -- Get all tips for the current symptom by matching the symptom name
        FOR tip_record IN
            SELECT st.id, st.title, st.color1, st.color2
            FROM symptoms.symptom_tips st
            WHERE st.symptom = record.symptom
        LOOP
            -- Initialize sections array for the current tip
            sections_array := '[';
            first_section := TRUE;

            -- Get all sections for the current tip
            FOR section_record IN
                SELECT sts.heading, sts.content, sts.example
                FROM symptoms.symptom_tip_sections sts
                WHERE sts.symptom_tip = tip_record.id
            LOOP
                -- Handle commas between sections
                IF NOT first_section THEN
                    sections_array := sections_array || ', ';
                END IF;

                -- Add each section with heading, content, and possibly example, using to_json to escape text
                sections_array := sections_array || '{"heading": ' || to_json(section_record.heading) || ', "content": ' || to_json(section_record.content);

                -- Add example if it's not NULL
                IF section_record.example IS NOT NULL THEN
                    sections_array := sections_array || ', "example": ' || to_json(section_record.example);
                END IF;

                -- Close the section object
                sections_array := sections_array || '}';

                -- Mark that this is no longer the first section
                first_section := FALSE;
            END LOOP;

            -- Close the sections array
            sections_array := sections_array || ']';

            -- Handle commas between tips
            IF NOT first_tip THEN
                tips_array := tips_array || ', ';
            END IF;

            -- Add each tip to the tips array with title, colors, and sections, using to_json to escape text
            tips_array := tips_array || '{"title": ' || to_json(tip_record.title) || ', "color1": ' || to_json(tip_record.color1) || ', "color2": ' || to_json(tip_record.color2) || ', "sections": ' || sections_array || '}';

            -- Mark that this is no longer the first tip
            first_tip := FALSE;
        END LOOP;

        -- Close the tips array
        tips_array := tips_array || ']';

        -- Initialize the reddit threads for the current symptom
        reddits := '{';
        first_reddit := TRUE;

        -- Get all Reddit threads for the current symptom using the join table
        FOR reddit_record IN
            SELECT r.title, r.url
            FROM symptoms.symptom_reddit_threads srt
            JOIN library.resources r ON r.id = srt.resource
            WHERE srt.symptom = record.symptom
        LOOP
            -- Handle commas between reddit entries
            IF NOT first_reddit THEN
                reddits := reddits || ', ';
            END IF;

            -- Add the reddit thread with title as key and url as value
            reddits := reddits || to_json(reddit_record.title) || ': ' || to_json(reddit_record.url);

            -- Mark that this is no longer the first reddit entry
            first_reddit := FALSE;
        END LOOP;

        -- Close the reddit threads object
        reddits := reddits || '}';

        -- Initialize the prompts for the current symptom
        prompts := '{';
        first_prompt := TRUE;

        -- Get all Claire prompts for the current symptom using the join table
        FOR prompt_record IN
            SELECT cp.title, cp.prompt
            FROM symptoms.symptom_claire_prompts scp
            JOIN library.claire_prompts cp ON cp.id = scp.claire_prompt
            WHERE scp.symptom = record.symptom
        LOOP
            -- Handle commas between prompt entries
            IF NOT first_prompt THEN
                prompts := prompts || ', ';
            END IF;

            -- Add the prompt with title as key and prompt as value
            prompts := prompts || to_json(prompt_record.title) || ': ' || to_json(prompt_record.prompt);

            -- Mark that this is no longer the first prompt entry
            first_prompt := FALSE;
        END LOOP;

        -- Close the prompts object
        prompts := prompts || '}';

        -- Handle commas between symptom entries
        IF NOT first_entry THEN
            result := result || ', ';
        END IF;

        -- Add the symptom's colors, tips, reddits, and prompts to the result
        result := result || '"' || record.symptom_key || '": {"color1": ' || to_json(record.color1) || ', "color2": ' || to_json(record.color2) || ', "tips": ' || tips_array || ', "reddits": ' || reddits || ', "prompts": ' || prompts || '}';

        -- Mark that this is no longer the first entry
        first_entry := FALSE;
    END LOOP;

    -- Close the JSON object with a closing brace
    result := result || '}';

    -- Step 4: Store the computed result in the cache table
    INSERT INTO library.cache (type, json, last_updated)
    VALUES (cache_key, result::JSON, NOW())
    ON CONFLICT (type) DO UPDATE
    SET json = EXCLUDED.json, last_updated = NOW();

    -- Step 5: Return the newly computed JSON
    RETURN result::JSON;
END;
$function$
;

grant delete on table "library"."cache" to "anon";

grant insert on table "library"."cache" to "anon";

grant references on table "library"."cache" to "anon";

grant select on table "library"."cache" to "anon";

grant trigger on table "library"."cache" to "anon";

grant truncate on table "library"."cache" to "anon";

grant update on table "library"."cache" to "anon";

grant delete on table "library"."cache" to "authenticated";

grant insert on table "library"."cache" to "authenticated";

grant references on table "library"."cache" to "authenticated";

grant select on table "library"."cache" to "authenticated";

grant trigger on table "library"."cache" to "authenticated";

grant truncate on table "library"."cache" to "authenticated";

grant update on table "library"."cache" to "authenticated";

grant delete on table "library"."claire_prompts" to "anon";

grant insert on table "library"."claire_prompts" to "anon";

grant references on table "library"."claire_prompts" to "anon";

grant select on table "library"."claire_prompts" to "anon";

grant trigger on table "library"."claire_prompts" to "anon";

grant truncate on table "library"."claire_prompts" to "anon";

grant update on table "library"."claire_prompts" to "anon";

grant delete on table "library"."claire_prompts" to "authenticated";

grant insert on table "library"."claire_prompts" to "authenticated";

grant references on table "library"."claire_prompts" to "authenticated";

grant select on table "library"."claire_prompts" to "authenticated";

grant trigger on table "library"."claire_prompts" to "authenticated";

grant truncate on table "library"."claire_prompts" to "authenticated";

grant update on table "library"."claire_prompts" to "authenticated";

grant delete on table "library"."journal_prompts" to "anon";

grant insert on table "library"."journal_prompts" to "anon";

grant references on table "library"."journal_prompts" to "anon";

grant select on table "library"."journal_prompts" to "anon";

grant trigger on table "library"."journal_prompts" to "anon";

grant truncate on table "library"."journal_prompts" to "anon";

grant update on table "library"."journal_prompts" to "anon";

grant delete on table "library"."journal_prompts" to "authenticated";

grant insert on table "library"."journal_prompts" to "authenticated";

grant references on table "library"."journal_prompts" to "authenticated";

grant select on table "library"."journal_prompts" to "authenticated";

grant trigger on table "library"."journal_prompts" to "authenticated";

grant truncate on table "library"."journal_prompts" to "authenticated";

grant update on table "library"."journal_prompts" to "authenticated";

grant delete on table "library"."meditations" to "anon";

grant insert on table "library"."meditations" to "anon";

grant references on table "library"."meditations" to "anon";

grant select on table "library"."meditations" to "anon";

grant trigger on table "library"."meditations" to "anon";

grant truncate on table "library"."meditations" to "anon";

grant update on table "library"."meditations" to "anon";

grant delete on table "library"."meditations" to "authenticated";

grant insert on table "library"."meditations" to "authenticated";

grant references on table "library"."meditations" to "authenticated";

grant select on table "library"."meditations" to "authenticated";

grant trigger on table "library"."meditations" to "authenticated";

grant truncate on table "library"."meditations" to "authenticated";

grant update on table "library"."meditations" to "authenticated";

grant delete on table "library"."resources" to "anon";

grant insert on table "library"."resources" to "anon";

grant references on table "library"."resources" to "anon";

grant select on table "library"."resources" to "anon";

grant trigger on table "library"."resources" to "anon";

grant truncate on table "library"."resources" to "anon";

grant update on table "library"."resources" to "anon";

grant delete on table "library"."resources" to "authenticated";

grant insert on table "library"."resources" to "authenticated";

grant references on table "library"."resources" to "authenticated";

grant select on table "library"."resources" to "authenticated";

grant trigger on table "library"."resources" to "authenticated";

grant truncate on table "library"."resources" to "authenticated";

grant update on table "library"."resources" to "authenticated";

create policy "Enable read access for all users"
on "library"."cache"
as permissive
for select
to public
using (true);


create policy "Enable read access for all users"
on "library"."claire_prompts"
as permissive
for select
to public
using (true);


create policy "Enable read access for all users"
on "library"."journal_prompts"
as permissive
for select
to public
using (true);


create policy "Enable read access for all users"
on "library"."meditations"
as permissive
for select
to public
using (true);


create policy "Enable read access for all users"
on "library"."resources"
as permissive
for select
to public
using (true);



set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.get_symptom_infos()
 RETURNS json
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    result TEXT := '{';  -- Initialize result as a JSON string starting with an opening brace
    first_entry BOOLEAN := TRUE;  -- To track whether it's the first entry to avoid trailing commas
    record RECORD;
    tip_record RECORD;  -- Declare tip_record as a RECORD
    section_record RECORD;  -- Declare section_record as a RECORD
    reddit_record RECORD;  -- Declare reddit_record as a RECORD
    prompt_record RECORD;  -- Declare prompt_record as a RECORD
    tips_array TEXT;
    sections_array TEXT;
    reddits TEXT;
    prompts TEXT;
    first_tip BOOLEAN;
    first_section BOOLEAN;
    first_reddit BOOLEAN;
    first_prompt BOOLEAN;
    cached_result JSONB;  -- Holds the cached JSON from the cache table
    cache_key CONSTANT TEXT := 'symptom_infos';  -- Key for this cache entry
BEGIN
    -- Step 1: Check if the cache already has a value for "symptom_infos"
    SELECT json INTO cached_result
    FROM library.cache
    WHERE type = cache_key;

    -- Step 2: If the cached JSON is not NULL, return the cached result
    IF cached_result IS NOT NULL THEN
        RETURN cached_result;
    END IF;

    -- Step 3: If no cached result or it's NULL, compute the new JSON result
    -- Loop through each symptom and gather the colors, tips, reddit threads, and prompts for that symptom
    FOR record IN 
        SELECT s.emoji || ' ' || s.symptom AS symptom_key, s.symptom, s.color1, s.color2
        FROM symptoms.symptoms s
        LEFT JOIN symptoms.symptom_tips st ON s.symptom = st.symptom
        GROUP BY s.emoji, s.symptom, st.color1, st.color2
        ORDER BY s.symptom
    LOOP
        -- Initialize tips array for the current symptom
        tips_array := '[';
        first_tip := TRUE;

        -- Get all tips for the current symptom by matching the symptom name
        FOR tip_record IN
            SELECT st.id, st.title, st.color1, st.color2
            FROM symptoms.symptom_tips st
            WHERE st.symptom = record.symptom
        LOOP
            -- Initialize sections array for the current tip
            sections_array := '[';
            first_section := TRUE;

            -- Get all sections for the current tip
            FOR section_record IN
                SELECT sts.heading, sts.content, sts.example
                FROM symptoms.symptom_tip_sections sts
                WHERE sts.symptom_tip = tip_record.id
            LOOP
                -- Handle commas between sections
                IF NOT first_section THEN
                    sections_array := sections_array || ', ';
                END IF;

                -- Add each section with heading, content, and possibly example, using to_json to escape text
                sections_array := sections_array || '{"heading": ' || to_json(section_record.heading) || ', "content": ' || to_json(section_record.content);

                -- Add example if it's not NULL
                IF section_record.example IS NOT NULL THEN
                    sections_array := sections_array || ', "example": ' || to_json(section_record.example);
                END IF;

                -- Close the section object
                sections_array := sections_array || '}';

                -- Mark that this is no longer the first section
                first_section := FALSE;
            END LOOP;

            -- Close the sections array
            sections_array := sections_array || ']';

            -- Handle commas between tips
            IF NOT first_tip THEN
                tips_array := tips_array || ', ';
            END IF;

            -- Add each tip to the tips array with title, colors, and sections, using to_json to escape text
            tips_array := tips_array || '{"title": ' || to_json(tip_record.title) || ', "color1": ' || to_json(tip_record.color1) || ', "color2": ' || to_json(tip_record.color2) || ', "sections": ' || sections_array || '}';

            -- Mark that this is no longer the first tip
            first_tip := FALSE;
        END LOOP;

        -- Close the tips array
        tips_array := tips_array || ']';

        -- Initialize the reddit threads for the current symptom
        reddits := '{';
        first_reddit := TRUE;

        -- Get all Reddit threads for the current symptom using the join table
        FOR reddit_record IN
            SELECT r.title, r.url
            FROM symptoms.symptom_reddit_threads srt
            JOIN library.resources r ON r.id = srt.resource
            WHERE srt.symptom = record.symptom
        LOOP
            -- Handle commas between reddit entries
            IF NOT first_reddit THEN
                reddits := reddits || ', ';
            END IF;

            -- Add the reddit thread with title as key and url as value
            reddits := reddits || to_json(reddit_record.title) || ': ' || to_json(reddit_record.url);

            -- Mark that this is no longer the first reddit entry
            first_reddit := FALSE;
        END LOOP;

        -- Close the reddit threads object
        reddits := reddits || '}';

        -- Initialize the prompts for the current symptom
        prompts := '{';
        first_prompt := TRUE;

        -- Get all Claire prompts for the current symptom using the join table
        FOR prompt_record IN
            SELECT cp.title, cp.prompt
            FROM symptoms.symptom_claire_prompts scp
            JOIN library.claire_prompts cp ON cp.id = scp.claire_prompt
            WHERE scp.symptom = record.symptom
        LOOP
            -- Handle commas between prompt entries
            IF NOT first_prompt THEN
                prompts := prompts || ', ';
            END IF;

            -- Add the prompt with title as key and prompt as value
            prompts := prompts || to_json(prompt_record.title) || ': ' || to_json(prompt_record.prompt);

            -- Mark that this is no longer the first prompt entry
            first_prompt := FALSE;
        END LOOP;

        -- Close the prompts object
        prompts := prompts || '}';

        -- Handle commas between symptom entries
        IF NOT first_entry THEN
            result := result || ', ';
        END IF;

        -- Add the symptom's colors, tips, reddits, and prompts to the result
        result := result || '"' || record.symptom_key || '": {"color1": ' || to_json(record.color1) || ', "color2": ' || to_json(record.color2) || ', "tips": ' || tips_array || ', "reddits": ' || reddits || ', "prompts": ' || prompts || '}';

        -- Mark that this is no longer the first entry
        first_entry := FALSE;
    END LOOP;

    -- Close the JSON object with a closing brace
    result := result || '}';

    -- Step 4: Store the computed result in the cache table
    INSERT INTO library.cache (type, json, last_updated)
    VALUES (cache_key, result::JSON, NOW())
    ON CONFLICT (type) DO UPDATE
    SET json = EXCLUDED.json, last_updated = NOW();

    -- Step 5: Return the newly computed JSON
    RETURN result::JSON;
END;
$function$
;


create schema if not exists "symptoms";

create table "symptoms"."symptom_claire_prompts" (
    "id" bigint generated by default as identity not null,
    "symptom" text not null default ''::text,
    "claire_prompt" bigint not null
);


alter table "symptoms"."symptom_claire_prompts" enable row level security;

create table "symptoms"."symptom_messages" (
    "symptom" text not null,
    "message" text not null
);


alter table "symptoms"."symptom_messages" enable row level security;

create table "symptoms"."symptom_reddit_threads" (
    "id" bigint generated by default as identity not null,
    "symptom" text not null default ''::text,
    "resource" bigint not null
);


alter table "symptoms"."symptom_reddit_threads" enable row level security;

create table "symptoms"."symptom_tip_sections" (
    "id" bigint generated by default as identity not null,
    "symptom_tip" bigint not null,
    "heading" text not null,
    "content" text not null,
    "example" text
);


alter table "symptoms"."symptom_tip_sections" enable row level security;

create table "symptoms"."symptom_tips" (
    "id" bigint generated by default as identity not null,
    "title" text not null,
    "color1" text not null,
    "color2" text not null,
    "symptom" text not null
);


alter table "symptoms"."symptom_tips" enable row level security;

create table "symptoms"."symptoms" (
    "symptom" text not null,
    "color1" text not null,
    "color2" text not null,
    "emoji" text not null
);


alter table "symptoms"."symptoms" enable row level security;

CREATE UNIQUE INDEX symptom_claire_prompts_pkey ON symptoms.symptom_claire_prompts USING btree (id);

CREATE UNIQUE INDEX symptom_messages_pkey ON symptoms.symptom_messages USING btree (symptom, message);

CREATE UNIQUE INDEX symptom_reddit_threads_pkey ON symptoms.symptom_reddit_threads USING btree (id);

CREATE UNIQUE INDEX symptom_tip_sections_pkey ON symptoms.symptom_tip_sections USING btree (id);

CREATE UNIQUE INDEX symptom_tips_pkey ON symptoms.symptom_tips USING btree (id);

CREATE UNIQUE INDEX symptoms_pkey ON symptoms.symptoms USING btree (symptom);

alter table "symptoms"."symptom_claire_prompts" add constraint "symptom_claire_prompts_pkey" PRIMARY KEY using index "symptom_claire_prompts_pkey";

alter table "symptoms"."symptom_messages" add constraint "symptom_messages_pkey" PRIMARY KEY using index "symptom_messages_pkey";

alter table "symptoms"."symptom_reddit_threads" add constraint "symptom_reddit_threads_pkey" PRIMARY KEY using index "symptom_reddit_threads_pkey";

alter table "symptoms"."symptom_tip_sections" add constraint "symptom_tip_sections_pkey" PRIMARY KEY using index "symptom_tip_sections_pkey";

alter table "symptoms"."symptom_tips" add constraint "symptom_tips_pkey" PRIMARY KEY using index "symptom_tips_pkey";

alter table "symptoms"."symptoms" add constraint "symptoms_pkey" PRIMARY KEY using index "symptoms_pkey";

alter table "symptoms"."symptom_claire_prompts" add constraint "symptom_claire_prompts_claire_prompt_fkey" FOREIGN KEY (claire_prompt) REFERENCES library.claire_prompts(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "symptoms"."symptom_claire_prompts" validate constraint "symptom_claire_prompts_claire_prompt_fkey";

alter table "symptoms"."symptom_claire_prompts" add constraint "symptom_claire_prompts_symptom_fkey" FOREIGN KEY (symptom) REFERENCES symptoms.symptoms(symptom) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "symptoms"."symptom_claire_prompts" validate constraint "symptom_claire_prompts_symptom_fkey";

alter table "symptoms"."symptom_messages" add constraint "symptom_messages_symptom_fkey1" FOREIGN KEY (symptom) REFERENCES symptoms.symptoms(symptom) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "symptoms"."symptom_messages" validate constraint "symptom_messages_symptom_fkey1";

alter table "symptoms"."symptom_reddit_threads" add constraint "symptom_reddit_threads_resource_fkey" FOREIGN KEY (resource) REFERENCES library.resources(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "symptoms"."symptom_reddit_threads" validate constraint "symptom_reddit_threads_resource_fkey";

alter table "symptoms"."symptom_reddit_threads" add constraint "symptom_reddit_threads_symptom_fkey" FOREIGN KEY (symptom) REFERENCES symptoms.symptoms(symptom) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "symptoms"."symptom_reddit_threads" validate constraint "symptom_reddit_threads_symptom_fkey";

alter table "symptoms"."symptom_tip_sections" add constraint "symptom_tip_sections_symptom_tip_fkey1" FOREIGN KEY (symptom_tip) REFERENCES symptoms.symptom_tips(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "symptoms"."symptom_tip_sections" validate constraint "symptom_tip_sections_symptom_tip_fkey1";

alter table "symptoms"."symptom_tips" add constraint "symptom_tips_symptom_fkey1" FOREIGN KEY (symptom) REFERENCES symptoms.symptoms(symptom) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "symptoms"."symptom_tips" validate constraint "symptom_tips_symptom_fkey1";

grant delete on table "symptoms"."symptom_claire_prompts" to "anon";

grant insert on table "symptoms"."symptom_claire_prompts" to "anon";

grant references on table "symptoms"."symptom_claire_prompts" to "anon";

grant select on table "symptoms"."symptom_claire_prompts" to "anon";

grant trigger on table "symptoms"."symptom_claire_prompts" to "anon";

grant truncate on table "symptoms"."symptom_claire_prompts" to "anon";

grant update on table "symptoms"."symptom_claire_prompts" to "anon";

grant delete on table "symptoms"."symptom_claire_prompts" to "authenticated";

grant insert on table "symptoms"."symptom_claire_prompts" to "authenticated";

grant references on table "symptoms"."symptom_claire_prompts" to "authenticated";

grant select on table "symptoms"."symptom_claire_prompts" to "authenticated";

grant trigger on table "symptoms"."symptom_claire_prompts" to "authenticated";

grant truncate on table "symptoms"."symptom_claire_prompts" to "authenticated";

grant update on table "symptoms"."symptom_claire_prompts" to "authenticated";

grant delete on table "symptoms"."symptom_messages" to "anon";

grant insert on table "symptoms"."symptom_messages" to "anon";

grant references on table "symptoms"."symptom_messages" to "anon";

grant select on table "symptoms"."symptom_messages" to "anon";

grant trigger on table "symptoms"."symptom_messages" to "anon";

grant truncate on table "symptoms"."symptom_messages" to "anon";

grant update on table "symptoms"."symptom_messages" to "anon";

grant delete on table "symptoms"."symptom_messages" to "authenticated";

grant insert on table "symptoms"."symptom_messages" to "authenticated";

grant references on table "symptoms"."symptom_messages" to "authenticated";

grant select on table "symptoms"."symptom_messages" to "authenticated";

grant trigger on table "symptoms"."symptom_messages" to "authenticated";

grant truncate on table "symptoms"."symptom_messages" to "authenticated";

grant update on table "symptoms"."symptom_messages" to "authenticated";

grant delete on table "symptoms"."symptom_reddit_threads" to "anon";

grant insert on table "symptoms"."symptom_reddit_threads" to "anon";

grant references on table "symptoms"."symptom_reddit_threads" to "anon";

grant select on table "symptoms"."symptom_reddit_threads" to "anon";

grant trigger on table "symptoms"."symptom_reddit_threads" to "anon";

grant truncate on table "symptoms"."symptom_reddit_threads" to "anon";

grant update on table "symptoms"."symptom_reddit_threads" to "anon";

grant delete on table "symptoms"."symptom_reddit_threads" to "authenticated";

grant insert on table "symptoms"."symptom_reddit_threads" to "authenticated";

grant references on table "symptoms"."symptom_reddit_threads" to "authenticated";

grant select on table "symptoms"."symptom_reddit_threads" to "authenticated";

grant trigger on table "symptoms"."symptom_reddit_threads" to "authenticated";

grant truncate on table "symptoms"."symptom_reddit_threads" to "authenticated";

grant update on table "symptoms"."symptom_reddit_threads" to "authenticated";

grant delete on table "symptoms"."symptom_tip_sections" to "anon";

grant insert on table "symptoms"."symptom_tip_sections" to "anon";

grant references on table "symptoms"."symptom_tip_sections" to "anon";

grant select on table "symptoms"."symptom_tip_sections" to "anon";

grant trigger on table "symptoms"."symptom_tip_sections" to "anon";

grant truncate on table "symptoms"."symptom_tip_sections" to "anon";

grant update on table "symptoms"."symptom_tip_sections" to "anon";

grant delete on table "symptoms"."symptom_tip_sections" to "authenticated";

grant insert on table "symptoms"."symptom_tip_sections" to "authenticated";

grant references on table "symptoms"."symptom_tip_sections" to "authenticated";

grant select on table "symptoms"."symptom_tip_sections" to "authenticated";

grant trigger on table "symptoms"."symptom_tip_sections" to "authenticated";

grant truncate on table "symptoms"."symptom_tip_sections" to "authenticated";

grant update on table "symptoms"."symptom_tip_sections" to "authenticated";

grant delete on table "symptoms"."symptom_tips" to "anon";

grant insert on table "symptoms"."symptom_tips" to "anon";

grant references on table "symptoms"."symptom_tips" to "anon";

grant select on table "symptoms"."symptom_tips" to "anon";

grant trigger on table "symptoms"."symptom_tips" to "anon";

grant truncate on table "symptoms"."symptom_tips" to "anon";

grant update on table "symptoms"."symptom_tips" to "anon";

grant delete on table "symptoms"."symptom_tips" to "authenticated";

grant insert on table "symptoms"."symptom_tips" to "authenticated";

grant references on table "symptoms"."symptom_tips" to "authenticated";

grant select on table "symptoms"."symptom_tips" to "authenticated";

grant trigger on table "symptoms"."symptom_tips" to "authenticated";

grant truncate on table "symptoms"."symptom_tips" to "authenticated";

grant update on table "symptoms"."symptom_tips" to "authenticated";

grant delete on table "symptoms"."symptoms" to "anon";

grant insert on table "symptoms"."symptoms" to "anon";

grant references on table "symptoms"."symptoms" to "anon";

grant select on table "symptoms"."symptoms" to "anon";

grant trigger on table "symptoms"."symptoms" to "anon";

grant truncate on table "symptoms"."symptoms" to "anon";

grant update on table "symptoms"."symptoms" to "anon";

grant delete on table "symptoms"."symptoms" to "authenticated";

grant insert on table "symptoms"."symptoms" to "authenticated";

grant references on table "symptoms"."symptoms" to "authenticated";

grant select on table "symptoms"."symptoms" to "authenticated";

grant trigger on table "symptoms"."symptoms" to "authenticated";

grant truncate on table "symptoms"."symptoms" to "authenticated";

grant update on table "symptoms"."symptoms" to "authenticated";

create policy "Enable read access for all users"
on "symptoms"."symptom_claire_prompts"
as permissive
for select
to public
using (true);


create policy "Enable read access for all users"
on "symptoms"."symptom_messages"
as permissive
for select
to public
using (true);


create policy "Enable read access for all users"
on "symptoms"."symptom_reddit_threads"
as permissive
for select
to public
using (true);


create policy "Enable read access for all users"
on "symptoms"."symptom_tip_sections"
as permissive
for select
to public
using (true);


create policy "Enable read access for all users"
on "symptoms"."symptom_tips"
as permissive
for select
to public
using (true);


create policy "Enable read access for all users"
on "symptoms"."symptoms"
as permissive
for select
to public
using (true);



