create table "programs"."program_feedback_resources" (
    "id" bigint generated by default as identity not null,
    "feedback_id" bigint not null,
    "resource_id" bigint not null
);


alter table "programs"."program_feedback_resources" enable row level security;

CREATE UNIQUE INDEX program_feedback_resources_pkey ON programs.program_feedback_resources USING btree (id);

alter table "programs"."program_feedback_resources" add constraint "program_feedback_resources_pkey" PRIMARY KEY using index "program_feedback_resources_pkey";

alter table "programs"."program_feedback_resources" add constraint "program_feedback_resources_feedback_id_fkey" FOREIGN KEY (feedback_id) REFERENCES programs.program_feedback(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "programs"."program_feedback_resources" validate constraint "program_feedback_resources_feedback_id_fkey";

alter table "programs"."program_feedback_resources" add constraint "program_feedback_resources_resource_id_fkey" FOREIGN KEY (resource_id) REFERENCES library.resources(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "programs"."program_feedback_resources" validate constraint "program_feedback_resources_resource_id_fkey";


set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.get_feedback(user_id text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$DECLARE
    recent_assessment RECORD;
    feedback JSONB := '[]';
BEGIN
    -- Step 1: Find the most recent assessment response for the user
    SELECT ar.assessment, pa.program, ar.responses
    INTO recent_assessment
    FROM programs.program_assessment_responses ar
    JOIN programs.program_assessments pa ON ar.assessment = pa.id
    WHERE ar.user_id = get_feedback.user_id
    ORDER BY ar.timestamp DESC
    LIMIT 1;

    -- Ensure a recent assessment exists
    IF recent_assessment IS NULL THEN
        RAISE EXCEPTION 'No assessments found for user %', user_id;
    END IF;

    -- Step 2: Fetch feedback for the associated program, applying filters and ordering
    SELECT jsonb_agg(
        jsonb_build_object(
            'order', af.order,
            'title', af.title,
            'body', af.body,
            'links', (
                SELECT COALESCE(
                    jsonb_agg(
                        jsonb_build_object(
                            'title', r.title,
                            'url', r.url
                        )
                    ),
                    '[]'::jsonb
                )
                FROM programs.program_feedback_resources pfr
                JOIN library.resources r ON pfr.resource_id = r.id
                WHERE pfr.feedback_id = af.id
            )
        ) ORDER BY af.order
    )
    INTO feedback
    FROM programs.program_feedback af
    WHERE af.program = recent_assessment.program
    AND (
        af.question_id IS NULL
        OR (
            af.question_id IS NOT NULL
            AND (
                -- String response match
                jsonb_typeof(recent_assessment.responses -> af.question_id) = 'string'
                AND af.question_response = recent_assessment.responses ->> af.question_id
            )
            OR (
                -- Array response match
                jsonb_typeof(recent_assessment.responses -> af.question_id) = 'array'
                AND af.question_response = ANY (
                    SELECT jsonb_array_elements_text(recent_assessment.responses -> af.question_id)
                )
            )
        )
    );

    RETURN COALESCE(feedback, '[]'::JSONB);
END;$function$
;

CREATE OR REPLACE FUNCTION public.get_messages(user_id text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$DECLARE
    recent_assessment RECORD;
    messages JSONB := '[]';
BEGIN
    -- Step 1: Find the most recent assessment response for the user
    SELECT ar.assessment, pa.program, ar.responses
    INTO recent_assessment
    FROM programs.program_assessment_responses ar
    JOIN programs.program_assessments pa ON ar.assessment = pa.id
    WHERE ar.user_id = get_messages.user_id
    ORDER BY ar.timestamp DESC
    LIMIT 1;

    -- Ensure a recent assessment exists
    IF recent_assessment IS NULL THEN
        RAISE EXCEPTION 'No assessments found for user %', user_id;
    END IF;

    -- Step 2: Fetch program messages for the associated program, applying filters and ordering
    SELECT jsonb_agg(message_data ORDER BY message_data->>'day', (message_data->>'question_id' IS NOT NULL))
    FROM (
        SELECT jsonb_build_object(
            'day', pm.day,
            'title', pm.title,
            'subtitle', pm.subtitle,
            'body', pm.body,
            'page_info', (
                SELECT NULLIF(
                    jsonb_agg(
                        jsonb_build_object(
                            'title', pmpi.title,
                            'body', pmpi.body
                        ) ORDER BY pmpi.order
                    ),
                    NULL
                )
                FROM programs.program_message_page_info pmpi
                WHERE pmpi.message_id = pm.id
            ),
            'claire_prompts', (
                SELECT NULLIF(
                    jsonb_agg(
                        jsonb_build_object(
                            'title', cp.title,
                            'prompt', cp.prompt
                        )
                    ),
                    NULL
                )
                FROM programs.program_message_claire_prompts pmcp
                JOIN library.claire_prompts cp ON pmcp.prompt_id = cp.id
                WHERE pmcp.message_id = pm.id
            ),
            'journal_prompts', (
                SELECT NULLIF(
                    jsonb_agg(jp.prompt),
                    NULL
                )
                FROM programs.program_message_journal_prompts pmjp
                JOIN library.journal_prompts jp ON pmjp.prompt_id = jp.id
                WHERE pmjp.message_id = pm.id
            ),
            'resources', (
                SELECT NULLIF(
                    jsonb_agg(
                        jsonb_build_object(
                            'title', r.title,
                            'url', r.url
                        )
                    ),
                    NULL
                )
                FROM programs.program_message_resources pmr
                JOIN library.resources r ON pmr.resource_id = r.id
                WHERE pmr.message_id = pm.id
            ),
            'meditation', (
                SELECT NULLIF(
                    jsonb_build_object(
                        'name', m.title,
                        'url', m.url,
                        'visited', 'false'::bool
                    ),
                    NULL
                )
                FROM programs.program_message_meditations pmm
                JOIN library.meditations m ON pmm.meditation_id = m.id
                WHERE pmm.message_id = pm.id
                LIMIT 1
            )
        ) AS message_data
        FROM programs.program_messages pm
        WHERE pm.program = recent_assessment.program
        AND (
            pm.question_id IS NULL
            OR (
                pm.question_id IS NOT NULL
                AND (
                    -- Case 1: The response is a string and matches question_response
                    jsonb_typeof(recent_assessment.responses -> pm.question_id) = 'string'
                    AND pm.question_response = recent_assessment.responses ->> pm.question_id
                )
                OR (
                    -- Case 2: The response is an array and contains question_response
                    jsonb_typeof(recent_assessment.responses -> pm.question_id) = 'array'
                    AND pm.question_response = ANY (
                        SELECT jsonb_array_elements_text(recent_assessment.responses -> pm.question_id)
                    )
                )
            )
        )
        ORDER BY pm.day ASC, 
                 pm.question_id IS NOT NULL
    ) subquery
    INTO messages;

    RETURN messages;
END;$function$
;


