create schema if not exists "comms";

create type "comms"."direction" as enum ('inbound', 'outbound');

create table "comms"."feedback" (
    "id" bigint generated by default as identity not null,
    "user_id" text,
    "feedback" text not null,
    "timestamp" timestamp with time zone not null
);


alter table "comms"."feedback" enable row level security;

create table "comms"."notifications" (
    "id" bigint generated by default as identity not null,
    "user_id" text not null,
    "title" text not null,
    "body" text not null,
    "timestamp" timestamp with time zone not null default now()
);


alter table "comms"."notifications" enable row level security;

CREATE UNIQUE INDEX feedback_pkey ON comms.feedback USING btree (id);

CREATE UNIQUE INDEX notifications_pkey ON comms.notifications USING btree (id);

alter table "comms"."feedback" add constraint "feedback_pkey" PRIMARY KEY using index "feedback_pkey";

alter table "comms"."notifications" add constraint "notifications_pkey" PRIMARY KEY using index "notifications_pkey";

alter table "comms"."feedback" add constraint "feedback_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "comms"."feedback" validate constraint "feedback_user_id_fkey";

alter table "comms"."notifications" add constraint "notifications_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "comms"."notifications" validate constraint "notifications_user_id_fkey";

grant delete on table "comms"."feedback" to "anon";

grant insert on table "comms"."feedback" to "anon";

grant references on table "comms"."feedback" to "anon";

grant select on table "comms"."feedback" to "anon";

grant trigger on table "comms"."feedback" to "anon";

grant truncate on table "comms"."feedback" to "anon";

grant update on table "comms"."feedback" to "anon";

grant delete on table "comms"."feedback" to "authenticated";

grant insert on table "comms"."feedback" to "authenticated";

grant references on table "comms"."feedback" to "authenticated";

grant select on table "comms"."feedback" to "authenticated";

grant trigger on table "comms"."feedback" to "authenticated";

grant truncate on table "comms"."feedback" to "authenticated";

grant update on table "comms"."feedback" to "authenticated";

grant delete on table "comms"."notifications" to "anon";

grant insert on table "comms"."notifications" to "anon";

grant references on table "comms"."notifications" to "anon";

grant select on table "comms"."notifications" to "anon";

grant trigger on table "comms"."notifications" to "anon";

grant truncate on table "comms"."notifications" to "anon";

grant update on table "comms"."notifications" to "anon";

grant delete on table "comms"."notifications" to "authenticated";

grant insert on table "comms"."notifications" to "authenticated";

grant references on table "comms"."notifications" to "authenticated";

grant select on table "comms"."notifications" to "authenticated";

grant trigger on table "comms"."notifications" to "authenticated";

grant truncate on table "comms"."notifications" to "authenticated";

grant update on table "comms"."notifications" to "authenticated";

create policy "Users can add feedback"
on "comms"."feedback"
as permissive
for insert
to public
with check (true);


create policy "Users cannot read feedback"
on "comms"."feedback"
as permissive
for select
to public
using (false);


create policy "Disable access for all users"
on "comms"."notifications"
as permissive
for all
to public
using (false);


CREATE TRIGGER send_notification AFTER INSERT ON comms.notifications FOR EACH ROW EXECUTE FUNCTION supabase_functions.http_request('https://quluipmdicjsolnsopkg.supabase.co/functions/v1/sendNotification', 'POST', '{"Content-type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF1bHVpcG1kaWNqc29sbnNvcGtnIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTcyNDY5NTgzNywiZXhwIjoyMDQwMjcxODM3fQ.UQ4uafnOA_nMELdw05JcySLuBqDIrOcQCrWzFNFR9FY"}', '{}', '1000');


create schema if not exists "groups";

create table "groups"."group_activity" (
    "id" uuid not null default gen_random_uuid(),
    "group_id" uuid not null,
    "user_id" text not null,
    "timestamp" timestamp with time zone not null default now(),
    "activity" group_activity_type not null default 'joined'::group_activity_type
);


alter table "groups"."group_activity" enable row level security;

create table "groups"."group_members" (
    "id" uuid not null default gen_random_uuid(),
    "group_id" uuid not null,
    "user_id" text not null
);


alter table "groups"."group_members" enable row level security;

create table "groups"."group_notes" (
    "id" uuid not null default gen_random_uuid(),
    "group_id" uuid not null,
    "to_member_id" text not null,
    "from_member_id" text not null,
    "message" text not null,
    "timestamp" timestamp with time zone not null default now()
);


alter table "groups"."group_notes" enable row level security;

create table "groups"."group_pings" (
    "id" uuid not null default gen_random_uuid(),
    "from_user_id" text not null default now(),
    "to_user_id" text not null,
    "group_id" uuid not null,
    "timestamp" timestamp with time zone not null default now()
);


alter table "groups"."group_pings" enable row level security;

create table "groups"."group_subscriptions" (
    "id" uuid not null default gen_random_uuid(),
    "group_id" uuid not null,
    "user_id" text not null,
    "subscribed_to" text not null,
    "timestamp" timestamp with time zone not null default now()
);


alter table "groups"."group_subscriptions" enable row level security;

create table "groups"."groups" (
    "id" uuid not null default gen_random_uuid(),
    "name" text not null,
    "hue" numeric not null
);


alter table "groups"."groups" enable row level security;

CREATE UNIQUE INDEX group_activity_pkey ON groups.group_activity USING btree (id);

CREATE UNIQUE INDEX group_members_pkey ON groups.group_members USING btree (id);

CREATE UNIQUE INDEX group_notes_pkey ON groups.group_notes USING btree (id);

CREATE UNIQUE INDEX group_notes_unique_constraint ON groups.group_notes USING btree (group_id, from_member_id, to_member_id, "timestamp");

CREATE UNIQUE INDEX group_pings_pkey ON groups.group_pings USING btree (id);

CREATE UNIQUE INDEX group_subscriptions_pkey ON groups.group_subscriptions USING btree (id);

CREATE UNIQUE INDEX groups_pkey ON groups.groups USING btree (id);

CREATE UNIQUE INDEX unique_group_activity ON groups.group_activity USING btree (group_id, user_id, "timestamp");

CREATE UNIQUE INDEX unique_group_user ON groups.group_members USING btree (group_id, user_id);

alter table "groups"."group_activity" add constraint "group_activity_pkey" PRIMARY KEY using index "group_activity_pkey";

alter table "groups"."group_members" add constraint "group_members_pkey" PRIMARY KEY using index "group_members_pkey";

alter table "groups"."group_notes" add constraint "group_notes_pkey" PRIMARY KEY using index "group_notes_pkey";

alter table "groups"."group_pings" add constraint "group_pings_pkey" PRIMARY KEY using index "group_pings_pkey";

alter table "groups"."group_subscriptions" add constraint "group_subscriptions_pkey" PRIMARY KEY using index "group_subscriptions_pkey";

alter table "groups"."groups" add constraint "groups_pkey" PRIMARY KEY using index "groups_pkey";

alter table "groups"."group_activity" add constraint "group_activity_group_id_fkey1" FOREIGN KEY (group_id) REFERENCES groups.groups(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "groups"."group_activity" validate constraint "group_activity_group_id_fkey1";

alter table "groups"."group_activity" add constraint "group_activity_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "groups"."group_activity" validate constraint "group_activity_user_id_fkey";

alter table "groups"."group_activity" add constraint "unique_group_activity" UNIQUE using index "unique_group_activity";

alter table "groups"."group_members" add constraint "group_members_group_id_fkey1" FOREIGN KEY (group_id) REFERENCES groups.groups(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "groups"."group_members" validate constraint "group_members_group_id_fkey1";

alter table "groups"."group_members" add constraint "group_members_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "groups"."group_members" validate constraint "group_members_user_id_fkey";

alter table "groups"."group_members" add constraint "unique_group_user" UNIQUE using index "unique_group_user";

alter table "groups"."group_notes" add constraint "group_notes_from_member_id_fkey" FOREIGN KEY (from_member_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "groups"."group_notes" validate constraint "group_notes_from_member_id_fkey";

alter table "groups"."group_notes" add constraint "group_notes_group_id_fkey1" FOREIGN KEY (group_id) REFERENCES groups.groups(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "groups"."group_notes" validate constraint "group_notes_group_id_fkey1";

alter table "groups"."group_notes" add constraint "group_notes_to_member_id_fkey" FOREIGN KEY (to_member_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "groups"."group_notes" validate constraint "group_notes_to_member_id_fkey";

alter table "groups"."group_notes" add constraint "group_notes_unique_constraint" UNIQUE using index "group_notes_unique_constraint";

alter table "groups"."group_pings" add constraint "group_pings_from_user_id_fkey" FOREIGN KEY (from_user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "groups"."group_pings" validate constraint "group_pings_from_user_id_fkey";

alter table "groups"."group_pings" add constraint "group_pings_group_id_fkey1" FOREIGN KEY (group_id) REFERENCES groups.groups(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "groups"."group_pings" validate constraint "group_pings_group_id_fkey1";

alter table "groups"."group_pings" add constraint "group_pings_to_user_id_fkey" FOREIGN KEY (to_user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "groups"."group_pings" validate constraint "group_pings_to_user_id_fkey";

alter table "groups"."group_subscriptions" add constraint "group_subscriptions_group_id_fkey1" FOREIGN KEY (group_id) REFERENCES groups.groups(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "groups"."group_subscriptions" validate constraint "group_subscriptions_group_id_fkey1";

alter table "groups"."group_subscriptions" add constraint "group_subscriptions_subscribed_to_fkey" FOREIGN KEY (subscribed_to) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "groups"."group_subscriptions" validate constraint "group_subscriptions_subscribed_to_fkey";

alter table "groups"."group_subscriptions" add constraint "group_subscriptions_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "groups"."group_subscriptions" validate constraint "group_subscriptions_user_id_fkey";

grant delete on table "groups"."group_activity" to "anon";

grant insert on table "groups"."group_activity" to "anon";

grant references on table "groups"."group_activity" to "anon";

grant select on table "groups"."group_activity" to "anon";

grant trigger on table "groups"."group_activity" to "anon";

grant truncate on table "groups"."group_activity" to "anon";

grant update on table "groups"."group_activity" to "anon";

grant delete on table "groups"."group_activity" to "authenticated";

grant insert on table "groups"."group_activity" to "authenticated";

grant references on table "groups"."group_activity" to "authenticated";

grant select on table "groups"."group_activity" to "authenticated";

grant trigger on table "groups"."group_activity" to "authenticated";

grant truncate on table "groups"."group_activity" to "authenticated";

grant update on table "groups"."group_activity" to "authenticated";

grant delete on table "groups"."group_members" to "anon";

grant insert on table "groups"."group_members" to "anon";

grant references on table "groups"."group_members" to "anon";

grant select on table "groups"."group_members" to "anon";

grant trigger on table "groups"."group_members" to "anon";

grant truncate on table "groups"."group_members" to "anon";

grant update on table "groups"."group_members" to "anon";

grant delete on table "groups"."group_members" to "authenticated";

grant insert on table "groups"."group_members" to "authenticated";

grant references on table "groups"."group_members" to "authenticated";

grant select on table "groups"."group_members" to "authenticated";

grant trigger on table "groups"."group_members" to "authenticated";

grant truncate on table "groups"."group_members" to "authenticated";

grant update on table "groups"."group_members" to "authenticated";

grant delete on table "groups"."group_notes" to "anon";

grant insert on table "groups"."group_notes" to "anon";

grant references on table "groups"."group_notes" to "anon";

grant select on table "groups"."group_notes" to "anon";

grant trigger on table "groups"."group_notes" to "anon";

grant truncate on table "groups"."group_notes" to "anon";

grant update on table "groups"."group_notes" to "anon";

grant delete on table "groups"."group_notes" to "authenticated";

grant insert on table "groups"."group_notes" to "authenticated";

grant references on table "groups"."group_notes" to "authenticated";

grant select on table "groups"."group_notes" to "authenticated";

grant trigger on table "groups"."group_notes" to "authenticated";

grant truncate on table "groups"."group_notes" to "authenticated";

grant update on table "groups"."group_notes" to "authenticated";

grant delete on table "groups"."group_pings" to "anon";

grant insert on table "groups"."group_pings" to "anon";

grant references on table "groups"."group_pings" to "anon";

grant select on table "groups"."group_pings" to "anon";

grant trigger on table "groups"."group_pings" to "anon";

grant truncate on table "groups"."group_pings" to "anon";

grant update on table "groups"."group_pings" to "anon";

grant delete on table "groups"."group_pings" to "authenticated";

grant insert on table "groups"."group_pings" to "authenticated";

grant references on table "groups"."group_pings" to "authenticated";

grant select on table "groups"."group_pings" to "authenticated";

grant trigger on table "groups"."group_pings" to "authenticated";

grant truncate on table "groups"."group_pings" to "authenticated";

grant update on table "groups"."group_pings" to "authenticated";

grant delete on table "groups"."group_subscriptions" to "anon";

grant insert on table "groups"."group_subscriptions" to "anon";

grant references on table "groups"."group_subscriptions" to "anon";

grant select on table "groups"."group_subscriptions" to "anon";

grant trigger on table "groups"."group_subscriptions" to "anon";

grant truncate on table "groups"."group_subscriptions" to "anon";

grant update on table "groups"."group_subscriptions" to "anon";

grant delete on table "groups"."group_subscriptions" to "authenticated";

grant insert on table "groups"."group_subscriptions" to "authenticated";

grant references on table "groups"."group_subscriptions" to "authenticated";

grant select on table "groups"."group_subscriptions" to "authenticated";

grant trigger on table "groups"."group_subscriptions" to "authenticated";

grant truncate on table "groups"."group_subscriptions" to "authenticated";

grant update on table "groups"."group_subscriptions" to "authenticated";

grant delete on table "groups"."groups" to "anon";

grant insert on table "groups"."groups" to "anon";

grant references on table "groups"."groups" to "anon";

grant select on table "groups"."groups" to "anon";

grant trigger on table "groups"."groups" to "anon";

grant truncate on table "groups"."groups" to "anon";

grant update on table "groups"."groups" to "anon";

grant delete on table "groups"."groups" to "authenticated";

grant insert on table "groups"."groups" to "authenticated";

grant references on table "groups"."groups" to "authenticated";

grant select on table "groups"."groups" to "authenticated";

grant trigger on table "groups"."groups" to "authenticated";

grant truncate on table "groups"."groups" to "authenticated";

grant update on table "groups"."groups" to "authenticated";

create policy "Disable access for all users"
on "groups"."group_activity"
as permissive
for all
to public
using (false);


create policy "Disable access for all users"
on "groups"."group_members"
as permissive
for all
to public
using (false);


create policy "Disable access for all users"
on "groups"."group_notes"
as permissive
for all
to public
using (false);


create policy "Disable access for all users"
on "groups"."group_pings"
as permissive
for all
to public
using (false);


create policy "Disable access for all users"
on "groups"."group_subscriptions"
as permissive
for all
to public
using (false);


create policy "Disable access for all users"
on "groups"."groups"
as permissive
for all
to public
using (false);


CREATE TRIGGER schedule_group_note_notification AFTER INSERT ON groups.group_notes FOR EACH ROW EXECUTE FUNCTION add_note_notification();

CREATE TRIGGER schedule_group_ping_notification AFTER INSERT ON groups.group_pings FOR EACH ROW EXECUTE FUNCTION add_ping_notification();


drop trigger if exists "send_note_notification" on "public"."group_notes";

drop trigger if exists "send_ping_notification" on "public"."group_pings";

drop trigger if exists "send_notification" on "public"."notifications";

drop policy "Disable read access for all users" on "public"."feedback";

drop policy "Enable write access for all users" on "public"."feedback";

drop policy "Disable public access" on "public"."group_activity";

drop policy "Disable public access" on "public"."group_members";

drop policy "Disable public access" on "public"."group_notes";

drop policy "Disable public access" on "public"."group_pings";

drop policy "No public access" on "public"."group_subscriptions";

drop policy "Disable public access" on "public"."groups";

drop policy "Disable public access" on "public"."notifications";

revoke delete on table "public"."feedback" from "anon";

revoke insert on table "public"."feedback" from "anon";

revoke references on table "public"."feedback" from "anon";

revoke select on table "public"."feedback" from "anon";

revoke trigger on table "public"."feedback" from "anon";

revoke truncate on table "public"."feedback" from "anon";

revoke update on table "public"."feedback" from "anon";

revoke delete on table "public"."feedback" from "authenticated";

revoke insert on table "public"."feedback" from "authenticated";

revoke references on table "public"."feedback" from "authenticated";

revoke select on table "public"."feedback" from "authenticated";

revoke trigger on table "public"."feedback" from "authenticated";

revoke truncate on table "public"."feedback" from "authenticated";

revoke update on table "public"."feedback" from "authenticated";

revoke delete on table "public"."feedback" from "service_role";

revoke insert on table "public"."feedback" from "service_role";

revoke references on table "public"."feedback" from "service_role";

revoke select on table "public"."feedback" from "service_role";

revoke trigger on table "public"."feedback" from "service_role";

revoke truncate on table "public"."feedback" from "service_role";

revoke update on table "public"."feedback" from "service_role";

revoke delete on table "public"."group_activity" from "anon";

revoke insert on table "public"."group_activity" from "anon";

revoke references on table "public"."group_activity" from "anon";

revoke select on table "public"."group_activity" from "anon";

revoke trigger on table "public"."group_activity" from "anon";

revoke truncate on table "public"."group_activity" from "anon";

revoke update on table "public"."group_activity" from "anon";

revoke delete on table "public"."group_activity" from "authenticated";

revoke insert on table "public"."group_activity" from "authenticated";

revoke references on table "public"."group_activity" from "authenticated";

revoke select on table "public"."group_activity" from "authenticated";

revoke trigger on table "public"."group_activity" from "authenticated";

revoke truncate on table "public"."group_activity" from "authenticated";

revoke update on table "public"."group_activity" from "authenticated";

revoke delete on table "public"."group_activity" from "service_role";

revoke insert on table "public"."group_activity" from "service_role";

revoke references on table "public"."group_activity" from "service_role";

revoke select on table "public"."group_activity" from "service_role";

revoke trigger on table "public"."group_activity" from "service_role";

revoke truncate on table "public"."group_activity" from "service_role";

revoke update on table "public"."group_activity" from "service_role";

revoke delete on table "public"."group_members" from "anon";

revoke insert on table "public"."group_members" from "anon";

revoke references on table "public"."group_members" from "anon";

revoke select on table "public"."group_members" from "anon";

revoke trigger on table "public"."group_members" from "anon";

revoke truncate on table "public"."group_members" from "anon";

revoke update on table "public"."group_members" from "anon";

revoke delete on table "public"."group_members" from "authenticated";

revoke insert on table "public"."group_members" from "authenticated";

revoke references on table "public"."group_members" from "authenticated";

revoke select on table "public"."group_members" from "authenticated";

revoke trigger on table "public"."group_members" from "authenticated";

revoke truncate on table "public"."group_members" from "authenticated";

revoke update on table "public"."group_members" from "authenticated";

revoke delete on table "public"."group_members" from "service_role";

revoke insert on table "public"."group_members" from "service_role";

revoke references on table "public"."group_members" from "service_role";

revoke select on table "public"."group_members" from "service_role";

revoke trigger on table "public"."group_members" from "service_role";

revoke truncate on table "public"."group_members" from "service_role";

revoke update on table "public"."group_members" from "service_role";

revoke delete on table "public"."group_notes" from "anon";

revoke insert on table "public"."group_notes" from "anon";

revoke references on table "public"."group_notes" from "anon";

revoke select on table "public"."group_notes" from "anon";

revoke trigger on table "public"."group_notes" from "anon";

revoke truncate on table "public"."group_notes" from "anon";

revoke update on table "public"."group_notes" from "anon";

revoke delete on table "public"."group_notes" from "authenticated";

revoke insert on table "public"."group_notes" from "authenticated";

revoke references on table "public"."group_notes" from "authenticated";

revoke select on table "public"."group_notes" from "authenticated";

revoke trigger on table "public"."group_notes" from "authenticated";

revoke truncate on table "public"."group_notes" from "authenticated";

revoke update on table "public"."group_notes" from "authenticated";

revoke delete on table "public"."group_notes" from "service_role";

revoke insert on table "public"."group_notes" from "service_role";

revoke references on table "public"."group_notes" from "service_role";

revoke select on table "public"."group_notes" from "service_role";

revoke trigger on table "public"."group_notes" from "service_role";

revoke truncate on table "public"."group_notes" from "service_role";

revoke update on table "public"."group_notes" from "service_role";

revoke delete on table "public"."group_pings" from "anon";

revoke insert on table "public"."group_pings" from "anon";

revoke references on table "public"."group_pings" from "anon";

revoke select on table "public"."group_pings" from "anon";

revoke trigger on table "public"."group_pings" from "anon";

revoke truncate on table "public"."group_pings" from "anon";

revoke update on table "public"."group_pings" from "anon";

revoke delete on table "public"."group_pings" from "authenticated";

revoke insert on table "public"."group_pings" from "authenticated";

revoke references on table "public"."group_pings" from "authenticated";

revoke select on table "public"."group_pings" from "authenticated";

revoke trigger on table "public"."group_pings" from "authenticated";

revoke truncate on table "public"."group_pings" from "authenticated";

revoke update on table "public"."group_pings" from "authenticated";

revoke delete on table "public"."group_pings" from "service_role";

revoke insert on table "public"."group_pings" from "service_role";

revoke references on table "public"."group_pings" from "service_role";

revoke select on table "public"."group_pings" from "service_role";

revoke trigger on table "public"."group_pings" from "service_role";

revoke truncate on table "public"."group_pings" from "service_role";

revoke update on table "public"."group_pings" from "service_role";

revoke delete on table "public"."group_subscriptions" from "anon";

revoke insert on table "public"."group_subscriptions" from "anon";

revoke references on table "public"."group_subscriptions" from "anon";

revoke select on table "public"."group_subscriptions" from "anon";

revoke trigger on table "public"."group_subscriptions" from "anon";

revoke truncate on table "public"."group_subscriptions" from "anon";

revoke update on table "public"."group_subscriptions" from "anon";

revoke delete on table "public"."group_subscriptions" from "authenticated";

revoke insert on table "public"."group_subscriptions" from "authenticated";

revoke references on table "public"."group_subscriptions" from "authenticated";

revoke select on table "public"."group_subscriptions" from "authenticated";

revoke trigger on table "public"."group_subscriptions" from "authenticated";

revoke truncate on table "public"."group_subscriptions" from "authenticated";

revoke update on table "public"."group_subscriptions" from "authenticated";

revoke delete on table "public"."group_subscriptions" from "service_role";

revoke insert on table "public"."group_subscriptions" from "service_role";

revoke references on table "public"."group_subscriptions" from "service_role";

revoke select on table "public"."group_subscriptions" from "service_role";

revoke trigger on table "public"."group_subscriptions" from "service_role";

revoke truncate on table "public"."group_subscriptions" from "service_role";

revoke update on table "public"."group_subscriptions" from "service_role";

revoke delete on table "public"."groups" from "anon";

revoke insert on table "public"."groups" from "anon";

revoke references on table "public"."groups" from "anon";

revoke select on table "public"."groups" from "anon";

revoke trigger on table "public"."groups" from "anon";

revoke truncate on table "public"."groups" from "anon";

revoke update on table "public"."groups" from "anon";

revoke delete on table "public"."groups" from "authenticated";

revoke insert on table "public"."groups" from "authenticated";

revoke references on table "public"."groups" from "authenticated";

revoke select on table "public"."groups" from "authenticated";

revoke trigger on table "public"."groups" from "authenticated";

revoke truncate on table "public"."groups" from "authenticated";

revoke update on table "public"."groups" from "authenticated";

revoke delete on table "public"."groups" from "service_role";

revoke insert on table "public"."groups" from "service_role";

revoke references on table "public"."groups" from "service_role";

revoke select on table "public"."groups" from "service_role";

revoke trigger on table "public"."groups" from "service_role";

revoke truncate on table "public"."groups" from "service_role";

revoke update on table "public"."groups" from "service_role";

revoke delete on table "public"."notifications" from "anon";

revoke insert on table "public"."notifications" from "anon";

revoke references on table "public"."notifications" from "anon";

revoke select on table "public"."notifications" from "anon";

revoke trigger on table "public"."notifications" from "anon";

revoke truncate on table "public"."notifications" from "anon";

revoke update on table "public"."notifications" from "anon";

revoke delete on table "public"."notifications" from "authenticated";

revoke insert on table "public"."notifications" from "authenticated";

revoke references on table "public"."notifications" from "authenticated";

revoke select on table "public"."notifications" from "authenticated";

revoke trigger on table "public"."notifications" from "authenticated";

revoke truncate on table "public"."notifications" from "authenticated";

revoke update on table "public"."notifications" from "authenticated";

revoke delete on table "public"."notifications" from "service_role";

revoke insert on table "public"."notifications" from "service_role";

revoke references on table "public"."notifications" from "service_role";

revoke select on table "public"."notifications" from "service_role";

revoke trigger on table "public"."notifications" from "service_role";

revoke truncate on table "public"."notifications" from "service_role";

revoke update on table "public"."notifications" from "service_role";

alter table "public"."group_activity" drop constraint "group_activity_group_id_fkey";

alter table "public"."group_activity" drop constraint "group_activity_user_id_fkey";

alter table "public"."group_activity" drop constraint "unique_group_activity";

alter table "public"."group_members" drop constraint "group_members_group_id_fkey";

alter table "public"."group_members" drop constraint "group_members_user_id_fkey";

alter table "public"."group_members" drop constraint "unique_group_user";

alter table "public"."group_notes" drop constraint "group_notes_from_member_id_fkey";

alter table "public"."group_notes" drop constraint "group_notes_group_id_fkey";

alter table "public"."group_notes" drop constraint "group_notes_to_member_id_fkey";

alter table "public"."group_notes" drop constraint "group_notes_unique_constraint";

alter table "public"."group_pings" drop constraint "group_pings_from_user_id_fkey";

alter table "public"."group_pings" drop constraint "group_pings_group_id_fkey";

alter table "public"."group_pings" drop constraint "group_pings_to_user_id_fkey";

alter table "public"."group_subscriptions" drop constraint "group_subscriptions_group_id_fkey";

alter table "public"."group_subscriptions" drop constraint "group_subscriptions_subscribed_to_fkey";

alter table "public"."group_subscriptions" drop constraint "group_subscriptions_user_id_fkey";

alter table "public"."notifications" drop constraint "notifications_user_id_fkey";

alter table "public"."feedback" drop constraint "feedback_pkey";

alter table "public"."group_activity" drop constraint "group_activity_pkey";

alter table "public"."group_members" drop constraint "group_members_pkey";

alter table "public"."group_notes" drop constraint "group_notes_pkey";

alter table "public"."group_pings" drop constraint "group_pings_pkey";

alter table "public"."group_subscriptions" drop constraint "group_subscriptions_pkey";

alter table "public"."groups" drop constraint "groups_pkey";

alter table "public"."notifications" drop constraint "notifications_pkey";

drop index if exists "public"."feedback_pkey";

drop index if exists "public"."group_activity_pkey";

drop index if exists "public"."group_members_pkey";

drop index if exists "public"."group_notes_pkey";

drop index if exists "public"."group_notes_unique_constraint";

drop index if exists "public"."group_pings_pkey";

drop index if exists "public"."group_subscriptions_pkey";

drop index if exists "public"."groups_pkey";

drop index if exists "public"."notifications_pkey";

drop index if exists "public"."unique_group_activity";

drop index if exists "public"."unique_group_user";

drop table "public"."feedback";

drop table "public"."group_activity";

drop table "public"."group_members";

drop table "public"."group_notes";

drop table "public"."group_pings";

drop table "public"."group_subscriptions";

drop table "public"."groups";

drop table "public"."notifications";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.add_group_mem(user_id text, group_id uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$BEGIN
    -- Insert a new row into the group_members table
    INSERT INTO groups.group_members (user_id, group_id)
    VALUES (user_id, group_id)
    ON CONFLICT DO NOTHING;  -- Avoid inserting duplicate records

    -- Insert a new row into the group_activity table with the "joined" activity
    INSERT INTO groups.group_activity (group_id, user_id, activity)
    VALUES (group_id, user_id, 'joined');
END;$function$
;

CREATE OR REPLACE FUNCTION public.add_group_note(group_id uuid, to_member_id text, from_member_id text, message text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$BEGIN
    -- Check if both to_member_id and from_member_id are in the group
    IF EXISTS (
        SELECT 1 FROM groups.group_members gm
        WHERE gm.group_id = add_group_note.group_id
          AND gm.user_id = add_group_note.to_member_id
    )
    AND EXISTS (
        SELECT 1 FROM groups.group_members gm
        WHERE gm.group_id = add_group_note.group_id
          AND gm.user_id = add_group_note.from_member_id
    ) THEN
        -- Insert the note into the group_notes table
        INSERT INTO groups.group_notes (group_id, to_member_id, from_member_id, message, timestamp)
        VALUES (add_group_note.group_id, add_group_note.to_member_id, add_group_note.from_member_id, add_group_note.message, NOW());

        -- Insert a new row into the group_activity table with the "note" activity
        INSERT INTO groups.group_activity (group_id, user_id, activity)
        VALUES (add_group_note.group_id, add_group_note.from_member_id, 'message');
    END IF;
END;$function$
;

CREATE OR REPLACE FUNCTION public.add_group_ping(group_id uuid, from_user_id text, to_user_id text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$BEGIN
    IF EXISTS (
        SELECT 1 FROM groups.group_members gm
        WHERE gm.group_id = add_group_ping.group_id
          AND gm.user_id = add_group_ping.to_user_id
    )
    AND EXISTS (
        SELECT 1 FROM groups.group_members gm
        WHERE gm.group_id = add_group_ping.group_id
          AND gm.user_id = add_group_ping.from_user_id
    ) THEN
        -- Insert the note into the group_notes table
        INSERT INTO groups.group_pings (group_id, from_user_id, to_user_id)
        VALUES (add_group_ping.group_id, add_group_ping.from_user_id, add_group_ping.to_user_id);
    END IF;
END;$function$
;

CREATE OR REPLACE FUNCTION public.add_note_notification()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$DECLARE
    -- Declare variables to hold the data we'll fetch
    to_user_fcm_token TEXT;
    from_user_name TEXT;
    from_user_emoji TEXT;
BEGIN
    -- Check if the 'to_member_id' has an fcm_token
    SELECT fcm_token INTO to_user_fcm_token
    FROM users
    WHERE id = NEW.to_member_id;

    -- If there is no fcm_token, just return and do nothing
    IF to_user_fcm_token IS NULL THEN
        RETURN NULL;
    END IF;

    -- Fetch the 'name' and 'emoji' of the 'from_member_id'
    SELECT name, emoji INTO from_user_name, from_user_emoji
    FROM users
    WHERE id = NEW.from_member_id;

    -- Insert a notification into the notifications table
    INSERT INTO comms.notifications (user_id, title, body, timestamp)
    VALUES (
        NEW.to_member_id, 
        from_user_emoji || ' ' || from_user_name || ' sent you a note!',  -- Format the title
        NEW.message,  -- The body is the note's message content
        NOW()  -- Set the current timestamp
    );

    RETURN NEW;
END;$function$
;

CREATE OR REPLACE FUNCTION public.add_ping_notification()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$DECLARE
    -- Declare variables to hold the data we'll fetch
    to_user_fcm_token TEXT;
    from_user_name TEXT;
    from_user_emoji TEXT;
BEGIN
    -- Check if the 'to_member_id' has an fcm_token
    SELECT fcm_token INTO to_user_fcm_token
    FROM users
    WHERE id = NEW.to_user_id;

    -- If there is no fcm_token, just return and do nothing
    IF to_user_fcm_token IS NULL THEN
        RETURN NULL;
    END IF;

    -- Fetch the 'name' and 'emoji' of the 'from_member_id'
    SELECT name, emoji INTO from_user_name, from_user_emoji
    FROM users
    WHERE id = NEW.from_user_id;

    -- Insert a notification into the notifications table
    INSERT INTO comms.notifications (user_id, title, body, timestamp)
    VALUES (
        NEW.to_user_id, 
        from_user_emoji || ' ' || from_user_name || ' check in!',  -- Format the title
        from_user_name || ' wants you to check in on Clear30!',  -- The body is the note's message content
        NOW()  -- Set the current timestamp
    );

    RETURN NEW;
END;$function$
;

CREATE OR REPLACE FUNCTION public.delete_group(group_id uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$BEGIN
    -- Delete all records from the group_notes table for the specified group
    DELETE FROM groups.group_notes
    WHERE groups.group_notes.group_id = delete_group.group_id;

    -- Delete all records from the group_activity table for the specified group
    DELETE FROM groups.group_activity
    WHERE groups.group_activity.group_id = delete_group.group_id;

    -- Delete all records from the group_members table for the specified group
    DELETE FROM groups.group_members
    WHERE groups.group_members.group_id = delete_group.group_id;

    -- Finally, delete the group itself from the groups table
    DELETE FROM groups.groups
    WHERE groups.groups.id = delete_group.group_id;

END;$function$
;

CREATE OR REPLACE FUNCTION public.get_group(group_id uuid)
 RETURNS json
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$BEGIN
    RETURN (
        SELECT json_build_object(
            'id', g.id,
            'name', g.name,
            'hue', g.hue,
            'members', (
                SELECT COALESCE(json_agg(
                    json_build_object(
                        'memberID', u.id,
                        'name', u.name,
                        'emoji', u.emoji,
                        'daysSober', u.days_sober,
                        'initialFrequency', COALESCE(NULLIF(u.initial_frequency, 0), 0),
                        'showInRank', u.show_in_group_rank,
                        'startDate', u.start_date,
                        'notes', COALESCE((
                            SELECT json_agg(
                                json_build_object(
                                    'fromMemberID', gn.from_member_id,
                                    'message', gn.message,
                                    'timestamp', date_trunc('second', gn.timestamp)  -- Truncate to seconds
                                )
                            )
                            FROM groups.group_notes gn
                            WHERE gn.to_member_id = u.id
                            AND gn.group_id = g.id
                        ), '[]'::json)
                    )
                ), '[]'::json)
                FROM groups.group_members gm
                JOIN users u ON gm.user_id = u.id
                WHERE gm.group_id = g.id
            ),
            'activity', COALESCE((
                SELECT json_agg(
                    json_build_object(
                        'memberID', ga.user_id,
                        'type', ga.activity,
                        'timestamp', date_trunc('second', ga.timestamp)  -- Truncate to seconds
                    )
                )
                FROM groups.group_activity ga
                WHERE ga.group_id = g.id
            ), '[]'::json)
        )
        FROM groups.groups g
        WHERE g.id = group_id
    );
END;$function$
;

CREATE OR REPLACE FUNCTION public.get_group(group_id uuid, user_id text)
 RETURNS json
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$BEGIN
    -- Step 1: Check if the user is part of the group
    IF NOT EXISTS (
        SELECT 1
        FROM groups.group_members gm
        WHERE gm.group_id = get_group.group_id
          AND gm.user_id = get_group.user_id
    ) THEN
        -- Raise a custom exception with a custom SQLSTATE
        RAISE EXCEPTION 'User % is not part of the group %', get_group.user_id, get_group.group_id
            USING ERRCODE = 'P0001';
    END IF;

    -- Step 2: Return group details if the user is part of the group
    RETURN (
        SELECT json_build_object(
            'id', g.id,
            'name', g.name,
            'hue', g.hue,
            'members', (
                SELECT COALESCE(json_agg(
                    json_build_object(
                        'memberID', u.id,
                        'name', u.name,
                        'emoji', u.emoji,
                        'daysSober', u.days_sober,
                        'initialFrequency', COALESCE(NULLIF(u.initial_frequency, 0), 0),
                        'showInRank', u.show_in_group_rank,
                        'startDate', u.start_date,
                        'notes', COALESCE((
                            SELECT json_agg(
                                json_build_object(
                                    'fromMemberID', gn.from_member_id,
                                    'message', gn.message,
                                    'timestamp', date_trunc('second', gn.timestamp)  -- Truncate to seconds
                                )
                            )
                            FROM groups.group_notes gn
                            WHERE gn.to_member_id = u.id
                            AND gn.group_id = g.id
                        ), '[]'::json)
                    )
                ), '[]'::json)
                FROM groups.group_members gm
                JOIN users u ON gm.user_id = u.id
                WHERE gm.group_id = g.id
            ),
            'activity', COALESCE((
                SELECT json_agg(
                    json_build_object(
                        'memberID', ga.user_id,
                        'type', ga.activity,
                        'timestamp', date_trunc('second', ga.timestamp)  -- Truncate to seconds
                    )
                )
                FROM groups.group_activity ga
                WHERE ga.group_id = g.id
            ), '[]'::json),
            'subscribed', (
                SELECT COALESCE(json_agg(
                    json_build_object(
                        'subscribedTo', gs.subscribed_to
                    )
                ), '[]'::json)
                FROM groups.group_subscriptions gs
                WHERE gs.group_id = get_group.group_id
                AND gs.user_id = get_group.user_id
            )
        )
        FROM groups.groups g
        WHERE g.id = get_group.group_id
    );
END;$function$
;

CREATE OR REPLACE FUNCTION public.rem_group_mem(user_id text, group_id uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$BEGIN
    -- Step 1: Remove all activities related to the user and group
    DELETE FROM groups.group_activity ga
    WHERE ga.user_id = rem_group_mem.user_id
      AND ga.group_id = rem_group_mem.group_id;

    -- Step 2: Remove the user from the group_members table
    DELETE FROM groups.group_members gm
    WHERE gm.user_id = rem_group_mem.user_id
      AND gm.group_id = rem_group_mem.group_id;

    -- Step 3: Remove all subscriptions for the user and group
    DELETE FROM groups.group_subscriptions gs
    WHERE gs.user_id = rem_group_mem.user_id
      AND gs.group_id = rem_group_mem.group_id;

    -- Step 4: Remove all related group notes (sent or received by the user)
    DELETE FROM groups.group_notes gn
    WHERE gn.group_id = rem_group_mem.group_id
      AND (gn.to_member_id = rem_group_mem.user_id OR gn.from_member_id = rem_group_mem.user_id);

    -- Step 5: Check if the user was the last member of the group
    IF NOT EXISTS (
        SELECT 1 FROM groups.group_members gm
        WHERE gm.group_id = rem_group_mem.group_id
    ) THEN
        -- Call the delete_group function to delete the group if no members remain
        PERFORM delete_group(rem_group_mem.group_id);
    END IF;
END;$function$
;

CREATE OR REPLACE FUNCTION public.submit_feedback(user_id text, feedback text)
 RETURNS void
 LANGUAGE plpgsql
AS $function$BEGIN
    INSERT INTO comms.feedback (user_id, feedback, timestamp)
    VALUES (user_id, feedback, CURRENT_TIMESTAMP);
END;$function$
;

CREATE OR REPLACE FUNCTION public.update_group(group_data json)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$DECLARE
    var_group_id UUID;
    var_member_record JSON;
    activity_record_json JSON;
    note_record JSON;
    member_id TEXT;
    note_id TEXT;
    activity_id TEXT;
BEGIN
    -- Update the groups table
    var_group_id := (group_data->>'id')::UUID;

    -- 1. DELETE missing members, notes, and activities
    -- Delete members that are not present in the updated JSON
    DELETE FROM groups.group_members
    WHERE group_id = var_group_id
    AND user_id NOT IN (
        SELECT (member_record->>'memberID')::TEXT
        FROM json_array_elements(group_data->'members') AS member_record
    );

    -- Delete notes for members that are not present in the updated JSON
    DELETE FROM groups.group_notes
    WHERE group_id = var_group_id
    AND to_member_id NOT IN (
        SELECT (member_record->>'memberID')::TEXT
        FROM json_array_elements(group_data->'members') AS member_record
    );

    -- Delete activities that are not present in the updated JSON
    DELETE FROM groups.group_activity
    WHERE group_id = var_group_id
    AND user_id NOT IN (
        SELECT (activity_record->>'memberID')::TEXT
        FROM json_array_elements(group_data->'activity') AS activity_record
    );

    -- 2. Insert/Update users before any group operations
    FOR var_member_record IN SELECT * FROM json_array_elements(group_data->'members')
    LOOP
        member_id := var_member_record->>'memberID';  -- No UUID cast, keeping it as TEXT

        -- Properly handle daysSober as a boolean[] array, with true, false, and null values
        INSERT INTO users (id, name, emoji, days_sober, initial_frequency, show_in_group_rank)
        VALUES (
            member_id, 
            var_member_record->>'name', 
            var_member_record->>'emoji', 
            ARRAY(
                SELECT 
                    CASE 
                        WHEN value = 'true' THEN TRUE
                        WHEN value = 'false' THEN FALSE
                        WHEN value = 'null' THEN NULL
                        ELSE NULL  -- Handle any unexpected values as NULL
                    END
                FROM json_array_elements_text(var_member_record->'daysSober') AS value
            )::boolean[],  -- Cast to boolean[] with proper handling for true, false, and null
            (var_member_record->>'initialFrequency')::NUMERIC, 
            (var_member_record->>'showInRank')::BOOLEAN
        )
        ON CONFLICT (id) DO UPDATE 
        SET name = EXCLUDED.name,
            emoji = EXCLUDED.emoji,
            days_sober = EXCLUDED.days_sober,
            initial_frequency = EXCLUDED.initial_frequency,
            show_in_group_rank = EXCLUDED.show_in_group_rank;
    END LOOP;

    -- 3. Update or Insert the group details after deletions and user insertions
    INSERT INTO groups.groups (id, name, hue)
    VALUES (var_group_id, group_data->>'name', (group_data->>'hue')::NUMERIC)
    ON CONFLICT (id) DO UPDATE 
    SET name = EXCLUDED.name,
        hue = EXCLUDED.hue;

    -- 4. Insert/Update members and their related notes
    FOR var_member_record IN SELECT * FROM json_array_elements(group_data->'members')
    LOOP
        member_id := var_member_record->>'memberID';  -- No UUID cast, keeping it as TEXT

        -- Update or Insert the member in the group_members table
        INSERT INTO groups.group_members (group_id, user_id)
        VALUES (var_group_id, member_id)  -- Explicitly using var_group_id to avoid ambiguity
        ON CONFLICT (group_id, user_id) DO NOTHING;

        -- Loop through notes and update group_notes
        FOR note_record IN SELECT * FROM json_array_elements(var_member_record->'notes')
        LOOP
            -- Update or Insert notes
            INSERT INTO groups.group_notes (group_id, to_member_id, from_member_id, message, timestamp)
            VALUES (
                var_group_id,  
                member_id,  
                note_record->>'fromMemberID',  
                note_record->>'message', 
                (note_record->>'timestamp')::TIMESTAMP
            )
            ON CONFLICT (group_id, from_member_id, to_member_id, timestamp)
            DO UPDATE SET message = EXCLUDED.message;
            
        END LOOP;
    END LOOP;

    -- 5. Insert/Update activities
    FOR activity_record_json IN SELECT * FROM json_array_elements(group_data->'activity')
    LOOP
        activity_id := activity_record_json->>'memberID';  -- user_id is TEXT
        
        -- Update or Insert activity
        INSERT INTO groups.group_activity (group_id, user_id, activity, timestamp)
        VALUES (
            var_group_id,  -- Explicitly using var_group_id to avoid ambiguity
            activity_id,  -- user_id is TEXT
            (activity_record_json->>'type')::group_activity_type, 
            (activity_record_json->>'timestamp')::TIMESTAMP
        )
        ON CONFLICT (group_id, user_id, timestamp) DO UPDATE 
        SET activity = EXCLUDED.activity;
    END LOOP;

END;$function$
;

CREATE OR REPLACE FUNCTION public.update_group_activity(group_id uuid, user_id text, activity_data jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$BEGIN
    WITH json_activities AS (
        -- Step 1: Unnest the JSONB array into a table format for easy comparison
        SELECT 
            -- Associate all activities with the provided user_id
            update_group_activity.user_id AS user_id,
            -- Map string values to the corresponding enum type
            CASE
                WHEN activity->>'type' = 'smoked' THEN 'smoked'::group_activity_type
                WHEN activity->>'type' = 'sober' THEN 'sober'::group_activity_type
                WHEN activity->>'type' = 'joined' THEN 'joined'::group_activity_type
                WHEN activity->>'type' = 'message' THEN 'message'::group_activity_type
                ELSE NULL
            END AS activity_type,
            (activity->>'timestamp')::timestamptz AS activity_timestamp
        FROM jsonb_array_elements(activity_data) AS activity
    ),
    -- Step 2: Delete activities for the specified user that are in the table but not in the provided JSON
    delete_activities AS (
        DELETE FROM groups.group_activity ga
        WHERE ga.group_id = update_group_activity.group_id
          AND ga.user_id = update_group_activity.user_id
          AND NOT EXISTS (
              SELECT 1 FROM json_activities ja
              WHERE ja.user_id = ga.user_id
                AND ja.activity_type = ga.activity
                AND ja.activity_timestamp = ga.timestamp
          )
        RETURNING *
    )
    -- Step 3: Insert activities from JSON if they don't already exist in the table
    INSERT INTO groups.group_activity (group_id, user_id, activity, timestamp)
    SELECT update_group_activity.group_id, ja.user_id, ja.activity_type, ja.activity_timestamp
    FROM json_activities ja
    WHERE ja.activity_type IS NOT NULL  -- Only insert valid activity types
      AND NOT EXISTS (
        SELECT 1 FROM groups.group_activity ga
        WHERE ga.group_id = update_group_activity.group_id
          AND ga.user_id = update_group_activity.user_id
          AND ga.activity = ja.activity_type
          AND ga.timestamp = ja.activity_timestamp
    );
END;$function$
;

CREATE OR REPLACE FUNCTION public.update_group_subscriptions(group_id uuid, user_id text, subscriptions jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$BEGIN
    -- 1. Check if the user is in the group
    IF NOT EXISTS (
        SELECT 1 
        FROM groups.group_members
        WHERE group_members.group_id = update_group_subscriptions.group_id
        AND group_members.user_id = update_group_subscriptions.user_id
    ) THEN
        RAISE EXCEPTION 'User is not a member of the group';
    END IF;

    -- 2. Remove all existing rows in group_subscriptions for the group_id and user_id
    DELETE FROM groups.group_subscriptions
    WHERE group_subscriptions.group_id = update_group_subscriptions.group_id
    AND group_subscriptions.user_id = update_group_subscriptions.user_id;

    -- 3. Insert new subscriptions into group_subscriptions
    INSERT INTO groups.group_subscriptions (group_id, user_id, subscribed_to)
    SELECT update_group_subscriptions.group_id, update_group_subscriptions.user_id, value::TEXT
    FROM jsonb_array_elements_text(update_group_subscriptions.subscriptions) AS value;

END;$function$
;

CREATE OR REPLACE FUNCTION public.upsert_group(group_data jsonb, user_id text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$BEGIN
    -- If an 'id' is provided, check if the group exists and the user is part of the group
    IF group_data ? 'id' THEN
        -- Check if the group exists
        IF EXISTS (SELECT 1 FROM groups.groups WHERE id = (group_data->>'id')::uuid) THEN
            -- Check if the user is part of the group
            IF NOT EXISTS (
                SELECT 1
                FROM groups.group_members gm
                WHERE gm.group_id = (group_data->>'id')::uuid
                  AND gm.user_id = upsert_group.user_id
            ) THEN
                -- Raise an exception if the user is not part of the group
                RAISE EXCEPTION 'User % is not a member of the group %', upsert_group.user_id, group_data->>'id';
            END IF;
        END IF;

        -- Insert or update the group with the provided 'id'
        INSERT INTO groups.groups (
            id, 
            name, 
            hue
        )
        VALUES (
            (group_data->>'id')::uuid, -- Use the provided 'id'
            group_data->>'name',        -- Name must be provided for creation
            (group_data->>'hue')::numeric -- Hue must be provided for creation
        )
        ON CONFLICT (id)
        DO UPDATE
        SET name = COALESCE(group_data->>'name', groups.name),
            hue = COALESCE((group_data->>'hue')::numeric, groups.hue);

    ELSE
        -- Insert without 'id', letting Supabase generate the UUID
        INSERT INTO groups.groups (
            name, 
            hue
        )
        VALUES (
            group_data->>'name', -- Name must be provided for creation
            (group_data->>'hue')::numeric -- Hue must be provided for creation
        );
    END IF;
END;$function$
;


