
create table "comms"."sms_messages" (
    "id" bigint generated by default as identity not null,
    "user_id" text not null default ''::text,
    "phone_number" text not null,
    "text" text not null,
    "outbound" boolean not null default 'true'::boolean,
    "scheduled_for" timestamp with time zone not null,
    "created_at" timestamp with time zone not null default now(),
    "twilio_id" text not null
);


create table "comms"."sms_statuses" (
    "id" bigint generated by default as identity not null,
    "message_id" bigint not null,
    "status" text not null
);


CREATE UNIQUE INDEX sms_messages_pkey ON comms.sms_messages USING btree (id);

CREATE UNIQUE INDEX sms_statuses_pkey ON comms.sms_statuses USING btree (id);

alter table "comms"."sms_messages" add constraint "sms_messages_pkey" PRIMARY KEY using index "sms_messages_pkey";

alter table "comms"."sms_statuses" add constraint "sms_statuses_pkey" PRIMARY KEY using index "sms_statuses_pkey";

alter table "comms"."sms_messages" add constraint "sms_messages_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) not valid;

alter table "comms"."sms_messages" validate constraint "sms_messages_user_id_fkey";

alter table "comms"."sms_statuses" add constraint "sms_statuses_message_id_fkey" FOREIGN KEY (message_id) REFERENCES comms.sms_messages(id) not valid;

alter table "comms"."sms_statuses" validate constraint "sms_statuses_message_id_fkey";


alter table "public"."users" add column "auth_id" uuid;

alter table "public"."users" add column "phone_number" text;

CREATE UNIQUE INDEX users_auth_id_key ON public.users USING btree (auth_id);

alter table "public"."users" add constraint "users_auth_id_fkey" FOREIGN KEY (auth_id) REFERENCES auth.users(id) not valid;

alter table "public"."users" validate constraint "users_auth_id_fkey";

alter table "public"."users" add constraint "users_auth_id_key" UNIQUE using index "users_auth_id_key";


