create table "library"."push_abandoned_onboarding" (
    "id" bigint generated by default as identity not null,
    "title" text,
    "body" text not null,
    "question_id" text,
    "question_response" text
);


alter table "library"."push_abandoned_onboarding" enable row level security;

CREATE UNIQUE INDEX push_abandoned_onboarding_pkey ON library.push_abandoned_onboarding USING btree (id);

alter table "library"."push_abandoned_onboarding" add constraint "push_abandoned_onboarding_pkey" PRIMARY KEY using index "push_abandoned_onboarding_pkey";

grant delete on table "library"."push_abandoned_onboarding" to "anon";

grant insert on table "library"."push_abandoned_onboarding" to "anon";

grant references on table "library"."push_abandoned_onboarding" to "anon";

grant select on table "library"."push_abandoned_onboarding" to "anon";

grant trigger on table "library"."push_abandoned_onboarding" to "anon";

grant truncate on table "library"."push_abandoned_onboarding" to "anon";

grant update on table "library"."push_abandoned_onboarding" to "anon";

grant delete on table "library"."push_abandoned_onboarding" to "authenticated";

grant insert on table "library"."push_abandoned_onboarding" to "authenticated";

grant references on table "library"."push_abandoned_onboarding" to "authenticated";

grant select on table "library"."push_abandoned_onboarding" to "authenticated";

grant trigger on table "library"."push_abandoned_onboarding" to "authenticated";

grant truncate on table "library"."push_abandoned_onboarding" to "authenticated";

grant update on table "library"."push_abandoned_onboarding" to "authenticated";

grant delete on table "library"."push_abandoned_onboarding" to "service_role";

grant insert on table "library"."push_abandoned_onboarding" to "service_role";

grant references on table "library"."push_abandoned_onboarding" to "service_role";

grant select on table "library"."push_abandoned_onboarding" to "service_role";

grant trigger on table "library"."push_abandoned_onboarding" to "service_role";

grant truncate on table "library"."push_abandoned_onboarding" to "service_role";

grant update on table "library"."push_abandoned_onboarding" to "service_role";

create policy "Access to all"
on "library"."push_abandoned_onboarding"
as permissive
for select
to public
using (true);



create table "payment"."trial_notifications" (
    "id" bigint generated by default as identity not null,
    "title" text not null,
    "body" text not null
);


alter table "payment"."trial_notifications" enable row level security;

CREATE UNIQUE INDEX trial_notifications_pkey ON payment.trial_notifications USING btree (id);

alter table "payment"."trial_notifications" add constraint "trial_notifications_pkey" PRIMARY KEY using index "trial_notifications_pkey";

grant delete on table "payment"."trial_notifications" to "anon";

grant insert on table "payment"."trial_notifications" to "anon";

grant references on table "payment"."trial_notifications" to "anon";

grant select on table "payment"."trial_notifications" to "anon";

grant trigger on table "payment"."trial_notifications" to "anon";

grant truncate on table "payment"."trial_notifications" to "anon";

grant update on table "payment"."trial_notifications" to "anon";

grant delete on table "payment"."trial_notifications" to "authenticated";

grant insert on table "payment"."trial_notifications" to "authenticated";

grant references on table "payment"."trial_notifications" to "authenticated";

grant select on table "payment"."trial_notifications" to "authenticated";

grant trigger on table "payment"."trial_notifications" to "authenticated";

grant truncate on table "payment"."trial_notifications" to "authenticated";

grant update on table "payment"."trial_notifications" to "authenticated";

grant delete on table "payment"."trial_notifications" to "service_role";

grant insert on table "payment"."trial_notifications" to "service_role";

grant references on table "payment"."trial_notifications" to "service_role";

grant select on table "payment"."trial_notifications" to "service_role";

grant trigger on table "payment"."trial_notifications" to "service_role";

grant truncate on table "payment"."trial_notifications" to "service_role";

grant update on table "payment"."trial_notifications" to "service_role";

create policy "Authed can access"
on "payment"."trial_notifications"
as permissive
for select
to public
using ((( SELECT get_user_id() AS get_user_id) IS NOT NULL));



