create table "library"."craving_resources" (
    "id" bigint generated by default as identity not null,
    "type" text not null,
    "data" jsonb not null
);


alter table "library"."craving_resources" enable row level security;

CREATE UNIQUE INDEX cravings_resources_pkey ON library.craving_resources USING btree (id);

alter table "library"."craving_resources" add constraint "cravings_resources_pkey" PRIMARY KEY using index "cravings_resources_pkey";

grant delete on table "library"."craving_resources" to "anon";

grant insert on table "library"."craving_resources" to "anon";

grant references on table "library"."craving_resources" to "anon";

grant select on table "library"."craving_resources" to "anon";

grant trigger on table "library"."craving_resources" to "anon";

grant truncate on table "library"."craving_resources" to "anon";

grant update on table "library"."craving_resources" to "anon";

grant delete on table "library"."craving_resources" to "authenticated";

grant insert on table "library"."craving_resources" to "authenticated";

grant references on table "library"."craving_resources" to "authenticated";

grant select on table "library"."craving_resources" to "authenticated";

grant trigger on table "library"."craving_resources" to "authenticated";

grant truncate on table "library"."craving_resources" to "authenticated";

grant update on table "library"."craving_resources" to "authenticated";

grant delete on table "library"."craving_resources" to "service_role";

grant insert on table "library"."craving_resources" to "service_role";

grant references on table "library"."craving_resources" to "service_role";

grant select on table "library"."craving_resources" to "service_role";

grant trigger on table "library"."craving_resources" to "service_role";

grant truncate on table "library"."craving_resources" to "service_role";

grant update on table "library"."craving_resources" to "service_role";

grant delete on table "library"."push_check_in" to "anon";

grant insert on table "library"."push_check_in" to "anon";

grant references on table "library"."push_check_in" to "anon";

grant select on table "library"."push_check_in" to "anon";

grant trigger on table "library"."push_check_in" to "anon";

grant truncate on table "library"."push_check_in" to "anon";

grant update on table "library"."push_check_in" to "anon";

grant delete on table "library"."sms_eow_summary" to "anon";

grant insert on table "library"."sms_eow_summary" to "anon";

grant references on table "library"."sms_eow_summary" to "anon";

grant select on table "library"."sms_eow_summary" to "anon";

grant trigger on table "library"."sms_eow_summary" to "anon";

grant truncate on table "library"."sms_eow_summary" to "anon";

grant update on table "library"."sms_eow_summary" to "anon";

grant delete on table "library"."sms_eow_summary" to "authenticated";

grant insert on table "library"."sms_eow_summary" to "authenticated";

grant references on table "library"."sms_eow_summary" to "authenticated";

grant select on table "library"."sms_eow_summary" to "authenticated";

grant trigger on table "library"."sms_eow_summary" to "authenticated";

grant truncate on table "library"."sms_eow_summary" to "authenticated";

grant update on table "library"."sms_eow_summary" to "authenticated";

grant delete on table "library"."sms_inactive" to "anon";

grant insert on table "library"."sms_inactive" to "anon";

grant references on table "library"."sms_inactive" to "anon";

grant select on table "library"."sms_inactive" to "anon";

grant trigger on table "library"."sms_inactive" to "anon";

grant truncate on table "library"."sms_inactive" to "anon";

grant update on table "library"."sms_inactive" to "anon";

grant delete on table "library"."sms_inactive" to "authenticated";

grant insert on table "library"."sms_inactive" to "authenticated";

grant references on table "library"."sms_inactive" to "authenticated";

grant select on table "library"."sms_inactive" to "authenticated";

grant trigger on table "library"."sms_inactive" to "authenticated";

grant truncate on table "library"."sms_inactive" to "authenticated";

grant update on table "library"."sms_inactive" to "authenticated";

create policy "Access to all"
on "library"."craving_resources"
as permissive
for select
to public
using (true);



