alter table "platform"."conversation_tags" alter column "id" drop default;

alter table "platform"."conversation_tags" alter column "id" add generated by default as identity;

alter table "platform"."tags" alter column "id" drop default;

alter table "platform"."tags" alter column "id" add generated by default as identity;


