create table "payment"."product_discount_codes" (
    "id" bigint generated by default as identity not null,
    "product_id" text not null,
    "shopify_discount_code" text not null,
    "enabled" boolean not null default true,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
);

alter table "payment"."product_discount_codes" enable row level security;

CREATE UNIQUE INDEX product_discount_codes_pkey ON payment.product_discount_codes USING btree (id);

CREATE INDEX product_discount_codes_product_id ON payment.product_discount_codes USING btree (product_id);

CREATE INDEX product_discount_codes_enabled ON payment.product_discount_codes USING btree (enabled);

alter table "payment"."product_discount_codes" add constraint "product_discount_codes_pkey" PRIMARY KEY using index "product_discount_codes_pkey";

create policy "Disable all access"
on "payment"."product_discount_codes"
as permissive
for all
to public
using (false);

