
create table "library"."sms_eow_summary" (
    "id" bigint generated by default as identity not null,
    "program" text default ''::text,
    "question_id" text,
    "question_response" text,
    "check_in_days" bigint,
    "sober_days" bigint,
    "message" text not null
);

grant usage on schema "programs" to "service_role";

alter table "library"."sms_eow_summary" enable row level security;

CREATE UNIQUE INDEX sms_eow_summary_pkey ON library.sms_eow_summary USING btree (id);

alter table "library"."sms_eow_summary" add constraint "sms_eow_summary_pkey" PRIMARY KEY using index "sms_eow_summary_pkey";

alter table "library"."sms_eow_summary" add constraint "sms_eow_summary_program_fkey" FOREIGN KEY (program) REFERENCES programs.programs(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "library"."sms_eow_summary" validate constraint "sms_eow_summary_program_fkey";

grant delete on table "library"."sms_eow_summary" to "service_role";

grant insert on table "library"."sms_eow_summary" to "service_role";

grant references on table "library"."sms_eow_summary" to "service_role";

grant select on table "library"."sms_eow_summary" to "service_role";

grant trigger on table "library"."sms_eow_summary" to "service_role";

grant truncate on table "library"."sms_eow_summary" to "service_role";

grant update on table "library"."sms_eow_summary" to "service_role";


grant delete on table "programs"."program_assessment_responses" to "service_role";

grant insert on table "programs"."program_assessment_responses" to "service_role";

grant references on table "programs"."program_assessment_responses" to "service_role";

grant select on table "programs"."program_assessment_responses" to "service_role";

grant trigger on table "programs"."program_assessment_responses" to "service_role";

grant truncate on table "programs"."program_assessment_responses" to "service_role";

grant update on table "programs"."program_assessment_responses" to "service_role";

grant delete on table "programs"."program_assessments" to "service_role";

grant insert on table "programs"."program_assessments" to "service_role";

grant references on table "programs"."program_assessments" to "service_role";

grant select on table "programs"."program_assessments" to "service_role";

grant trigger on table "programs"."program_assessments" to "service_role";

grant truncate on table "programs"."program_assessments" to "service_role";

grant update on table "programs"."program_assessments" to "service_role";

grant delete on table "programs"."program_feedback" to "service_role";

grant insert on table "programs"."program_feedback" to "service_role";

grant references on table "programs"."program_feedback" to "service_role";

grant select on table "programs"."program_feedback" to "service_role";

grant trigger on table "programs"."program_feedback" to "service_role";

grant truncate on table "programs"."program_feedback" to "service_role";

grant update on table "programs"."program_feedback" to "service_role";

grant delete on table "programs"."program_guides" to "service_role";

grant insert on table "programs"."program_guides" to "service_role";

grant references on table "programs"."program_guides" to "service_role";

grant select on table "programs"."program_guides" to "service_role";

grant trigger on table "programs"."program_guides" to "service_role";

grant truncate on table "programs"."program_guides" to "service_role";

grant update on table "programs"."program_guides" to "service_role";

grant delete on table "programs"."program_guides_qa" to "service_role";

grant insert on table "programs"."program_guides_qa" to "service_role";

grant references on table "programs"."program_guides_qa" to "service_role";

grant select on table "programs"."program_guides_qa" to "service_role";

grant trigger on table "programs"."program_guides_qa" to "service_role";

grant truncate on table "programs"."program_guides_qa" to "service_role";

grant update on table "programs"."program_guides_qa" to "service_role";

grant delete on table "programs"."program_messages" to "service_role";

grant insert on table "programs"."program_messages" to "service_role";

grant references on table "programs"."program_messages" to "service_role";

grant select on table "programs"."program_messages" to "service_role";

grant trigger on table "programs"."program_messages" to "service_role";

grant truncate on table "programs"."program_messages" to "service_role";

grant update on table "programs"."program_messages" to "service_role";

grant delete on table "programs"."program_messages_qa" to "service_role";

grant insert on table "programs"."program_messages_qa" to "service_role";

grant references on table "programs"."program_messages_qa" to "service_role";

grant select on table "programs"."program_messages_qa" to "service_role";

grant trigger on table "programs"."program_messages_qa" to "service_role";

grant truncate on table "programs"."program_messages_qa" to "service_role";

grant update on table "programs"."program_messages_qa" to "service_role";

grant delete on table "programs"."program_stages" to "service_role";

grant insert on table "programs"."program_stages" to "service_role";

grant references on table "programs"."program_stages" to "service_role";

grant select on table "programs"."program_stages" to "service_role";

grant trigger on table "programs"."program_stages" to "service_role";

grant truncate on table "programs"."program_stages" to "service_role";

grant update on table "programs"."program_stages" to "service_role";

grant delete on table "programs"."programs" to "service_role";

grant insert on table "programs"."programs" to "service_role";

grant references on table "programs"."programs" to "service_role";

grant select on table "programs"."programs" to "service_role";

grant trigger on table "programs"."programs" to "service_role";

grant truncate on table "programs"."programs" to "service_role";

grant update on table "programs"."programs" to "service_role";

