alter table "community"."tags" alter column "type" drop default;

alter type "community"."tag_type" rename to "tag_type__old_version_to_be_dropped";

create type "community"."tag_type" as enum ('program', 'day', 'event', 'general', 'lobby');

alter table "community"."tags" alter column type type "community"."tag_type" using type::text::"community"."tag_type";

alter table "community"."tags" alter column "type" set default 'general'::community.tag_type;

drop type "community"."tag_type__old_version_to_be_dropped";


create schema if not exists "events";

create table "events"."event_pop_ups" (
    "id" bigint generated by default as identity not null,
    "event" text not null,
    "start_date" date not null,
    "end_date" date not null,
    "text" text not null
);


alter table "events"."event_pop_ups" enable row level security;

create table "events"."events" (
    "id" text not null,
    "name" text not null,
    "short_name" text not null,
    "num_waiting" bigint not null,
    "onboarding_start_date" date not null,
    "onboarding_end_date" date not null,
    "program_day_1" date not null,
    "app_unlock_date" date not null,
    "color1" text not null,
    "color2" text not null,
    "sms_id" text not null,
    "lobby_community_tag" uuid not null,
    "community_tag" uuid,
    "end_date" date not null default now()
);


alter table "events"."events" enable row level security;

CREATE UNIQUE INDEX event_pop_ups_pkey ON events.event_pop_ups USING btree (id);

CREATE UNIQUE INDEX events_pkey ON events.events USING btree (id);

alter table "events"."event_pop_ups" add constraint "event_pop_ups_pkey" PRIMARY KEY using index "event_pop_ups_pkey";

alter table "events"."events" add constraint "events_pkey" PRIMARY KEY using index "events_pkey";

alter table "events"."event_pop_ups" add constraint "event_pop_ups_event_fkey" FOREIGN KEY (event) REFERENCES events.events(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "events"."event_pop_ups" validate constraint "event_pop_ups_event_fkey";

alter table "events"."events" add constraint "events_community_tag_fkey" FOREIGN KEY (community_tag) REFERENCES community.tags(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "events"."events" validate constraint "events_community_tag_fkey";

alter table "events"."events" add constraint "events_lobby_community_tag_fkey" FOREIGN KEY (lobby_community_tag) REFERENCES community.tags(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "events"."events" validate constraint "events_lobby_community_tag_fkey";

grant delete on table "events"."event_pop_ups" to "anon";

grant insert on table "events"."event_pop_ups" to "anon";

grant references on table "events"."event_pop_ups" to "anon";

grant select on table "events"."event_pop_ups" to "anon";

grant trigger on table "events"."event_pop_ups" to "anon";

grant truncate on table "events"."event_pop_ups" to "anon";

grant update on table "events"."event_pop_ups" to "anon";

grant delete on table "events"."event_pop_ups" to "authenticated";

grant insert on table "events"."event_pop_ups" to "authenticated";

grant references on table "events"."event_pop_ups" to "authenticated";

grant select on table "events"."event_pop_ups" to "authenticated";

grant trigger on table "events"."event_pop_ups" to "authenticated";

grant truncate on table "events"."event_pop_ups" to "authenticated";

grant update on table "events"."event_pop_ups" to "authenticated";

grant delete on table "events"."event_pop_ups" to "service_role";

grant insert on table "events"."event_pop_ups" to "service_role";

grant references on table "events"."event_pop_ups" to "service_role";

grant select on table "events"."event_pop_ups" to "service_role";

grant trigger on table "events"."event_pop_ups" to "service_role";

grant truncate on table "events"."event_pop_ups" to "service_role";

grant update on table "events"."event_pop_ups" to "service_role";

grant delete on table "events"."events" to "anon";

grant insert on table "events"."events" to "anon";

grant references on table "events"."events" to "anon";

grant select on table "events"."events" to "anon";

grant trigger on table "events"."events" to "anon";

grant truncate on table "events"."events" to "anon";

grant update on table "events"."events" to "anon";

grant delete on table "events"."events" to "authenticated";

grant insert on table "events"."events" to "authenticated";

grant references on table "events"."events" to "authenticated";

grant select on table "events"."events" to "authenticated";

grant trigger on table "events"."events" to "authenticated";

grant truncate on table "events"."events" to "authenticated";

grant update on table "events"."events" to "authenticated";

grant delete on table "events"."events" to "service_role";

grant insert on table "events"."events" to "service_role";

grant references on table "events"."events" to "service_role";

grant select on table "events"."events" to "service_role";

grant trigger on table "events"."events" to "service_role";

grant truncate on table "events"."events" to "service_role";

grant update on table "events"."events" to "service_role";

grant usage on schema events to "anon";
grant usage on schema events to "authenticated";
grant usage on schema events to "service_role";

create policy "Use is authed"
on "events"."event_pop_ups"
as permissive
for select
to public
using (( SELECT (auth.uid() IS NOT NULL)));


create policy "All can select"
on "events"."events"
as permissive
for select
to public
using (true);



