create schema if not exists "guardian";

grant usage on schema guardian to "anon";
grant usage on schema guardian to "authenticated";
grant usage on schema guardian to "service_role";

create table "guardian"."code_users" (
    "id" bigint generated by default as identity not null,
    "code" text not null default ''::text,
    "user_id" text not null,
    "notify_guardian" boolean not null default false
);


alter table "guardian"."code_users" enable row level security;

create table "guardian"."codes" (
    "creator" text not null,
    "code" text not null,
    "free" boolean not null default false,
    "created_at" timestamp with time zone not null default now(),
    "program" text not null default 'adolescent'::text,
    "guardian_email" text not null,
    "uses" integer not null default 0
);


alter table "guardian"."codes" enable row level security;

CREATE UNIQUE INDEX code_users_pkey ON guardian.code_users USING btree (id);

CREATE UNIQUE INDEX codes_pkey ON guardian.codes USING btree (code);

alter table "guardian"."code_users" add constraint "code_users_pkey" PRIMARY KEY using index "code_users_pkey";

alter table "guardian"."codes" add constraint "codes_pkey" PRIMARY KEY using index "codes_pkey";

alter table "guardian"."code_users" add constraint "code_users_code_fkey" FOREIGN KEY (code) REFERENCES guardian.codes(code) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "guardian"."code_users" validate constraint "code_users_code_fkey";

alter table "guardian"."code_users" add constraint "code_users_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "guardian"."code_users" validate constraint "code_users_user_id_fkey";

alter table "guardian"."codes" add constraint "codes_program_fkey" FOREIGN KEY (program) REFERENCES programs.programs(id) ON UPDATE CASCADE ON DELETE SET DEFAULT not valid;

alter table "guardian"."codes" validate constraint "codes_program_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION guardian.check_code(input_code text)
 RETURNS TABLE(code text, free boolean, program text)
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
    RETURN QUERY
    SELECT 
        c.code,
        c.free,
        c.program
    FROM guardian.codes c
    WHERE c.code = input_code;
END;
$function$
;

grant delete on table "guardian"."code_users" to "anon";

grant insert on table "guardian"."code_users" to "anon";

grant references on table "guardian"."code_users" to "anon";

grant select on table "guardian"."code_users" to "anon";

grant trigger on table "guardian"."code_users" to "anon";

grant truncate on table "guardian"."code_users" to "anon";

grant update on table "guardian"."code_users" to "anon";

grant delete on table "guardian"."code_users" to "authenticated";

grant insert on table "guardian"."code_users" to "authenticated";

grant references on table "guardian"."code_users" to "authenticated";

grant select on table "guardian"."code_users" to "authenticated";

grant trigger on table "guardian"."code_users" to "authenticated";

grant truncate on table "guardian"."code_users" to "authenticated";

grant update on table "guardian"."code_users" to "authenticated";

grant delete on table "guardian"."code_users" to "service_role";

grant insert on table "guardian"."code_users" to "service_role";

grant references on table "guardian"."code_users" to "service_role";

grant select on table "guardian"."code_users" to "service_role";

grant trigger on table "guardian"."code_users" to "service_role";

grant truncate on table "guardian"."code_users" to "service_role";

grant update on table "guardian"."code_users" to "service_role";

grant delete on table "guardian"."codes" to "anon";

grant insert on table "guardian"."codes" to "anon";

grant references on table "guardian"."codes" to "anon";

grant select on table "guardian"."codes" to "anon";

grant trigger on table "guardian"."codes" to "anon";

grant truncate on table "guardian"."codes" to "anon";

grant update on table "guardian"."codes" to "anon";

grant delete on table "guardian"."codes" to "authenticated";

grant insert on table "guardian"."codes" to "authenticated";

grant references on table "guardian"."codes" to "authenticated";

grant select on table "guardian"."codes" to "authenticated";

grant trigger on table "guardian"."codes" to "authenticated";

grant truncate on table "guardian"."codes" to "authenticated";

grant update on table "guardian"."codes" to "authenticated";

grant delete on table "guardian"."codes" to "service_role";

grant insert on table "guardian"."codes" to "service_role";

grant references on table "guardian"."codes" to "service_role";

grant select on table "guardian"."codes" to "service_role";

grant trigger on table "guardian"."codes" to "service_role";

grant truncate on table "guardian"."codes" to "service_role";

grant update on table "guardian"."codes" to "service_role";

create policy "Users can insert for self"
on "guardian"."code_users"
as permissive
for insert
to public
with check ((user_id = ( SELECT get_user_id() AS get_user_id)));


create policy "Disable all access"
on "guardian"."codes"
as permissive
for all
to public
using (false);



