create table "public"."amplitude_test" (
    "id" bigint generated by default as identity not null,
    "text" text not null
);


alter table "public"."amplitude_test" enable row level security;

CREATE UNIQUE INDEX amplitude_test_pkey ON public.amplitude_test USING btree (id);

alter table "public"."amplitude_test" add constraint "amplitude_test_pkey" PRIMARY KEY using index "amplitude_test_pkey";

grant delete on table "public"."amplitude_test" to "anon";

grant insert on table "public"."amplitude_test" to "anon";

grant references on table "public"."amplitude_test" to "anon";

grant select on table "public"."amplitude_test" to "anon";

grant trigger on table "public"."amplitude_test" to "anon";

grant truncate on table "public"."amplitude_test" to "anon";

grant update on table "public"."amplitude_test" to "anon";

grant delete on table "public"."amplitude_test" to "authenticated";

grant insert on table "public"."amplitude_test" to "authenticated";

grant references on table "public"."amplitude_test" to "authenticated";

grant select on table "public"."amplitude_test" to "authenticated";

grant trigger on table "public"."amplitude_test" to "authenticated";

grant truncate on table "public"."amplitude_test" to "authenticated";

grant update on table "public"."amplitude_test" to "authenticated";

grant delete on table "public"."amplitude_test" to "service_role";

grant insert on table "public"."amplitude_test" to "service_role";

grant references on table "public"."amplitude_test" to "service_role";

grant select on table "public"."amplitude_test" to "service_role";

grant trigger on table "public"."amplitude_test" to "service_role";

grant truncate on table "public"."amplitude_test" to "service_role";

grant update on table "public"."amplitude_test" to "service_role";

create policy "Disable all access"
on "public"."amplitude_test"
as permissive
for all
to public
using (false);



