create table "community"."reactions" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" text,
    "post_id" uuid not null,
    "emoji" character varying not null
);


alter table "community"."reactions" enable row level security;

CREATE UNIQUE INDEX reactions_pkey ON community.reactions USING btree (id);

alter table "community"."reactions" add constraint "reactions_pkey" PRIMARY KEY using index "reactions_pkey";

alter table "community"."reactions" add constraint "reactions_post_id_fkey" FOREIGN KEY (post_id) REFERENCES community.posts(id) not valid;

alter table "community"."reactions" validate constraint "reactions_post_id_fkey";

alter table "community"."reactions" add constraint "reactions_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) not valid;

alter table "community"."reactions" validate constraint "reactions_user_id_fkey";


