create table "payment"."sale" (
    "id" bigint generated by default as identity not null,
    "starts_on" date not null,
    "ends_on" date not null,
    "uses" bigint not null default '0'::bigint
);


alter table "payment"."sale" enable row level security;

CREATE UNIQUE INDEX sale_pkey ON payment.sale USING btree (id);

alter table "payment"."sale" add constraint "sale_pkey" PRIMARY KEY using index "sale_pkey";

create policy "Disable public access"
on "payment"."sale"
as permissive
for all
to public
using (false);



set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.payment_check_sale()
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  active_sale_id bigint;
  sale_exists boolean;
  user_id text;
BEGIN
  -- Get the authenticated user's ID
  user_id := auth.uid();
  
  -- Throw an error if no authenticated user
  IF user_id IS NULL THEN
    RAISE EXCEPTION 'Authentication required';
  END IF;
  
  -- Check if there's an active sale (current date between starts_on and ends_on)
  SELECT id INTO active_sale_id
  FROM payment.sale
  WHERE CURRENT_DATE BETWEEN starts_on AND ends_on
  LIMIT 1;
  
  -- Determine if a sale exists
  sale_exists := active_sale_id IS NOT NULL;
  
  -- If a sale exists, increment the uses count
  IF sale_exists THEN
    UPDATE payment.sale
    SET uses = uses + 1
    WHERE id = active_sale_id;
  END IF;
  
  -- Return whether a sale exists
  RETURN sale_exists;
END;
$function$
;


