create table "library"."support_items" (
    "id" bigint generated by default as identity not null,
    "button_title" text not null,
    "button_symbol" text not null,
    "color1" text not null,
    "color2" text not null,
    "sheet_info" jsonb not null
);


alter table "library"."support_items" enable row level security;

CREATE UNIQUE INDEX support_items_pkey ON library.support_items USING btree (id);

alter table "library"."support_items" add constraint "support_items_pkey" PRIMARY KEY using index "support_items_pkey";

grant delete on table "library"."support_items" to "anon";

grant insert on table "library"."support_items" to "anon";

grant references on table "library"."support_items" to "anon";

grant select on table "library"."support_items" to "anon";

grant trigger on table "library"."support_items" to "anon";

grant truncate on table "library"."support_items" to "anon";

grant update on table "library"."support_items" to "anon";

grant delete on table "library"."support_items" to "authenticated";

grant insert on table "library"."support_items" to "authenticated";

grant references on table "library"."support_items" to "authenticated";

grant select on table "library"."support_items" to "authenticated";

grant trigger on table "library"."support_items" to "authenticated";

grant truncate on table "library"."support_items" to "authenticated";

grant update on table "library"."support_items" to "authenticated";

grant delete on table "library"."support_items" to "service_role";

grant insert on table "library"."support_items" to "service_role";

grant references on table "library"."support_items" to "service_role";

grant select on table "library"."support_items" to "service_role";

grant trigger on table "library"."support_items" to "service_role";

grant truncate on table "library"."support_items" to "service_role";

grant update on table "library"."support_items" to "service_role";

create policy "Select to authed"
on "library"."support_items"
as permissive
for select
to public
using ((( SELECT get_user_id() AS get_user_id) IS NOT NULL));
