create table "library"."push_check_in" (
    "id" bigint generated by default as identity not null,
    "title" text not null,
    "body" text not null,
    "question_id" text,
    "question_response" text
);


alter table "library"."push_check_in" enable row level security;

CREATE UNIQUE INDEX push_check_in_pkey ON library.push_check_in USING btree (id);

alter table "library"."push_check_in" add constraint "push_check_in_pkey" PRIMARY KEY using index "push_check_in_pkey";

grant delete on table "library"."push_check_in" to "authenticated";

grant insert on table "library"."push_check_in" to "authenticated";

grant references on table "library"."push_check_in" to "authenticated";

grant select on table "library"."push_check_in" to "authenticated";

grant trigger on table "library"."push_check_in" to "authenticated";

grant truncate on table "library"."push_check_in" to "authenticated";

grant update on table "library"."push_check_in" to "authenticated";

grant delete on table "library"."push_check_in" to "service_role";

grant insert on table "library"."push_check_in" to "service_role";

grant references on table "library"."push_check_in" to "service_role";

grant select on table "library"."push_check_in" to "service_role";

grant trigger on table "library"."push_check_in" to "service_role";

grant truncate on table "library"."push_check_in" to "service_role";

grant update on table "library"."push_check_in" to "service_role";

grant delete on table "library"."sms_schedule" to "authenticated";

grant insert on table "library"."sms_schedule" to "authenticated";

grant references on table "library"."sms_schedule" to "authenticated";

grant select on table "library"."sms_schedule" to "authenticated";

grant trigger on table "library"."sms_schedule" to "authenticated";

grant truncate on table "library"."sms_schedule" to "authenticated";

grant update on table "library"."sms_schedule" to "authenticated";

create policy "Access to authed"
on "library"."push_check_in"
as permissive
for select
to public
using ((auth.uid() IS NOT NULL));



