create table "library"."sms_day" (
    "id" bigint generated by default as identity not null,
    "day" bigint not null,
    "hour" bigint,
    "min_offset" bigint,
    "program" text not null,
    "matches_program_time" boolean,
    "question_id" text,
    "question_response" text,
    "text" text not null,
    "additional_id" text null,
    "paid" boolean
);

grant usage on schema library to "anon";
grant usage on schema library to "authenticated";
grant usage on schema library to "service_role";

alter table "library"."sms_day" alter column "matches_program_time" set default true;

alter table "library"."sms_day" enable row level security;

CREATE UNIQUE INDEX sms_day_pkey ON library.sms_day USING btree (id);

alter table "library"."sms_day" add constraint "sms_day_pkey" PRIMARY KEY using index "sms_day_pkey";

alter table "library"."sms_day" add constraint "sms_day_program_fkey" FOREIGN KEY (program) REFERENCES programs.programs(id) ON UPDATE CASCADE not valid;

alter table "library"."sms_day" validate constraint "sms_day_program_fkey";

grant delete on table "library"."cache" to "service_role";

grant insert on table "library"."cache" to "service_role";

grant references on table "library"."cache" to "service_role";

grant select on table "library"."cache" to "service_role";

grant trigger on table "library"."cache" to "service_role";

grant truncate on table "library"."cache" to "service_role";

grant update on table "library"."cache" to "service_role";

grant delete on table "library"."one_offs" to "service_role";

grant insert on table "library"."one_offs" to "service_role";

grant references on table "library"."one_offs" to "service_role";

grant select on table "library"."one_offs" to "service_role";

grant trigger on table "library"."one_offs" to "service_role";

grant truncate on table "library"."one_offs" to "service_role";

grant update on table "library"."one_offs" to "service_role";

grant delete on table "library"."sms_check_in" to "service_role";

grant insert on table "library"."sms_check_in" to "service_role";

grant references on table "library"."sms_check_in" to "service_role";

grant select on table "library"."sms_check_in" to "service_role";

grant trigger on table "library"."sms_check_in" to "service_role";

grant truncate on table "library"."sms_check_in" to "service_role";

grant update on table "library"."sms_check_in" to "service_role";

grant delete on table "library"."sms_day" to "anon";

grant insert on table "library"."sms_day" to "anon";

grant references on table "library"."sms_day" to "anon";

grant select on table "library"."sms_day" to "anon";

grant trigger on table "library"."sms_day" to "anon";

grant truncate on table "library"."sms_day" to "anon";

grant update on table "library"."sms_day" to "anon";

grant delete on table "library"."sms_day" to "authenticated";

grant insert on table "library"."sms_day" to "authenticated";

grant references on table "library"."sms_day" to "authenticated";

grant select on table "library"."sms_day" to "authenticated";

grant trigger on table "library"."sms_day" to "authenticated";

grant truncate on table "library"."sms_day" to "authenticated";

grant update on table "library"."sms_day" to "authenticated";

grant delete on table "library"."sms_day" to "service_role";

grant insert on table "library"."sms_day" to "service_role";

grant references on table "library"."sms_day" to "service_role";

grant select on table "library"."sms_day" to "service_role";

grant trigger on table "library"."sms_day" to "service_role";

grant truncate on table "library"."sms_day" to "service_role";

grant update on table "library"."sms_day" to "service_role";

grant delete on table "library"."sms_get_back" to "service_role";

grant insert on table "library"."sms_get_back" to "service_role";

grant references on table "library"."sms_get_back" to "service_role";

grant select on table "library"."sms_get_back" to "service_role";

grant trigger on table "library"."sms_get_back" to "service_role";

grant truncate on table "library"."sms_get_back" to "service_role";

grant update on table "library"."sms_get_back" to "service_role";

grant delete on table "library"."sms_slip_up" to "service_role";

grant insert on table "library"."sms_slip_up" to "service_role";

grant references on table "library"."sms_slip_up" to "service_role";

grant select on table "library"."sms_slip_up" to "service_role";

grant trigger on table "library"."sms_slip_up" to "service_role";

grant truncate on table "library"."sms_slip_up" to "service_role";

grant update on table "library"."sms_slip_up" to "service_role";

create policy "Access to authed"
on "library"."sms_day"
as permissive
for select
to public
using ((auth.uid() IS NOT NULL));



