create table "comms"."silent_notifications" (
    "id" bigint generated by default as identity not null,
    "user_id" text not null,
    "scheduled_for" timestamptz not null,
    "metadata" jsonb not null,
    "processed" boolean not null default 'false'::boolean
);


alter table "comms"."silent_notifications" enable row level security;

alter table "comms"."notifications" add column "silent" boolean default false;

CREATE UNIQUE INDEX silent_notifications_pkey ON comms.silent_notifications USING btree (id);

alter table "comms"."silent_notifications" add constraint "silent_notifications_pkey" PRIMARY KEY using index "silent_notifications_pkey";

alter table "comms"."silent_notifications" add constraint "silent_notifications_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE not valid;

alter table "comms"."silent_notifications" validate constraint "silent_notifications_user_id_fkey";


set check_function_bodies = off;

CREATE OR REPLACE FUNCTION comms.add_silent_notification()
 RETURNS VOID
 LANGUAGE plpgsql
AS $function$BEGIN
  -- Insert due silent notifications into the notifications table
  WITH due_silent_notifications AS (
    SELECT 
      id,
      user_id,
      metadata,
      scheduled_for
    FROM comms.silent_notifications
    WHERE 
      processed = false 
      AND scheduled_for <= NOW()
  ),
  inserted_notifications AS (
    INSERT INTO comms.notifications (
      user_id,
      title,
      body,
      metadata,
      silent
    )
    SELECT
      user_id,
      '',
      '',
      metadata,
      true
    FROM due_silent_notifications
    RETURNING id
  )
  -- Mark processed silent notifications
  UPDATE comms.silent_notifications
  SET processed = true
  WHERE id IN (SELECT id FROM due_silent_notifications);
END;$function$
;

