create table "community"."community_prompts" (
    "id" bigint generated by default as identity not null,
    "start_date" date not null,
    "end_date" date not null,
    "prompt" text not null,
    "tag" uuid,
    "title" text not null default ''::text
);


alter table "community"."community_prompts" enable row level security;

CREATE UNIQUE INDEX community_prompts_pkey ON community.community_prompts USING btree (id);

alter table "community"."community_prompts" add constraint "community_prompts_pkey" PRIMARY KEY using index "community_prompts_pkey";

alter table "community"."community_prompts" add constraint "community_prompts_tag_fkey" FOREIGN KEY (tag) REFERENCES community.tags(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "community"."community_prompts" validate constraint "community_prompts_tag_fkey";

grant delete on table "community"."community_prompts" to "anon";

grant insert on table "community"."community_prompts" to "anon";

grant references on table "community"."community_prompts" to "anon";

grant select on table "community"."community_prompts" to "anon";

grant trigger on table "community"."community_prompts" to "anon";

grant truncate on table "community"."community_prompts" to "anon";

grant update on table "community"."community_prompts" to "anon";

grant delete on table "community"."community_prompts" to "authenticated";

grant insert on table "community"."community_prompts" to "authenticated";

grant references on table "community"."community_prompts" to "authenticated";

grant select on table "community"."community_prompts" to "authenticated";

grant trigger on table "community"."community_prompts" to "authenticated";

grant truncate on table "community"."community_prompts" to "authenticated";

grant update on table "community"."community_prompts" to "authenticated";

grant delete on table "community"."community_prompts" to "service_role";

grant insert on table "community"."community_prompts" to "service_role";

grant references on table "community"."community_prompts" to "service_role";

grant select on table "community"."community_prompts" to "service_role";

grant trigger on table "community"."community_prompts" to "service_role";

grant truncate on table "community"."community_prompts" to "service_role";

grant update on table "community"."community_prompts" to "service_role";

grant delete on table "community"."settings" to "anon";

grant insert on table "community"."settings" to "anon";

grant references on table "community"."settings" to "anon";

grant trigger on table "community"."settings" to "anon";

grant truncate on table "community"."settings" to "anon";

grant update on table "community"."settings" to "anon";

grant delete on table "community"."settings" to "authenticated";

grant insert on table "community"."settings" to "authenticated";

grant references on table "community"."settings" to "authenticated";

grant trigger on table "community"."settings" to "authenticated";

grant truncate on table "community"."settings" to "authenticated";

grant update on table "community"."settings" to "authenticated";

create policy "Access to authed"
on "community"."community_prompts"
as permissive
for select
to public
using (( SELECT (auth.uid() IS NOT NULL)));



