create table "library"."health_categories" (
    "name" text not null,
    "sf_symbol" text not null,
    "color1" text not null,
    "color2" text not null
);


alter table "library"."health_categories" enable row level security;

create table "library"."health_steps" (
    "id" bigint generated by default as identity not null,
    "category" text not null,
    "days_without_weed" smallint not null,
    "check_in_offset" smallint not null,
    "percentage" smallint not null,
    "text" text not null,
    "citation" text not null
);


alter table "library"."health_steps" enable row level security;

CREATE UNIQUE INDEX health_categories_pkey ON library.health_categories USING btree (name);

CREATE UNIQUE INDEX health_steps_pkey ON library.health_steps USING btree (id);

alter table "library"."health_categories" add constraint "health_categories_pkey" PRIMARY KEY using index "health_categories_pkey";

alter table "library"."health_steps" add constraint "health_steps_pkey" PRIMARY KEY using index "health_steps_pkey";

alter table "library"."health_steps" add constraint "health_steps_category_fkey" FOREIGN KEY (category) REFERENCES library.health_categories(name) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "library"."health_steps" validate constraint "health_steps_category_fkey";

grant delete on table "library"."health_categories" to "anon";

grant insert on table "library"."health_categories" to "anon";

grant references on table "library"."health_categories" to "anon";

grant select on table "library"."health_categories" to "anon";

grant trigger on table "library"."health_categories" to "anon";

grant truncate on table "library"."health_categories" to "anon";

grant update on table "library"."health_categories" to "anon";

grant delete on table "library"."health_categories" to "authenticated";

grant insert on table "library"."health_categories" to "authenticated";

grant references on table "library"."health_categories" to "authenticated";

grant select on table "library"."health_categories" to "authenticated";

grant trigger on table "library"."health_categories" to "authenticated";

grant truncate on table "library"."health_categories" to "authenticated";

grant update on table "library"."health_categories" to "authenticated";

grant delete on table "library"."health_categories" to "service_role";

grant insert on table "library"."health_categories" to "service_role";

grant references on table "library"."health_categories" to "service_role";

grant select on table "library"."health_categories" to "service_role";

grant trigger on table "library"."health_categories" to "service_role";

grant truncate on table "library"."health_categories" to "service_role";

grant update on table "library"."health_categories" to "service_role";

grant delete on table "library"."health_steps" to "anon";

grant insert on table "library"."health_steps" to "anon";

grant references on table "library"."health_steps" to "anon";

grant select on table "library"."health_steps" to "anon";

grant trigger on table "library"."health_steps" to "anon";

grant truncate on table "library"."health_steps" to "anon";

grant update on table "library"."health_steps" to "anon";

grant delete on table "library"."health_steps" to "authenticated";

grant insert on table "library"."health_steps" to "authenticated";

grant references on table "library"."health_steps" to "authenticated";

grant select on table "library"."health_steps" to "authenticated";

grant trigger on table "library"."health_steps" to "authenticated";

grant truncate on table "library"."health_steps" to "authenticated";

grant update on table "library"."health_steps" to "authenticated";

grant delete on table "library"."health_steps" to "service_role";

grant insert on table "library"."health_steps" to "service_role";

grant references on table "library"."health_steps" to "service_role";

grant select on table "library"."health_steps" to "service_role";

grant trigger on table "library"."health_steps" to "service_role";

grant truncate on table "library"."health_steps" to "service_role";

grant update on table "library"."health_steps" to "service_role";

create policy "Access to authed"
on "library"."health_categories"
as permissive
for select
to public
using (( SELECT (auth.uid() IS NOT NULL)));


create policy "Access to authed"
on "library"."health_steps"
as permissive
for select
to public
using (( SELECT (auth.uid() IS NOT NULL)));



