create schema if not exists "community";

create table "community"."post_tags" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "post_id" uuid,
    "tag_id" uuid,
    "updated_at" timestamp with time zone
);


alter table "community"."post_tags" enable row level security;

create table "community"."posts" (
    "id" uuid not null default gen_random_uuid(),
    "user_id" text,
    "title" character varying,
    "content_type" text,
    "body" text,
    "video_url" text,
    "view_count" bigint default '0'::bigint,
    "is_pinned" boolean,
    "is_hidden" boolean,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone
);


alter table "community"."posts" enable row level security;

create table "community"."tags" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "name" character varying,
    "updated_at" timestamp with time zone
);


alter table "community"."tags" enable row level security;

CREATE UNIQUE INDEX post_tags_pkey ON community.post_tags USING btree (id);

CREATE UNIQUE INDEX posts_pkey ON community.posts USING btree (id);

CREATE UNIQUE INDEX tags_pkey ON community.tags USING btree (id);

alter table "community"."post_tags" add constraint "post_tags_pkey" PRIMARY KEY using index "post_tags_pkey";

alter table "community"."posts" add constraint "posts_pkey" PRIMARY KEY using index "posts_pkey";

alter table "community"."tags" add constraint "tags_pkey" PRIMARY KEY using index "tags_pkey";

alter table "community"."post_tags" add constraint "post_tags_post_id_fkey" FOREIGN KEY (post_id) REFERENCES community.posts(id) not valid;

alter table "community"."post_tags" validate constraint "post_tags_post_id_fkey";

alter table "community"."post_tags" add constraint "post_tags_tag_id_fkey" FOREIGN KEY (tag_id) REFERENCES community.tags(id) not valid;

alter table "community"."post_tags" validate constraint "post_tags_tag_id_fkey";

alter table "community"."posts" add constraint "posts_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL not valid;

alter table "community"."posts" validate constraint "posts_user_id_fkey";


