create table "library"."sms_inactive" (
    "id" bigint generated by default as identity not null,
    "day" date,
    "message" text not null
);


alter table "library"."sms_inactive" enable row level security;

CREATE UNIQUE INDEX sms_inactive_pkey ON library.sms_inactive USING btree (id);

alter table "library"."sms_inactive" add constraint "sms_inactive_pkey" PRIMARY KEY using index "sms_inactive_pkey";

grant delete on table "library"."sms_inactive" to "service_role";

grant insert on table "library"."sms_inactive" to "service_role";

grant references on table "library"."sms_inactive" to "service_role";

grant select on table "library"."sms_inactive" to "service_role";

grant trigger on table "library"."sms_inactive" to "service_role";

grant truncate on table "library"."sms_inactive" to "service_role";

grant update on table "library"."sms_inactive" to "service_role";


