create table "payment"."referral_codes" (
    "id" bigint generated by default as identity not null,
    "code" text not null,
    "uses" integer not null default 0,
    "free" boolean not null default false,
    "created_at" date not null
);


alter table "payment"."referral_codes" enable row level security;

CREATE UNIQUE INDEX referral_codes_pkey ON payment.referral_codes USING btree (id);

alter table "payment"."referral_codes" add constraint "referral_codes_pkey" PRIMARY KEY using index "referral_codes_pkey";

create policy "Disable all access"
on "payment"."referral_codes"
as permissive
for all
to public
using (false);



set check_function_bodies = off;

CREATE OR REPLACE FUNCTION payment.check_referral_code(input_code text)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$DECLARE
    is_valid boolean;
BEGIN
    -- Check if code exists (case insensitive) and increment uses if it does
    UPDATE payment.referral_codes
    SET uses = uses + 1
    WHERE LOWER(code) = LOWER(input_code)
    RETURNING free INTO is_valid;
    
    -- Return the result (null becomes false)
    RETURN COALESCE(is_valid, false);
END;$function$
;


