create schema if not exists "platform";

create sequence "platform"."conversation_tags_id_seq";

create sequence "platform"."tags_id_seq";

create table "platform"."admins" (
    "id" bigint generated by default as identity not null,
    "auth_id" uuid not null
);


alter table "platform"."admins" enable row level security;

create table "platform"."conversation_tags" (
    "id" bigint not null default nextval('platform.conversation_tags_id_seq'::regclass),
    "tag_id" bigint not null,
    "phone_number" text not null,
    "admin_id" bigint not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "platform"."conversation_tags" enable row level security;

create table "platform"."tags" (
    "id" bigint not null default nextval('platform.tags_id_seq'::regclass),
    "admin_id" bigint not null,
    "name" text not null,
    "color" text not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "platform"."tags" enable row level security;

alter sequence "platform"."conversation_tags_id_seq" owned by "platform"."conversation_tags"."id";

alter sequence "platform"."tags_id_seq" owned by "platform"."tags"."id";

CREATE UNIQUE INDEX admins_pkey ON platform.admins USING btree (id);

CREATE UNIQUE INDEX conversation_tags_pkey ON platform.conversation_tags USING btree (id);

CREATE UNIQUE INDEX conversation_tags_tag_id_phone_number_admin_id_key ON platform.conversation_tags USING btree (tag_id, phone_number, admin_id);

CREATE INDEX idx_conversation_tags_admin_id ON platform.conversation_tags USING btree (admin_id);

CREATE INDEX idx_conversation_tags_phone_number ON platform.conversation_tags USING btree (phone_number);

CREATE INDEX idx_conversation_tags_tag_id ON platform.conversation_tags USING btree (tag_id);

CREATE INDEX idx_tags_admin_id ON platform.tags USING btree (admin_id);

CREATE UNIQUE INDEX tags_admin_id_name_key ON platform.tags USING btree (admin_id, name);

CREATE UNIQUE INDEX tags_pkey ON platform.tags USING btree (id);

grant usage on schema "platform" to "anon";
grant usage on schema "platform" to "authenticated";
grant usage on schema "platform" to "service_role";

alter table "platform"."admins" add constraint "admins_pkey" PRIMARY KEY using index "admins_pkey";

alter table "platform"."conversation_tags" add constraint "conversation_tags_pkey" PRIMARY KEY using index "conversation_tags_pkey";

alter table "platform"."tags" add constraint "tags_pkey" PRIMARY KEY using index "tags_pkey";

alter table "platform"."admins" add constraint "admins_auth_id_fkey" FOREIGN KEY (auth_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "platform"."admins" validate constraint "admins_auth_id_fkey";

alter table "platform"."conversation_tags" add constraint "conversation_tags_admin_id_fkey" FOREIGN KEY (admin_id) REFERENCES platform.admins(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "platform"."conversation_tags" validate constraint "conversation_tags_admin_id_fkey";

alter table "platform"."conversation_tags" add constraint "conversation_tags_tag_id_fkey" FOREIGN KEY (tag_id) REFERENCES platform.tags(id) ON DELETE CASCADE not valid;

alter table "platform"."conversation_tags" validate constraint "conversation_tags_tag_id_fkey";

alter table "platform"."conversation_tags" add constraint "conversation_tags_tag_id_phone_number_admin_id_key" UNIQUE using index "conversation_tags_tag_id_phone_number_admin_id_key";

alter table "platform"."tags" add constraint "tags_admin_id_fkey" FOREIGN KEY (admin_id) REFERENCES platform.admins(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "platform"."tags" validate constraint "tags_admin_id_fkey";

alter table "platform"."tags" add constraint "tags_admin_id_name_key" UNIQUE using index "tags_admin_id_name_key";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION platform.get_admin_id()
 RETURNS integer
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$BEGIN
  RETURN (SELECT id FROM platform.admins WHERE auth_id = auth.uid());
END;$function$
;

grant delete on table "platform"."admins" to "anon";

grant insert on table "platform"."admins" to "anon";

grant references on table "platform"."admins" to "anon";

grant select on table "platform"."admins" to "anon";

grant trigger on table "platform"."admins" to "anon";

grant truncate on table "platform"."admins" to "anon";

grant update on table "platform"."admins" to "anon";

grant delete on table "platform"."admins" to "authenticated";

grant insert on table "platform"."admins" to "authenticated";

grant references on table "platform"."admins" to "authenticated";

grant select on table "platform"."admins" to "authenticated";

grant trigger on table "platform"."admins" to "authenticated";

grant truncate on table "platform"."admins" to "authenticated";

grant update on table "platform"."admins" to "authenticated";

grant delete on table "platform"."admins" to "service_role";

grant insert on table "platform"."admins" to "service_role";

grant references on table "platform"."admins" to "service_role";

grant select on table "platform"."admins" to "service_role";

grant trigger on table "platform"."admins" to "service_role";

grant truncate on table "platform"."admins" to "service_role";

grant update on table "platform"."admins" to "service_role";

grant delete on table "platform"."conversation_tags" to "anon";

grant insert on table "platform"."conversation_tags" to "anon";

grant references on table "platform"."conversation_tags" to "anon";

grant select on table "platform"."conversation_tags" to "anon";

grant trigger on table "platform"."conversation_tags" to "anon";

grant truncate on table "platform"."conversation_tags" to "anon";

grant update on table "platform"."conversation_tags" to "anon";

grant delete on table "platform"."conversation_tags" to "authenticated";

grant insert on table "platform"."conversation_tags" to "authenticated";

grant references on table "platform"."conversation_tags" to "authenticated";

grant select on table "platform"."conversation_tags" to "authenticated";

grant trigger on table "platform"."conversation_tags" to "authenticated";

grant truncate on table "platform"."conversation_tags" to "authenticated";

grant update on table "platform"."conversation_tags" to "authenticated";

grant delete on table "platform"."conversation_tags" to "service_role";

grant insert on table "platform"."conversation_tags" to "service_role";

grant references on table "platform"."conversation_tags" to "service_role";

grant select on table "platform"."conversation_tags" to "service_role";

grant trigger on table "platform"."conversation_tags" to "service_role";

grant truncate on table "platform"."conversation_tags" to "service_role";

grant update on table "platform"."conversation_tags" to "service_role";

grant delete on table "platform"."tags" to "anon";

grant insert on table "platform"."tags" to "anon";

grant references on table "platform"."tags" to "anon";

grant select on table "platform"."tags" to "anon";

grant trigger on table "platform"."tags" to "anon";

grant truncate on table "platform"."tags" to "anon";

grant update on table "platform"."tags" to "anon";

grant delete on table "platform"."tags" to "authenticated";

grant insert on table "platform"."tags" to "authenticated";

grant references on table "platform"."tags" to "authenticated";

grant select on table "platform"."tags" to "authenticated";

grant trigger on table "platform"."tags" to "authenticated";

grant truncate on table "platform"."tags" to "authenticated";

grant update on table "platform"."tags" to "authenticated";

grant delete on table "platform"."tags" to "service_role";

grant insert on table "platform"."tags" to "service_role";

grant references on table "platform"."tags" to "service_role";

grant select on table "platform"."tags" to "service_role";

grant trigger on table "platform"."tags" to "service_role";

grant truncate on table "platform"."tags" to "service_role";

grant update on table "platform"."tags" to "service_role";

create policy "Disable all access"
on "platform"."admins"
as permissive
for all
to public
using (false);


create policy "Admin only"
on "platform"."conversation_tags"
as permissive
for all
to public
using (( SELECT admin_check() AS admin_check))
with check ((admin_id = ( SELECT platform.get_admin_id() AS get_admin_id)));


create policy "Admin access"
on "platform"."tags"
as permissive
for all
to public
using (( SELECT admin_check() AS admin_check))
with check ((admin_id = ( SELECT platform.get_admin_id() AS get_admin_id)));



set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.admin_check()
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$declare
  uid uuid;
  is_admin boolean;
begin
  -- Get the current user ID from the JWT using auth.uid()
  select auth.uid() into uid;
  
  if uid is null then
    return false;
  end if;

  select exists(select 1 from platform.admins where auth_id = uid) into is_admin;
  return is_admin;
end;$function$
;


