create table "library"."onboarding_reviews" (
    "id" bigint generated by default as identity not null,
    "title" text not null,
    "body" text not null,
    "priority" bigint not null default '1'::bigint,
    "created_at" timestamp with time zone not null default now(),
    "author" text not null
);


alter table "library"."onboarding_reviews" enable row level security;

CREATE UNIQUE INDEX onboarding_reviews_pkey ON library.onboarding_reviews USING btree (id);

alter table "library"."onboarding_reviews" add constraint "onboarding_reviews_pkey" PRIMARY KEY using index "onboarding_reviews_pkey";

grant delete on table "library"."onboarding_reviews" to "anon";

grant insert on table "library"."onboarding_reviews" to "anon";

grant references on table "library"."onboarding_reviews" to "anon";

grant select on table "library"."onboarding_reviews" to "anon";

grant trigger on table "library"."onboarding_reviews" to "anon";

grant truncate on table "library"."onboarding_reviews" to "anon";

grant update on table "library"."onboarding_reviews" to "anon";

grant delete on table "library"."onboarding_reviews" to "authenticated";

grant insert on table "library"."onboarding_reviews" to "authenticated";

grant references on table "library"."onboarding_reviews" to "authenticated";

grant select on table "library"."onboarding_reviews" to "authenticated";

grant trigger on table "library"."onboarding_reviews" to "authenticated";

grant truncate on table "library"."onboarding_reviews" to "authenticated";

grant update on table "library"."onboarding_reviews" to "authenticated";

grant delete on table "library"."onboarding_reviews" to "service_role";

grant insert on table "library"."onboarding_reviews" to "service_role";

grant references on table "library"."onboarding_reviews" to "service_role";

grant select on table "library"."onboarding_reviews" to "service_role";

grant trigger on table "library"."onboarding_reviews" to "service_role";

grant truncate on table "library"."onboarding_reviews" to "service_role";

grant update on table "library"."onboarding_reviews" to "service_role";

create policy "All can select"
on "library"."onboarding_reviews"
as permissive
for select
to public
using (true);



