create table "programs"."program_pop_ups" (
    "id" bigint generated by default as identity not null,
    "program" text not null,
    "day" integer not null,
    "sheet_data" jsonb not null,
    "active" boolean not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "programs"."program_pop_ups" enable row level security;

CREATE UNIQUE INDEX program_pop_ups_pkey ON programs.program_pop_ups USING btree (id);

alter table "programs"."program_pop_ups" add constraint "program_pop_ups_pkey" PRIMARY KEY using index "program_pop_ups_pkey";

alter table "programs"."program_pop_ups" add constraint "program_pop_ups_program_fkey" FOREIGN KEY (program) REFERENCES programs.programs(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "programs"."program_pop_ups" validate constraint "program_pop_ups_program_fkey";


