create table "symptoms"."symptom_resources" (
    "id" bigint generated by default as identity not null,
    "symptom" text not null,
    "title" text not null,
    "subtitle" text not null,
    "image_url" text not null,
    "type" text not null,
    "extra_info" jsonb,
    "enabled" boolean not null default true,
    "created_at" timestamp with time zone not null default now()
);

alter table "symptoms"."symptom_resources" enable row level security;

CREATE UNIQUE INDEX symptom_resources_pkey ON symptoms.symptom_resources USING btree (id);

CREATE INDEX symptom_resources_symptom ON symptoms.symptom_resources USING btree (symptom);

CREATE INDEX symptom_resources_enabled ON symptoms.symptom_resources USING btree (enabled);

alter table "symptoms"."symptom_resources" add constraint "symptom_resources_pkey" PRIMARY KEY using index "symptom_resources_pkey";

create policy "Enable public access"
on "symptoms"."symptom_resources"
as permissive
for select
to public
using (true);

