create table "payment"."hard_paywalls" (
    "id" bigint generated by default as identity not null,
    "paywall_id" text not null,
    "hard" boolean not null
);


alter table "payment"."hard_paywalls" enable row level security;

CREATE UNIQUE INDEX hard_paywalls_pkey ON payment.hard_paywalls USING btree (id);

alter table "payment"."hard_paywalls" add constraint "hard_paywalls_pkey" PRIMARY KEY using index "hard_paywalls_pkey";

grant delete on table "payment"."hard_paywalls" to "anon";

grant insert on table "payment"."hard_paywalls" to "anon";

grant references on table "payment"."hard_paywalls" to "anon";

grant select on table "payment"."hard_paywalls" to "anon";

grant trigger on table "payment"."hard_paywalls" to "anon";

grant truncate on table "payment"."hard_paywalls" to "anon";

grant update on table "payment"."hard_paywalls" to "anon";

grant delete on table "payment"."hard_paywalls" to "authenticated";

grant insert on table "payment"."hard_paywalls" to "authenticated";

grant references on table "payment"."hard_paywalls" to "authenticated";

grant select on table "payment"."hard_paywalls" to "authenticated";

grant trigger on table "payment"."hard_paywalls" to "authenticated";

grant truncate on table "payment"."hard_paywalls" to "authenticated";

grant update on table "payment"."hard_paywalls" to "authenticated";

grant delete on table "payment"."hard_paywalls" to "service_role";

grant insert on table "payment"."hard_paywalls" to "service_role";

grant references on table "payment"."hard_paywalls" to "service_role";

grant select on table "payment"."hard_paywalls" to "service_role";

grant trigger on table "payment"."hard_paywalls" to "service_role";

grant truncate on table "payment"."hard_paywalls" to "service_role";

grant update on table "payment"."hard_paywalls" to "service_role";


