create table "payment"."one_time_offers" (
    "id" bigint generated by default as identity not null,
    "paywall_id" text not null,
    "oto_placement" text not null,
    "enabled" boolean not null default true
);


alter table "payment"."one_time_offers" enable row level security;

CREATE UNIQUE INDEX one_time_offers_pkey ON payment.one_time_offers USING btree (id);

alter table "payment"."one_time_offers" add constraint "one_time_offers_pkey" PRIMARY KEY using index "one_time_offers_pkey";

grant delete on table "payment"."domain_allowlist" to "anon";

grant insert on table "payment"."domain_allowlist" to "anon";

grant references on table "payment"."domain_allowlist" to "anon";

grant select on table "payment"."domain_allowlist" to "anon";

grant trigger on table "payment"."domain_allowlist" to "anon";

grant truncate on table "payment"."domain_allowlist" to "anon";

grant update on table "payment"."domain_allowlist" to "anon";

grant delete on table "payment"."domain_allowlist" to "authenticated";

grant insert on table "payment"."domain_allowlist" to "authenticated";

grant references on table "payment"."domain_allowlist" to "authenticated";

grant select on table "payment"."domain_allowlist" to "authenticated";

grant trigger on table "payment"."domain_allowlist" to "authenticated";

grant truncate on table "payment"."domain_allowlist" to "authenticated";

grant update on table "payment"."domain_allowlist" to "authenticated";

grant delete on table "payment"."domain_allowlist" to "service_role";

grant insert on table "payment"."domain_allowlist" to "service_role";

grant references on table "payment"."domain_allowlist" to "service_role";

grant select on table "payment"."domain_allowlist" to "service_role";

grant trigger on table "payment"."domain_allowlist" to "service_role";

grant truncate on table "payment"."domain_allowlist" to "service_role";

grant update on table "payment"."domain_allowlist" to "service_role";

grant delete on table "payment"."one_time_offers" to "anon";

grant insert on table "payment"."one_time_offers" to "anon";

grant references on table "payment"."one_time_offers" to "anon";

grant select on table "payment"."one_time_offers" to "anon";

grant trigger on table "payment"."one_time_offers" to "anon";

grant truncate on table "payment"."one_time_offers" to "anon";

grant update on table "payment"."one_time_offers" to "anon";

grant delete on table "payment"."one_time_offers" to "authenticated";

grant insert on table "payment"."one_time_offers" to "authenticated";

grant references on table "payment"."one_time_offers" to "authenticated";

grant select on table "payment"."one_time_offers" to "authenticated";

grant trigger on table "payment"."one_time_offers" to "authenticated";

grant truncate on table "payment"."one_time_offers" to "authenticated";

grant update on table "payment"."one_time_offers" to "authenticated";

grant delete on table "payment"."one_time_offers" to "service_role";

grant insert on table "payment"."one_time_offers" to "service_role";

grant references on table "payment"."one_time_offers" to "service_role";

grant select on table "payment"."one_time_offers" to "service_role";

grant trigger on table "payment"."one_time_offers" to "service_role";

grant truncate on table "payment"."one_time_offers" to "service_role";

grant update on table "payment"."one_time_offers" to "service_role";

grant delete on table "payment"."promo_codes" to "anon";

grant insert on table "payment"."promo_codes" to "anon";

grant references on table "payment"."promo_codes" to "anon";

grant select on table "payment"."promo_codes" to "anon";

grant trigger on table "payment"."promo_codes" to "anon";

grant truncate on table "payment"."promo_codes" to "anon";

grant update on table "payment"."promo_codes" to "anon";

grant delete on table "payment"."promo_codes" to "authenticated";

grant insert on table "payment"."promo_codes" to "authenticated";

grant references on table "payment"."promo_codes" to "authenticated";

grant select on table "payment"."promo_codes" to "authenticated";

grant trigger on table "payment"."promo_codes" to "authenticated";

grant truncate on table "payment"."promo_codes" to "authenticated";

grant update on table "payment"."promo_codes" to "authenticated";

grant delete on table "payment"."promo_codes" to "service_role";

grant insert on table "payment"."promo_codes" to "service_role";

grant references on table "payment"."promo_codes" to "service_role";

grant select on table "payment"."promo_codes" to "service_role";

grant trigger on table "payment"."promo_codes" to "service_role";

grant truncate on table "payment"."promo_codes" to "service_role";

grant update on table "payment"."promo_codes" to "service_role";

grant delete on table "payment"."sale" to "anon";

grant insert on table "payment"."sale" to "anon";

grant references on table "payment"."sale" to "anon";

grant select on table "payment"."sale" to "anon";

grant trigger on table "payment"."sale" to "anon";

grant truncate on table "payment"."sale" to "anon";

grant update on table "payment"."sale" to "anon";

grant delete on table "payment"."sale" to "authenticated";

grant insert on table "payment"."sale" to "authenticated";

grant references on table "payment"."sale" to "authenticated";

grant select on table "payment"."sale" to "authenticated";

grant trigger on table "payment"."sale" to "authenticated";

grant truncate on table "payment"."sale" to "authenticated";

grant update on table "payment"."sale" to "authenticated";

grant delete on table "payment"."sale" to "service_role";

grant insert on table "payment"."sale" to "service_role";

grant references on table "payment"."sale" to "service_role";

grant select on table "payment"."sale" to "service_role";

grant trigger on table "payment"."sale" to "service_role";

grant truncate on table "payment"."sale" to "service_role";

grant update on table "payment"."sale" to "service_role";

grant delete on table "payment"."sale_users" to "anon";

grant insert on table "payment"."sale_users" to "anon";

grant references on table "payment"."sale_users" to "anon";

grant select on table "payment"."sale_users" to "anon";

grant trigger on table "payment"."sale_users" to "anon";

grant truncate on table "payment"."sale_users" to "anon";

grant update on table "payment"."sale_users" to "anon";

grant delete on table "payment"."sale_users" to "authenticated";

grant insert on table "payment"."sale_users" to "authenticated";

grant references on table "payment"."sale_users" to "authenticated";

grant select on table "payment"."sale_users" to "authenticated";

grant trigger on table "payment"."sale_users" to "authenticated";

grant truncate on table "payment"."sale_users" to "authenticated";

grant update on table "payment"."sale_users" to "authenticated";

grant delete on table "payment"."sale_users" to "service_role";

grant insert on table "payment"."sale_users" to "service_role";

grant references on table "payment"."sale_users" to "service_role";

grant select on table "payment"."sale_users" to "service_role";

grant trigger on table "payment"."sale_users" to "service_role";

grant truncate on table "payment"."sale_users" to "service_role";

grant update on table "payment"."sale_users" to "service_role";

create policy "Select to all"
on "payment"."one_time_offers"
as permissive
for select
to public
using (true);



