create table "comms"."sms_blocked" (
    "id" bigint generated by default as identity not null,
    "phone_number" text not null
);


alter table "comms"."sms_blocked" enable row level security;

CREATE UNIQUE INDEX sms_blocked_pkey ON comms.sms_blocked USING btree (id);

alter table "comms"."sms_blocked" add constraint "sms_blocked_pkey" PRIMARY KEY using index "sms_blocked_pkey";

grant delete on table "comms"."dr_fred" to "anon";

grant insert on table "comms"."dr_fred" to "anon";

grant references on table "comms"."dr_fred" to "anon";

grant select on table "comms"."dr_fred" to "anon";

grant trigger on table "comms"."dr_fred" to "anon";

grant truncate on table "comms"."dr_fred" to "anon";

grant update on table "comms"."dr_fred" to "anon";

grant delete on table "comms"."silent_notifications" to "anon";

grant insert on table "comms"."silent_notifications" to "anon";

grant references on table "comms"."silent_notifications" to "anon";

grant select on table "comms"."silent_notifications" to "anon";

grant trigger on table "comms"."silent_notifications" to "anon";

grant truncate on table "comms"."silent_notifications" to "anon";

grant update on table "comms"."silent_notifications" to "anon";

grant delete on table "comms"."silent_notifications" to "authenticated";

grant insert on table "comms"."silent_notifications" to "authenticated";

grant references on table "comms"."silent_notifications" to "authenticated";

grant select on table "comms"."silent_notifications" to "authenticated";

grant trigger on table "comms"."silent_notifications" to "authenticated";

grant truncate on table "comms"."silent_notifications" to "authenticated";

grant update on table "comms"."silent_notifications" to "authenticated";

grant delete on table "comms"."silent_notifications" to "service_role";

grant insert on table "comms"."silent_notifications" to "service_role";

grant references on table "comms"."silent_notifications" to "service_role";

grant select on table "comms"."silent_notifications" to "service_role";

grant trigger on table "comms"."silent_notifications" to "service_role";

grant truncate on table "comms"."silent_notifications" to "service_role";

grant update on table "comms"."silent_notifications" to "service_role";

grant delete on table "comms"."sms_blocked" to "anon";

grant insert on table "comms"."sms_blocked" to "anon";

grant references on table "comms"."sms_blocked" to "anon";

grant select on table "comms"."sms_blocked" to "anon";

grant trigger on table "comms"."sms_blocked" to "anon";

grant truncate on table "comms"."sms_blocked" to "anon";

grant update on table "comms"."sms_blocked" to "anon";

grant delete on table "comms"."sms_blocked" to "authenticated";

grant insert on table "comms"."sms_blocked" to "authenticated";

grant references on table "comms"."sms_blocked" to "authenticated";

grant select on table "comms"."sms_blocked" to "authenticated";

grant trigger on table "comms"."sms_blocked" to "authenticated";

grant truncate on table "comms"."sms_blocked" to "authenticated";

grant update on table "comms"."sms_blocked" to "authenticated";

grant delete on table "comms"."sms_blocked" to "service_role";

grant insert on table "comms"."sms_blocked" to "service_role";

grant references on table "comms"."sms_blocked" to "service_role";

grant select on table "comms"."sms_blocked" to "service_role";

grant trigger on table "comms"."sms_blocked" to "service_role";

grant truncate on table "comms"."sms_blocked" to "service_role";

grant update on table "comms"."sms_blocked" to "service_role";

grant delete on table "comms"."sms_messages" to "anon";

grant insert on table "comms"."sms_messages" to "anon";

grant references on table "comms"."sms_messages" to "anon";

grant select on table "comms"."sms_messages" to "anon";

grant trigger on table "comms"."sms_messages" to "anon";

grant truncate on table "comms"."sms_messages" to "anon";

grant update on table "comms"."sms_messages" to "anon";

grant delete on table "comms"."sms_statuses" to "anon";

grant insert on table "comms"."sms_statuses" to "anon";

grant references on table "comms"."sms_statuses" to "anon";

grant select on table "comms"."sms_statuses" to "anon";

grant trigger on table "comms"."sms_statuses" to "anon";

grant truncate on table "comms"."sms_statuses" to "anon";

grant update on table "comms"."sms_statuses" to "anon";

create policy "Disable all access"
on "comms"."sms_blocked"
as permissive
for all
to public
using (false);



