create table "payment"."one_time_offers" (
    "id" bigint generated by default as identity not null,
    "paywall_id" text not null,
    "oto_placement" text not null
);


alter table "payment"."one_time_offers" enable row level security;

CREATE UNIQUE INDEX one_time_offers_pkey ON payment.one_time_offers USING btree (id);

alter table "payment"."one_time_offers" add constraint "one_time_offers_pkey" PRIMARY KEY using index "one_time_offers_pkey";

create policy "Select to all"
on "payment"."one_time_offers"
as permissive
for select
to public
using (true);



