-- Peer Support Migration: SMS to In-App Messaging
-- Part 1: Tables, Functions, Triggers, and Indexes

--------------------------------------------------------------------------------
-- 1. NEW TABLES
--------------------------------------------------------------------------------

-- comms.peer_messages - Core storage for in-app messages
CREATE TABLE comms.peer_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    text TEXT NOT NULL,
    outbound BOOLEAN NOT NULL DEFAULT false,  -- true = from admin/system
    type TEXT DEFAULT 'manual',  -- 'manual', 'milestone', 'system', 'migrated'
    template_id BIGINT,  -- references library.peer_day.id if from template
    read_at TIMESTAMPTZ,
    notification_sent TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted BOOLEAN NOT NULL DEFAULT false
);

-- Index for efficient user message queries
CREATE INDEX idx_peer_messages_user_id ON comms.peer_messages(user_id, created_at DESC);

-- Index for push notification processing
CREATE INDEX idx_peer_messages_notification ON comms.peer_messages(outbound, notification_sent)
    WHERE outbound = true AND notification_sent IS NULL;

-- Enable realtime
ALTER PUBLICATION supabase_realtime ADD TABLE comms.peer_messages;

-- comms.peer_conversations - Denormalized view for admin panel
CREATE TABLE comms.peer_conversations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL UNIQUE REFERENCES public.users(id) ON DELETE CASCADE,
    name TEXT,
    last_message_id BIGINT,
    last_message_text TEXT,
    last_message_timestamp TIMESTAMPTZ,
    last_message_outbound BOOLEAN,
    unread_count INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- Index for admin panel sorting
CREATE INDEX idx_peer_conversations_updated ON comms.peer_conversations(updated_at DESC);

-- library.peer_day - In-app message templates (separate from sms_day)
CREATE TABLE library.peer_day (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    day INT NOT NULL,  -- day in program (0, 10, 30, etc.)
    program TEXT NOT NULL DEFAULT 'clear30',  -- 'clear30', 'life'
    text TEXT NOT NULL,  -- message template with _CLIENTNAME_ etc.
    question_id TEXT,  -- assessment question to condition on
    question_response TEXT,  -- expected response value
    variant_id TEXT,  -- e.g., 'x10-day-perfect', 'breakdown-good'
    variant_conditions JSONB,  -- e.g., {"check_in_count": {"min": 7, "max": 9}}
    hour_utc INT DEFAULT 16,  -- hour to send (UTC), default 4 PM
    active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- Index for efficient lookup
CREATE INDEX idx_peer_day_lookup ON library.peer_day(day, program, active);

--------------------------------------------------------------------------------
-- 2. USER MIGRATION FLAGS
--------------------------------------------------------------------------------

ALTER TABLE public.users ADD COLUMN IF NOT EXISTS peer_support_migrated BOOLEAN DEFAULT false;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS peer_support_migrated_at TIMESTAMPTZ;

--------------------------------------------------------------------------------
-- 3. SMS TYPE TRACKING INDEX
--------------------------------------------------------------------------------

CREATE INDEX IF NOT EXISTS idx_sms_messages_accountability
    ON comms.sms_messages(user_id, type)
    WHERE sent_at IS NULL AND type IN ('slip_up', 'get_back', 'check_in');

--------------------------------------------------------------------------------
-- 4. DATABASE FUNCTIONS
--------------------------------------------------------------------------------

-- Function: Update peer conversation on message insert
CREATE OR REPLACE FUNCTION comms.update_peer_conversation()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO comms.peer_conversations (
        user_id,
        name,
        last_message_id,
        last_message_text,
        last_message_timestamp,
        last_message_outbound,
        updated_at
    )
    SELECT
        NEW.user_id,
        u.name,
        NEW.id,
        NEW.text,
        NEW.created_at,
        NEW.outbound,
        now()
    FROM public.users u
    WHERE u.id = NEW.user_id
    ON CONFLICT (user_id) DO UPDATE SET
        last_message_id = NEW.id,
        last_message_text = NEW.text,
        last_message_timestamp = NEW.created_at,
        last_message_outbound = NEW.outbound,
        unread_count = CASE
            WHEN NEW.outbound = true THEN comms.peer_conversations.unread_count + 1
            ELSE comms.peer_conversations.unread_count
        END,
        updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger for peer conversation updates
CREATE TRIGGER peer_message_insert_trigger
    AFTER INSERT ON comms.peer_messages
    FOR EACH ROW EXECUTE FUNCTION comms.update_peer_conversation();

-- Function: Queue push notification when outbound peer message is inserted
CREATE OR REPLACE FUNCTION comms.queue_peer_message_notification()
RETURNS TRIGGER AS $$
BEGIN
    -- Only queue notification for outbound messages (from admin/system)
    IF NEW.outbound = true THEN
        INSERT INTO comms.notifications (user_id, title, body, metadata, timestamp, status)
        VALUES (
            NEW.user_id,
            '💬 Julian',
            LEFT(NEW.text, 100),
            jsonb_build_object('type', 'peerMessage', 'message_id', NEW.id),
            now(),
            'pending'
        );

        -- Mark the message as notification queued
        UPDATE comms.peer_messages
        SET notification_sent = now()
        WHERE id = NEW.id;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger for push notification queueing
CREATE TRIGGER peer_message_notification_trigger
    AFTER INSERT ON comms.peer_messages
    FOR EACH ROW EXECUTE FUNCTION comms.queue_peer_message_notification();

-- Function: Mark peer messages as read
CREATE OR REPLACE FUNCTION comms.mark_peer_messages_read(p_user_id TEXT)
RETURNS void AS $$
BEGIN
    UPDATE comms.peer_messages
    SET read_at = now()
    WHERE user_id = p_user_id AND outbound = true AND read_at IS NULL;

    UPDATE comms.peer_conversations
    SET unread_count = 0
    WHERE user_id = p_user_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

--------------------------------------------------------------------------------
-- 5. GRANTS
--------------------------------------------------------------------------------

-- Grant permissions on new tables
GRANT ALL ON comms.peer_messages TO anon, authenticated, service_role;
GRANT ALL ON comms.peer_conversations TO anon, authenticated, service_role;
GRANT ALL ON library.peer_day TO anon, authenticated, service_role;

-- Grant execute on functions
GRANT EXECUTE ON FUNCTION comms.mark_peer_messages_read(TEXT) TO anon, authenticated, service_role;

--------------------------------------------------------------------------------
-- 6. RLS POLICIES
--------------------------------------------------------------------------------

-- Enable RLS
ALTER TABLE comms.peer_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE comms.peer_conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE library.peer_day ENABLE ROW LEVEL SECURITY;

-- peer_messages: Users can read/write their own messages
CREATE POLICY "Users can read own peer messages" ON comms.peer_messages
    FOR SELECT USING (user_id = auth.uid()::text OR auth.role() = 'service_role');

CREATE POLICY "Users can insert own peer messages" ON comms.peer_messages
    FOR INSERT WITH CHECK (user_id = auth.uid()::text OR auth.role() = 'service_role');

CREATE POLICY "Service role can update peer messages" ON comms.peer_messages
    FOR UPDATE USING (auth.role() = 'service_role');

-- peer_conversations: Users can read their own conversation
CREATE POLICY "Users can read own peer conversation" ON comms.peer_conversations
    FOR SELECT USING (user_id = auth.uid()::text OR auth.role() = 'service_role');

CREATE POLICY "Service role can manage peer conversations" ON comms.peer_conversations
    FOR ALL USING (auth.role() = 'service_role');

-- peer_day: All authenticated users can read templates
CREATE POLICY "Authenticated users can read peer_day" ON library.peer_day
    FOR SELECT USING (auth.role() = 'authenticated' OR auth.role() = 'service_role');

CREATE POLICY "Service role can manage peer_day" ON library.peer_day
    FOR ALL USING (auth.role() = 'service_role');
