-- Migration: Add School Leaderboard Feature
-- This adds tables and functions for the university leaderboard where students can request Clear30 coverage at their school

-- ============================================
-- 1. Add logo_url column to existing schools.schools table (for partner school logos)
-- ============================================
ALTER TABLE schools.schools ADD COLUMN IF NOT EXISTS logo_url TEXT;

-- ============================================
-- 2. Create all_universities table (comprehensive list of requestable schools)
-- ============================================
CREATE TABLE schools.all_universities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    short_name TEXT,
    state TEXT,
    logo_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================
-- 3. Create leaderboard_requests table (user requests for school coverage)
-- ============================================
CREATE TABLE schools.leaderboard_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES public.users(id),
    university_id BIGINT NOT NULL REFERENCES schools.all_universities(id),
    reasons TEXT[] NOT NULL,
    impact TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, university_id)
);

-- Create index for faster lookups
CREATE INDEX idx_leaderboard_requests_university_id ON schools.leaderboard_requests(university_id);
CREATE INDEX idx_leaderboard_requests_user_id ON schools.leaderboard_requests(user_id);

-- ============================================
-- 4. Enable RLS
-- ============================================
ALTER TABLE schools.all_universities ENABLE ROW LEVEL SECURITY;
ALTER TABLE schools.leaderboard_requests ENABLE ROW LEVEL SECURITY;

-- ============================================
-- 5. RLS Policies
-- ============================================

-- Universities: anyone can read
CREATE POLICY "Anyone can read universities" ON schools.all_universities
    FOR SELECT USING (true);

-- Requests: anyone can read (for leaderboard counts)
CREATE POLICY "Anyone can read requests" ON schools.leaderboard_requests
    FOR SELECT USING (true);

-- Requests: authenticated users can insert their own
CREATE POLICY "Users can insert own requests" ON schools.leaderboard_requests
    FOR INSERT WITH CHECK (
        user_id = (SELECT id FROM public.users WHERE auth_id = auth.uid())
    );

-- ============================================
-- 6. Grant permissions
-- ============================================
GRANT SELECT ON schools.all_universities TO anon, authenticated;
GRANT SELECT, INSERT ON schools.leaderboard_requests TO authenticated;

-- ============================================
-- 7. Create get_leaderboard function
-- ============================================
CREATE OR REPLACE FUNCTION schools.get_leaderboard(p_limit INT DEFAULT 50)
RETURNS TABLE (
    university_id BIGINT,
    name TEXT,
    short_name TEXT,
    logo_url TEXT,
    request_count BIGINT,
    rank BIGINT
) AS $$
BEGIN
    RETURN QUERY
    SELECT
        u.id AS university_id,
        u.name,
        u.short_name,
        u.logo_url,
        COUNT(r.id) AS request_count,
        RANK() OVER (ORDER BY COUNT(r.id) DESC) AS rank
    FROM schools.all_universities u
    INNER JOIN schools.leaderboard_requests r ON u.id = r.university_id
    GROUP BY u.id, u.name, u.short_name, u.logo_url
    ORDER BY request_count DESC
    LIMIT p_limit;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Grant execute on function
GRANT EXECUTE ON FUNCTION schools.get_leaderboard TO authenticated;


COMMENT ON TABLE schools.all_universities IS 'Comprehensive list of US universities for the leaderboard feature';
COMMENT ON TABLE schools.leaderboard_requests IS 'User requests for Clear30 coverage at their school';
COMMENT ON FUNCTION schools.get_leaderboard IS 'Returns ranked universities by request count';
