-- Create library.sleep_resources table, mirroring library.craving_resources.
-- Kept as a separate table (rather than adding a type filter to craving_resources)
-- because shipped app versions fetch craving_resources with no filter and
-- crash on rows they don't recognize.

create table library.sleep_resources (
    id bigint generated by default as identity primary key,
    type text not null,
    data jsonb not null
);

alter table library.sleep_resources enable row level security;

create policy "Access to all"
    on library.sleep_resources
    for select
    to public
    using (true);
