create table "comms"."video_testimonials" (
    "id" bigint generated by default as identity not null,
    "user_id" text,
    "sections" jsonb not null,
    "payment_info" text not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "comms"."video_testimonials" enable row level security;

CREATE UNIQUE INDEX video_testimonials_pkey ON comms.video_testimonials USING btree (id);

alter table "comms"."video_testimonials" add constraint "video_testimonials_pkey" PRIMARY KEY using index "video_testimonials_pkey";

alter table "comms"."video_testimonials" add constraint "video_testimonials_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "comms"."video_testimonials" validate constraint "video_testimonials_user_id_fkey";

grant delete on table "comms"."video_testimonials" to "anon";

grant insert on table "comms"."video_testimonials" to "anon";

grant references on table "comms"."video_testimonials" to "anon";

grant select on table "comms"."video_testimonials" to "anon";

grant trigger on table "comms"."video_testimonials" to "anon";

grant truncate on table "comms"."video_testimonials" to "anon";

grant update on table "comms"."video_testimonials" to "anon";

grant delete on table "comms"."video_testimonials" to "authenticated";

grant insert on table "comms"."video_testimonials" to "authenticated";

grant references on table "comms"."video_testimonials" to "authenticated";

grant select on table "comms"."video_testimonials" to "authenticated";

grant trigger on table "comms"."video_testimonials" to "authenticated";

grant truncate on table "comms"."video_testimonials" to "authenticated";

grant update on table "comms"."video_testimonials" to "authenticated";

grant delete on table "comms"."video_testimonials" to "service_role";

grant insert on table "comms"."video_testimonials" to "service_role";

grant references on table "comms"."video_testimonials" to "service_role";

grant select on table "comms"."video_testimonials" to "service_role";

grant trigger on table "comms"."video_testimonials" to "service_role";

grant truncate on table "comms"."video_testimonials" to "service_role";

grant update on table "comms"."video_testimonials" to "service_role";

create policy "Users can access own"
on "comms"."video_testimonials"
as permissive
for select
to public
using ((user_id = ( SELECT get_user_id() AS get_user_id)));


create policy "Users can insert for self"
on "comms"."video_testimonials"
as permissive
for insert
to public
with check ((user_id = ( SELECT get_user_id() AS get_user_id)));



