-- Table to store email leads from school redemption pages
CREATE TABLE schools.school_leads (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id text NOT NULL REFERENCES schools.schools(school_id),
  email text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (school_id, email)
);

-- Enable RLS
ALTER TABLE schools.school_leads ENABLE ROW LEVEL SECURITY;

-- Grant access for service role operations
GRANT ALL ON schools.school_leads TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA schools TO anon, authenticated, service_role;
