-- coach_referral_events: tracks impressions, CTA taps, and skips for external coach referrals
-- (e.g. Phil Stille slide in PostAssessment). Kept separate from public.events so business
-- metrics can be queried with structured columns instead of JSON extraction.

create table comms.coach_referral_events (
    id bigint generated by default as identity primary key,
    user_id text not null,
    event_type text not null check (event_type in ('shown', 'cta_tapped', 'skipped')),
    placement text not null default 'post_assessment',
    coach_slug text not null,
    created_at timestamptz not null default now()
);

create index coach_referral_events_user_id_idx on comms.coach_referral_events(user_id);
create index coach_referral_events_created_at_idx on comms.coach_referral_events(created_at);
create index coach_referral_events_coach_slug_idx on comms.coach_referral_events(coach_slug);

alter table comms.coach_referral_events enable row level security;

create policy "Users insert own coach referral events"
    on comms.coach_referral_events
    for insert
    to authenticated
    with check (user_id = public.get_user_id());

create policy "Admin read coach referral events"
    on comms.coach_referral_events
    for select
    to authenticated
    using ((select public.admin_check()));
