drop policy "Disable access for all" on "schools"."school_activities";

drop policy "Disable access for all" on "schools"."school_messages";

drop policy "Disable access for all" on "schools"."school_resources";

drop policy "Allow authed access" on "schools"."schools";


  create table "schools"."portal_reports" (
    "id" bigint generated by default as identity not null,
    "school_id" text not null,
    "generated_by" bigint,
    "period_type" text not null,
    "period_label" text not null,
    "period_start" date,
    "period_end" date,
    "generated_at" timestamp with time zone not null default now()
      );


alter table "schools"."portal_reports" enable row level security;


  create table "schools"."portal_users" (
    "id" bigint generated by default as identity not null,
    "school_id" text not null,
    "auth_id" uuid,
    "email" text not null,
    "name" text not null,
    "first_name" text,
    "role" text not null default 'Team Member'::text,
    "is_admin" boolean not null default false,
    "invited_by" bigint,
    "invited_at" timestamp with time zone not null default now(),
    "invite_accepted_at" timestamp with time zone,
    "created_at" timestamp with time zone not null default now()
      );


alter table "schools"."portal_users" enable row level security;


  create table "schools"."tracking_link_clicks" (
    "id" bigint generated by default as identity not null,
    "school_id" text not null,
    "link_key" text not null,
    "clicked_at" timestamp with time zone not null default now(),
    "user_agent" text,
    "referrer" text
      );


alter table "schools"."tracking_link_clicks" enable row level security;

alter table "schools"."schools" add column "campus_url" text;

alter table "schools"."schools" add column "distribution_checklist" jsonb not null default '{}'::jsonb;

alter table "schools"."schools" add column "license_contact_email" text default 'julian@clear30.org'::text;

alter table "schools"."schools" add column "license_plan" text not null default 'Clear30 University Partner'::text;

alter table "schools"."schools" add column "license_renewal_date" date;

alter table "schools"."schools" add column "license_start_date" date;

alter table "schools"."schools" add column "license_tier" text not null default 'Premium'::text;

alter table "schools"."schools" add column "logo_wide_url" text;

alter table "schools"."schools" add column "partner_since" text;

alter table "schools"."schools" add column "student_population" integer;

alter table "schools"."schools" add column "tracking_links" jsonb not null default '{}'::jsonb;

CREATE INDEX idx_tracking_clicks_school_key ON schools.tracking_link_clicks USING btree (school_id, link_key);

CREATE UNIQUE INDEX portal_reports_pkey ON schools.portal_reports USING btree (id);

CREATE UNIQUE INDEX portal_users_auth_id_key ON schools.portal_users USING btree (auth_id);

CREATE UNIQUE INDEX portal_users_email_key ON schools.portal_users USING btree (email);

CREATE UNIQUE INDEX portal_users_pkey ON schools.portal_users USING btree (id);

CREATE UNIQUE INDEX tracking_link_clicks_pkey ON schools.tracking_link_clicks USING btree (id);

alter table "schools"."portal_reports" add constraint "portal_reports_pkey" PRIMARY KEY using index "portal_reports_pkey";

alter table "schools"."portal_users" add constraint "portal_users_pkey" PRIMARY KEY using index "portal_users_pkey";

alter table "schools"."tracking_link_clicks" add constraint "tracking_link_clicks_pkey" PRIMARY KEY using index "tracking_link_clicks_pkey";

alter table "schools"."portal_reports" add constraint "portal_reports_generated_by_fkey" FOREIGN KEY (generated_by) REFERENCES schools.portal_users(id) ON DELETE SET NULL not valid;

alter table "schools"."portal_reports" validate constraint "portal_reports_generated_by_fkey";

alter table "schools"."portal_reports" add constraint "portal_reports_school_id_fkey" FOREIGN KEY (school_id) REFERENCES schools.schools(school_id) ON DELETE CASCADE not valid;

alter table "schools"."portal_reports" validate constraint "portal_reports_school_id_fkey";

alter table "schools"."portal_users" add constraint "portal_users_auth_id_fkey" FOREIGN KEY (auth_id) REFERENCES auth.users(id) ON DELETE SET NULL not valid;

alter table "schools"."portal_users" validate constraint "portal_users_auth_id_fkey";

alter table "schools"."portal_users" add constraint "portal_users_auth_id_key" UNIQUE using index "portal_users_auth_id_key";

alter table "schools"."portal_users" add constraint "portal_users_email_key" UNIQUE using index "portal_users_email_key";

alter table "schools"."portal_users" add constraint "portal_users_invited_by_fkey" FOREIGN KEY (invited_by) REFERENCES schools.portal_users(id) ON DELETE SET NULL not valid;

alter table "schools"."portal_users" validate constraint "portal_users_invited_by_fkey";

alter table "schools"."portal_users" add constraint "portal_users_role_check" CHECK ((role = ANY (ARRAY['Admin'::text, 'Team Member'::text]))) not valid;

alter table "schools"."portal_users" validate constraint "portal_users_role_check";

alter table "schools"."portal_users" add constraint "portal_users_school_id_fkey" FOREIGN KEY (school_id) REFERENCES schools.schools(school_id) ON DELETE CASCADE not valid;

alter table "schools"."portal_users" validate constraint "portal_users_school_id_fkey";

alter table "schools"."tracking_link_clicks" add constraint "tracking_link_clicks_school_id_fkey" FOREIGN KEY (school_id) REFERENCES schools.schools(school_id) ON DELETE CASCADE not valid;

alter table "schools"."tracking_link_clicks" validate constraint "tracking_link_clicks_school_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION schools.get_portal_school_id()
 RETURNS text
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'schools', 'public'
AS $function$
  SELECT school_id
  FROM schools.portal_users
  WHERE auth_id = auth.uid()
  LIMIT 1;
$function$
;

CREATE OR REPLACE FUNCTION schools.get_school_analytics(p_school_id text)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'schools', 'public', 'payment'
AS $function$
BEGIN
  IF schools.get_portal_school_id() IS DISTINCT FROM p_school_id THEN
    RAISE EXCEPTION 'Access denied: not a portal user for school %', p_school_id;
  END IF;

  RETURN (
    WITH school_users AS (
      SELECT u.id, u.created_at, u.day_info
      FROM public.users u
      JOIN payment.domain_allowlist dal
        ON u.email ILIKE ('%@' || dal.domain)
      WHERE dal.school_id = p_school_id
        AND u.day_info IS NOT NULL
        AND jsonb_array_length(u.day_info) > 0
    ),
    checkin_stats AS (
      SELECT
        su.id,
        su.created_at,
        COUNT(*) FILTER (
          WHERE jsonb_typeof(elem) = 'object'
        ) AS total_checkins,
        COUNT(*) FILTER (
          WHERE jsonb_typeof(elem) = 'object'
            AND (elem->>'sober')::boolean = true
        ) AS sober_days,
        -- The date strings in day_info tell us when the last check-in was
        MAX(
          CASE WHEN jsonb_typeof(elem) = 'string'
            THEN (elem #>> '{}')::date
            ELSE NULL
          END
        ) AS last_checkin_date
      FROM school_users su,
        jsonb_array_elements(su.day_info) AS elem
      GROUP BY su.id, su.created_at
    )
    SELECT jsonb_build_object(
      'total_students',   COUNT(*),
      'total_checkins',   COALESCE(SUM(total_checkins), 0),
      'total_sober_days', COALESCE(SUM(sober_days), 0),
      'active_last_30d',  COUNT(*) FILTER (
                            WHERE last_checkin_date >= CURRENT_DATE - INTERVAL '30 days'
                          )
    )
    FROM checkin_stats
  );
END;
$function$
;

CREATE OR REPLACE FUNCTION schools.get_school_checkin_trend(p_school_id text, p_interval text DEFAULT 'weekly'::text)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'schools', 'public', 'payment'
AS $function$
BEGIN
  IF schools.get_portal_school_id() IS DISTINCT FROM p_school_id THEN
    RAISE EXCEPTION 'Access denied: not a portal user for school %', p_school_id;
  END IF;

  IF p_interval = 'monthly' THEN
    RETURN (
      WITH school_users AS (
        SELECT u.id, u.day_info
        FROM public.users u
        JOIN payment.domain_allowlist dal ON u.email ILIKE ('%@' || dal.domain)
        WHERE dal.school_id = p_school_id
          AND u.day_info IS NOT NULL
          AND jsonb_array_length(u.day_info) > 0
      ),
      -- Attach the previous element to each row so we can pair date strings
      -- with their corresponding check-in objects
      indexed AS (
        SELECT
          su.id,
          elem,
          jsonb_typeof(elem)                                         AS elem_type,
          LAG(elem) OVER (PARTITION BY su.id ORDER BY idx)          AS prev_elem
        FROM school_users su,
          jsonb_array_elements(su.day_info) WITH ORDINALITY AS t(elem, idx)
      ),
      -- Each object element's preceding sibling is the date string
      pairs AS (
        SELECT
          (prev_elem #>> '{}')::date   AS checkin_date,
          (elem->>'sober')::boolean    AS sober
        FROM indexed
        WHERE elem_type = 'object' AND prev_elem IS NOT NULL
      )
      SELECT COALESCE(jsonb_agg(row ORDER BY bucket), '[]'::jsonb)
      FROM (
        SELECT
          date_trunc('month', checkin_date) AS bucket,
          jsonb_build_object(
            'label',     to_char(date_trunc('month', checkin_date), 'Mon YYYY'),
            'checkIns',  COUNT(*),
            'soberDays', COUNT(*) FILTER (WHERE sober = true)
          ) AS row
        FROM pairs
        WHERE checkin_date IS NOT NULL
        GROUP BY 1
      ) t
    );
  ELSE
    -- weekly (default)
    RETURN (
      WITH school_users AS (
        SELECT u.id, u.day_info
        FROM public.users u
        JOIN payment.domain_allowlist dal ON u.email ILIKE ('%@' || dal.domain)
        WHERE dal.school_id = p_school_id
          AND u.day_info IS NOT NULL
          AND jsonb_array_length(u.day_info) > 0
      ),
      indexed AS (
        SELECT
          su.id,
          elem,
          jsonb_typeof(elem)                                         AS elem_type,
          LAG(elem) OVER (PARTITION BY su.id ORDER BY idx)          AS prev_elem
        FROM school_users su,
          jsonb_array_elements(su.day_info) WITH ORDINALITY AS t(elem, idx)
      ),
      pairs AS (
        SELECT
          (prev_elem #>> '{}')::date   AS checkin_date,
          (elem->>'sober')::boolean    AS sober
        FROM indexed
        WHERE elem_type = 'object' AND prev_elem IS NOT NULL
      )
      SELECT COALESCE(jsonb_agg(row ORDER BY bucket), '[]'::jsonb)
      FROM (
        SELECT
          date_trunc('week', checkin_date) AS bucket,
          jsonb_build_object(
            'label',     to_char(date_trunc('week', checkin_date), 'MM/DD'),
            'checkIns',  COUNT(*),
            'soberDays', COUNT(*) FILTER (WHERE sober = true)
          ) AS row
        FROM pairs
        WHERE checkin_date IS NOT NULL
        GROUP BY 1
      ) t
    );
  END IF;
END;
$function$
;

CREATE OR REPLACE FUNCTION schools.get_school_enrollment_trend(p_school_id text, p_interval text DEFAULT 'weekly'::text)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'schools', 'public', 'payment'
AS $function$
BEGIN
  IF schools.get_portal_school_id() IS DISTINCT FROM p_school_id THEN
    RAISE EXCEPTION 'Access denied: not a portal user for school %', p_school_id;
  END IF;

  IF p_interval = 'monthly' THEN
    RETURN (
      SELECT COALESCE(jsonb_agg(row ORDER BY bucket), '[]'::jsonb)
      FROM (
        SELECT
          date_trunc('month', u.created_at) AS bucket,
          jsonb_build_object(
            'label',    to_char(date_trunc('month', u.created_at), 'Mon YYYY'),
            'students', COUNT(*)
          ) AS row
        FROM public.users u
        JOIN payment.domain_allowlist dal ON u.email ILIKE ('%@' || dal.domain)
        WHERE dal.school_id = p_school_id
        GROUP BY 1
      ) t
    );
  ELSE
    -- weekly (default)
    RETURN (
      SELECT COALESCE(jsonb_agg(row ORDER BY bucket), '[]'::jsonb)
      FROM (
        SELECT
          date_trunc('week', u.created_at) AS bucket,
          jsonb_build_object(
            'label',    to_char(date_trunc('week', u.created_at), 'MM/DD'),
            'students', COUNT(*)
          ) AS row
        FROM public.users u
        JOIN payment.domain_allowlist dal ON u.email ILIKE ('%@' || dal.domain)
        WHERE dal.school_id = p_school_id
        GROUP BY 1
      ) t
    );
  END IF;
END;
$function$
;

CREATE OR REPLACE FUNCTION schools.get_tracking_link_stats(p_school_id text)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'schools', 'public'
AS $function$
BEGIN
  IF schools.get_portal_school_id() IS DISTINCT FROM p_school_id THEN
    RAISE EXCEPTION 'Access denied: not a portal user for school %', p_school_id;
  END IF;

  RETURN (
    SELECT COALESCE(
      jsonb_object_agg(link_key, click_count),
      '{}'::jsonb
    )
    FROM (
      SELECT link_key, COUNT(*) AS click_count
      FROM schools.tracking_link_clicks
      WHERE school_id = p_school_id
      GROUP BY link_key
    ) t
  );
END;
$function$
;

CREATE OR REPLACE FUNCTION schools.is_portal_admin()
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'schools', 'public'
AS $function$
  SELECT COALESCE(
    (SELECT is_admin FROM schools.portal_users WHERE auth_id = auth.uid() LIMIT 1),
    false
  );
$function$
;


  create policy "portal_users_insert_reports"
  on "schools"."portal_reports"
  as permissive
  for insert
  to public
with check ((school_id = schools.get_portal_school_id()));



  create policy "portal_users_select_reports"
  on "schools"."portal_reports"
  as permissive
  for select
  to public
using ((school_id = schools.get_portal_school_id()));



  create policy "portal_admins_delete_members"
  on "schools"."portal_users"
  as permissive
  for delete
  to public
using (((school_id = schools.get_portal_school_id()) AND schools.is_portal_admin() AND (auth_id IS DISTINCT FROM auth.uid())));



  create policy "portal_admins_insert_members"
  on "schools"."portal_users"
  as permissive
  for insert
  to public
with check (((school_id = schools.get_portal_school_id()) AND schools.is_portal_admin()));



  create policy "portal_users_select_own_school_members"
  on "schools"."portal_users"
  as permissive
  for select
  to public
using ((school_id = schools.get_portal_school_id()));



  create policy "portal_users_update_members"
  on "schools"."portal_users"
  as permissive
  for update
  to public
using (((school_id = schools.get_portal_school_id()) AND (schools.is_portal_admin() OR (auth_id = auth.uid()))))
with check (((school_id = schools.get_portal_school_id()) AND (schools.is_portal_admin() OR (auth_id = auth.uid()))));



  create policy "portal_users_delete_activities"
  on "schools"."school_activities"
  as permissive
  for delete
  to public
using ((school_id = schools.get_portal_school_id()));



  create policy "portal_users_insert_activities"
  on "schools"."school_activities"
  as permissive
  for insert
  to public
with check ((school_id = schools.get_portal_school_id()));



  create policy "portal_users_select_activities"
  on "schools"."school_activities"
  as permissive
  for select
  to public
using ((school_id = schools.get_portal_school_id()));



  create policy "portal_users_update_activities"
  on "schools"."school_activities"
  as permissive
  for update
  to public
using ((school_id = schools.get_portal_school_id()))
with check ((school_id = schools.get_portal_school_id()));



  create policy "portal_users_delete_messages"
  on "schools"."school_messages"
  as permissive
  for delete
  to public
using ((school_id = schools.get_portal_school_id()));



  create policy "portal_users_insert_messages"
  on "schools"."school_messages"
  as permissive
  for insert
  to public
with check ((school_id = schools.get_portal_school_id()));



  create policy "portal_users_select_messages"
  on "schools"."school_messages"
  as permissive
  for select
  to public
using ((school_id = schools.get_portal_school_id()));



  create policy "portal_users_update_messages"
  on "schools"."school_messages"
  as permissive
  for update
  to public
using ((school_id = schools.get_portal_school_id()))
with check ((school_id = schools.get_portal_school_id()));



  create policy "portal_users_delete_resources"
  on "schools"."school_resources"
  as permissive
  for delete
  to public
using ((school_id = schools.get_portal_school_id()));



  create policy "portal_users_insert_resources"
  on "schools"."school_resources"
  as permissive
  for insert
  to public
with check ((school_id = schools.get_portal_school_id()));



  create policy "portal_users_select_resources"
  on "schools"."school_resources"
  as permissive
  for select
  to public
using ((school_id = schools.get_portal_school_id()));



  create policy "portal_users_update_resources"
  on "schools"."school_resources"
  as permissive
  for update
  to public
using ((school_id = schools.get_portal_school_id()))
with check ((school_id = schools.get_portal_school_id()));



  create policy "portal_admins_update_own_school"
  on "schools"."schools"
  as permissive
  for update
  to public
using (((school_id = schools.get_portal_school_id()) AND schools.is_portal_admin()))
with check (((school_id = schools.get_portal_school_id()) AND schools.is_portal_admin()));



  create policy "portal_users_select_own_school"
  on "schools"."schools"
  as permissive
  for select
  to public
using ((school_id = schools.get_portal_school_id()));



  create policy "portal_users_select_clicks"
  on "schools"."tracking_link_clicks"
  as permissive
  for select
  to public
using ((school_id = schools.get_portal_school_id()));



