-- Create new simplified table for start-soon messages
CREATE TABLE library.sms_start_soon (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type text NOT NULL DEFAULT 'countdown',  -- 'intro' or 'countdown'
  day integer NOT NULL,  -- For countdown: days until Clear30 (0 = start day, 1 = tomorrow). For intro: always 0
  hour integer,          -- Hour to send (UTC), null = use default
  question_id text,      -- Assessment question to match
  question_response text, -- Required response value
  text text NOT NULL     -- Message content
);

-- Enable RLS
ALTER TABLE library.sms_start_soon ENABLE ROW LEVEL SECURITY;

-- Grant permissions
GRANT SELECT ON library.sms_start_soon TO anon, authenticated, service_role;

-- Add comment
COMMENT ON TABLE library.sms_start_soon IS 'SMS messages for start-soon period: intro (sent when entering countdown) and countdown (daily until Clear30)';

-- Migrate intro messages (matches_program_time = false, no additional_id)
-- These are sent when user first enters the start-soon break
INSERT INTO library.sms_start_soon (type, day, hour, question_id, question_response, text)
SELECT 'intro', day, hour, question_id, question_response, text
FROM library.sms_day
WHERE program = 'clear30-start-soon'
  AND matches_program_time = false
  AND (additional_id IS NULL OR additional_id = '');
