-- Seed: payment.hard_paywalls
-- Source: 2025_12_16_paywalls.csv (most recent)
-- Controls paywall hardness + extra config per paywall ID

TRUNCATE payment.hard_paywalls CASCADE;

INSERT INTO payment.hard_paywalls (id, paywall_id, hard, extra_data) VALUES
  (32, 'cb_120life_30y_demo', true, '{"show_tutorial_on_dismiss":true}'),
  (33, 'cb_120life_40y_demo', true, '{"show_tutorial_on_dismiss":true}'),
  (34, 'stripe_cb_15m_40y_video', true, '{"entitlement":"Plus","is_stripe_paywall":true,"stripe_product_mapping":{"org.clear30.Clear30.yearly":{"amount":39.99,"interval":"yearly","trial_days":3,"display_name":"Clear30 Yearly","stripe_product_id":"prod_TPUxQcIerfACJF"},"org.clear30.Clear30.monthly15":{"amount":14.99,"interval":"monthly","trial_days":0,"display_name":"Clear30 Monthly","stripe_product_id":"prod_TRLzWF54Is3BS0"}}}'),
  (35, 'qa_stripe_cb_15m_40y_video', true, '{"entitlement":"Plus","down_sell_info":{"placement":"pro_to_core","notification_body":"Before you go, we want to give you a little something \ud83d\udc40","notification_title":"Free Gift!! \ud83c\udf81\ud83e\udd79"},"is_stripe_paywall":true,"stripe_product_mapping":{"org.clear30.Clear30.yearly":{"amount":39.99,"interval":"yearly","trial_days":3,"display_name":"Clear30 Yearly (QA)","stripe_product_id":"prod_TPTyZX7tpBJMFL"},"org.clear30.Clear30.monthly15":{"amount":14.99,"interval":"monthly","trial_days":0,"display_name":"Clear30 Monthly (QA)","stripe_product_id":"prod_TPcr04Wtw4CXrF"}}}'),
  (36, 'stripe_popup_discount_30y', true, '{"entitlement":"Plus","is_stripe_paywall":true,"stripe_product_mapping":{"org.clear30.Clear30.yearly30":{"amount":29.99,"interval":"yearly","trial_days":0,"display_name":"Clear30 Yearly Discount","stripe_product_id":"prod_TSChtDwHQLt673"}}}'),
  (37, 'stripe_popup_gain_control', true, '{"entitlement":"Plus","is_stripe_paywall":true,"stripe_product_mapping":{"org.clear30.Clear30.yearly30":{"amount":29.99,"interval":"yearly","trial_days":0,"display_name":"Clear30 Yearly Discount","stripe_product_id":"prod_TSChtDwHQLt673"}}}'),
  (38, 'stripe_cbcm_120life_30y', true, '{"entitlement":"Plus","is_stripe_paywall":true,"stripe_product_mapping":{"org.clear30.Clear30.yearly30":{"amount":29.99,"interval":"yearly","trial_days":3,"display_name":"Clear30 Cyber Monday Discount","stripe_product_id":"prod_TSChtDwHQLt673"}}}'),
  (39, 'stripe_cb_120life_40y_video', true, '{"entitlement":"Plus","down_sell_info":{"placement":"pro_to_core","notification_body":"Before you go, we want to give you a little something \ud83d\udc40","notification_title":"Free Gift!! \ud83c\udf81\ud83e\udd79"},"is_stripe_paywall":true,"stripe_product_mapping":{"org.clear30.Clear30.yearly":{"amount":39.99,"interval":"yearly","trial_days":3,"display_name":"Clear30 Yearly","stripe_product_id":"prod_TPUxQcIerfACJF"}}}'),
  (40, 'stripe_core_meditation_30y', true, '{"entitlement":"Core","is_stripe_paywall":true,"stripe_product_mapping":{"org.clear30.Clear30.core.yearly30":{"amount":29.99,"interval":"yearly","trial_days":3,"display_name":"Clear30 Core Yearly","stripe_product_id":"prod_TXPli1dDVXV6tN"}}}'),
  (41, 'qa_stripe_core_meditation_30y', true, '{"entitlement":"Core","is_stripe_paywall":true,"stripe_product_mapping":{"org.clear30.Clear30.core.yearly30":{"amount":29.99,"interval":"yearly","trial_days":3,"display_name":"Clear30 Core Yearly (QA)","stripe_product_id":"prod_TXTeQ4pvb20zs8"}}}'),
  (42, 'stripe_pro_upsell_40y', true, '{"entitlement":"Plus","initial_offer":false,"is_stripe_paywall":true,"stripe_product_mapping":{"org.clear30.Clear30.yearly":{"amount":39.99,"interval":"yearly","trial_days":0,"display_name":"Clear30 Yearly","stripe_product_id":"prod_TPUxQcIerfACJF"}}}'),
  (43, 'qa_stripe_pro_upsell_40y', true, '{"entitlement":"Plus","initial_offer":false,"is_stripe_paywall":true,"stripe_product_mapping":{"org.clear30.Clear30.yearly":{"amount":39.99,"interval":"yearly","trial_days":0,"display_name":"Clear30 Yearly (QA)","stripe_product_id":"prod_TPTyZX7tpBJMFL"}}}')
ON CONFLICT (id) DO NOTHING;
