-- Seed: library.support_items
-- Source: 2025_08_23_support_items.csv
-- Generated by generate_seeds.py

TRUNCATE library.support_items CASCADE;

INSERT INTO library.support_items (id, button_title, button_symbol, color1, color2, sheet_info) VALUES (1, 'Supplements', 'pill.fill', '5FA7F1', '67D0C0', '{"link":"https://clear30.org/webapps/supplements/?user_id=_USERID_&from=app_button","title":"Feel Like Yourself Again","color1":"#5FA7F1","color2":"#67D0C0","subtitle":"Get your own science backed supplement plan in less than a minute!","sf_symbol":"pill.fill","button_text":"Level Up","button_sf_symbol":"sparkle.magnifyingglass"}') ON CONFLICT (id) DO NOTHING;
