-- Seed: library.craving_resources
-- Source: 2025_10_20_craving_resources.csv
-- Generated by generate_seeds.py

TRUNCATE library.craving_resources CASCADE;

INSERT INTO library.craving_resources (id, type, data) VALUES (3, 'meditation', '{"url": "https://m.clear30.org/cravings/notice_without_needing_2.wav", "name": "Notice Without Needing"}') ON CONFLICT (id) DO NOTHING;
INSERT INTO library.craving_resources (id, type, data) VALUES (4, 'meditation', '{"url": "https://m.clear30.org/cravings/cravings_pass_2.wav", "name": "Cravings Pass"}') ON CONFLICT (id) DO NOTHING;
INSERT INTO library.craving_resources (id, type, data) VALUES (5, 'meditation', '{"url": "https://m.clear30.org/cravings/become_powerful.wav", "name": "Become Powerful"}') ON CONFLICT (id) DO NOTHING;
INSERT INTO library.craving_resources (id, type, data) VALUES (6, 'meditation', '{"url": "https://m.clear30.org/cravings/unstoppable_force.wav", "name": "Unstoppable Force"}') ON CONFLICT (id) DO NOTHING;
INSERT INTO library.craving_resources (id, type, data) VALUES (7, 'meditation', '{"url": "https://m.clear30.org/cravings/connection_over_craving.wav", "name": "Connection Over Craving"}') ON CONFLICT (id) DO NOTHING;
INSERT INTO library.craving_resources (id, type, data) VALUES (8, 'meditation', '{"url": "https://m.clear30.org/cravings/growing_pains.wav", "name": "Growing Pains"}') ON CONFLICT (id) DO NOTHING;
INSERT INTO library.craving_resources (id, type, data) VALUES (9, 'meditation', '{"url": "https://m.clear30.org/cravings/every_breath_is_a_choice.wav", "name": "Every Breath Is A Choice"}') ON CONFLICT (id) DO NOTHING;
INSERT INTO library.craving_resources (id, type, data) VALUES (10, 'meditation', '{"url": "https://m.clear30.org/cravings/one_choice_stronger_2.wav", "name": "One Choice Stronger"}') ON CONFLICT (id) DO NOTHING;
