-- Seed: library.onboarding_reviews
-- Source: 2025_04_28_onboarding_reviews.csv
-- Generated by generate_seeds.py

TRUNCATE library.onboarding_reviews CASCADE;

INSERT INTO library.onboarding_reviews (id, title, body, priority, created_at, author) VALUES (1, 'Finally something personal!', 'I really appreciated this app and how personalized it was. I didn’t want to fully quit, and just wanted to monitor my use. Nobody tried to force me to fully quit smoking, and I was able to really cut down on use. When I was struggling with cravings I reached out to peer support and they had great advice! Thank you guys so much', 1, '2025-04-28 03:08:36+00', 'LorSing') ON CONFLICT (id) DO NOTHING;
INSERT INTO library.onboarding_reviews (id, title, body, priority, created_at, author) VALUES (2, 'Highly recommend', 'I have been smoking for 8 years straight every day. I randomly got the urge to try quitting for the second time (The first time lasted 2 days). At this time I saw an add for this app and decided to give it a try, I did not expect it to work. However I was wrong, simply just seeing the time I’ve been clean for and the symptoms that are normal too feel has really helped me!', 1, '2025-04-28 03:09:22.157583+00', 'JimD555') ON CONFLICT (id) DO NOTHING;
