-- Seed: library.push_check_in
-- Source: 2025_03_03_push_check_in.csv
-- Generated by generate_seeds.py

TRUNCATE library.push_check_in CASCADE;

INSERT INTO library.push_check_in (id, title, body, question_id, question_response) VALUES (1, '🔮 A fortune teller told us you’d check in today.', 'Don’t prove them wrong. 👁️ 🐽👁️', NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO library.push_check_in (id, title, body, question_id, question_response) VALUES (2, '🎶 Like a good neighbor, Clear30 is there!', 'With a reminder to check in on the app 💚', NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO library.push_check_in (id, title, body, question_id, question_response) VALUES (3, 'Your entire bloodline is cheering you on ✨', '✅ They''re waiting for you to check in on Clear30 _CLIENTNAME_', NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO library.push_check_in (id, title, body, question_id, question_response) VALUES (4, '1ASD$HASJH32DJASLSA', 'Sorry my dog stepped on my keyboard... 😅

Tryna check in on Clear30?', NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO library.push_check_in (id, title, body, question_id, question_response) VALUES (5, '"🤖 Hey GPT...', 'Can you write a message for _CLIENTNAME_ to get them to check in on Clear30"', NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO library.push_check_in (id, title, body, question_id, question_response) VALUES (6, '🌹🌸💐🌺🌷🌻🪻
', 'Hey _CLIENTNAME_ I picked some flowers for you. And wanna remind you to checkinnnnn :)', NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO library.push_check_in (id, title, body, question_id, question_response) VALUES (7, '😪Nice guys always finish last', 'Why does everyone choose instachat and snapgram over ME? 

I''m a fun app! I just want to help you 🥺', NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO library.push_check_in (id, title, body, question_id, question_response) VALUES (8, '🛑 DON''T CHECK IN TODAY
', 'Definitely DO NOT. Don''t check in on Clear30. Please don''t. Just don''t do it.', NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO library.push_check_in (id, title, body, question_id, question_response) VALUES (9, 'I like Chicken 🐔
', 'Wait... Did I say Chicken?
I meant Checking In.
Like on Clear30 ya know', NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO library.push_check_in (id, title, body, question_id, question_response) VALUES (10, '💰 Get your money up!', '🤣 Not your funny up...

What I''m trying to say _CLIENTNAME_ is you should check in ✅', NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO library.push_check_in (id, title, body, question_id, question_response) VALUES (11, '♟️Are you playing Checkers or chess?', 'Cause you gotta check in to be the best...

Mic Drop 🎤🤯', NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO library.push_check_in (id, title, body, question_id, question_response) VALUES (12, 'Me when you check in: 
', '😋', NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO library.push_check_in (id, title, body, question_id, question_response) VALUES (13, 'Me when you don''t check in ', '😖', NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO library.push_check_in (id, title, body, question_id, question_response) VALUES (14, 'Are you suffering from...', '✨Sub-Optimal Aura✨
If so - 
✅Check IN✅', NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO library.push_check_in (id, title, body, question_id, question_response) VALUES (15, '🚨THIS IS THE IRS YOU OWE US $$', 'jk - its Clear30 reminding you to checkin', NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO library.push_check_in (id, title, body, question_id, question_response) VALUES (16, 'You smoke today?
', '☕️💅 Fill us innnnn', NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO library.push_check_in (id, title, body, question_id, question_response) VALUES (17, 'We cant solve all your problems...', 'But we can solve some :) 
If you Check In _CLIENTNAME_', NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO library.push_check_in (id, title, body, question_id, question_response) VALUES (18, 'There''s no comparison...
', '😢👮 Police checking your vehicle
vs.
🤩💚 _CLIENTNAME_ checking in on C30', NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO library.push_check_in (id, title, body, question_id, question_response) VALUES (19, 'Ch ch ch ch ch...', '💪😎Check in', NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO library.push_check_in (id, title, body, question_id, question_response) VALUES (20, '🙏 NI KCEHC', 'Can you decipher the riddle above _CLIENTNAME_?', NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO library.push_check_in (id, title, body, question_id, question_response) VALUES (21, '🫅I DECLARE...
', 'That it is time for you to check in _CLIENTNAME_!', NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO library.push_check_in (id, title, body, question_id, question_response) VALUES (22, '🌈Life when you check in', '🌨️Life when you don''t check in', NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO library.push_check_in (id, title, body, question_id, question_response) VALUES (23, '💍Will you...', 'Make me the happiest app in the word?

And Check-in?', NULL, NULL) ON CONFLICT (id) DO NOTHING;
