-- Seed: programs.remote_assessment_questions
-- Source: 2025_07_17_assessment_remote.csv
-- Generated by generate_seeds.py

TRUNCATE programs.remote_assessment_questions CASCADE;

INSERT INTO programs.remote_assessment_questions (id, after_question_id, stripped_prompt, prompt1, prompt2, options, displayed_options, image_names, badges, subtexts, min, max, enabled, created_at, randomize_options) VALUES (1, 'triggers_affirmation', 'Planned-Usage', '', 'What do you plan to use Clear30 for?', '["Claire", "Community", "Guides", "Journaling", "Journal Prompts", "Clinician Chat", "Symptom Relief", "Emergency Resources", "Goal Tracking", "Money Tracker", "Support Buddy", "Group Chats", "Meditations", "Daily Messages", "Long Term Program"]', '["🤖 Access to Claire, AI Weed Expert", "🌍 Clear30 Community", "📚 In-Depth Guides for your Goals", "✍️🎥 Text and Video Journaling", "📝 Daily Journal Prompts", "💬 Talk with a Clinician", "🧠 Symptom Breakdown and Relief", "🚨 Emergency Craving Resources", "📊 Daily Goal Tracking", "💸 Money Saved Tracker", "👫 24/7 Support Buddy", "🗣️ Clear30 Group Chats", "🧘 Guided Meditations", "🎯 Personalized Daily Messages & Videos", "🚀 Long-Term Goals Program"]', NULL, NULL, NULL, 1, 3, TRUE, '2025-07-17 21:07:26.675535+00', TRUE) ON CONFLICT (id) DO NOTHING;
