-- Seed: events.events
-- Source: events.csv (April 2025 university cohort event, for local dev/testing)
-- Generated by generate_seeds.py

-- NOTE: events.events references community.tags. Insert stub tags first to satisfy FK.
INSERT INTO community.tags (id, name, created_at) VALUES
  ('688ec9e9-3aa8-4f24-a3bc-06430b8a24c7', '4/21 Lobby', NOW()),
  ('3105ea01-6e14-4e22-a4cb-74a874893b9a', '4/21 Community', NOW())
ON CONFLICT (id) DO NOTHING;

-- NOTE: Events are time-limited; these are April 2025 events for local dev/testing.
TRUNCATE events.events CASCADE;

INSERT INTO events.events (id, name, short_name, num_waiting, onboarding_start_date, onboarding_end_date, program_day_1, app_unlock_date, color1, color2, sms_id, lobby_community_tag, community_tag, end_date) VALUES ('421', 'The 4/21 Weed Break', '4/21', 103, '2025-04-15', '2025-04-21', '2025-04-21', '2025-04-21', '5F95F1', '9F42FE', '421', '688ec9e9-3aa8-4f24-a3bc-06430b8a24c7', '3105ea01-6e14-4e22-a4cb-74a874893b9a', '2025-05-20') ON CONFLICT (id) DO NOTHING;
