-- ============================================================
-- QA USER SEED — goldieclear30@gmail.com
-- ============================================================
-- Seeds the Goldie QA test user for local simulator testing.
--
-- Generated by Star ⭐ after full onboarding + check-in run on 2026-02-22.
--
-- auth.users: pre-seeded so GoTrue can locate the user on sign-in.
--   - Use ON CONFLICT DO NOTHING to avoid errors on subsequent resets.
--
-- public.users: upserted with content_info + day_info from a completed
--   onboarding + check-in session.
--   - ON CONFLICT (id) DO UPDATE SET content_info, day_info so the row
--     reflects the latest snapshot without clobbering other columns.
--
-- OTP for sign-in after reset goes to REAL Gmail (goldieclear30@gmail.com)
-- because config.toml uses smtp.gmail.com — NOT local Mailpit.
-- Check with: himalaya envelope list --account goldie
-- ============================================================

-- ── auth.users ──────────────────────────────────────────────
INSERT INTO "auth"."users"
            ("instance_id",
             "id",
             "aud",
             "role",
             "email",
             "encrypted_password",
             "email_confirmed_at",
             "invited_at",
             "confirmation_token",
             "confirmation_sent_at",
             "recovery_token",
             "recovery_sent_at",
             "email_change_token_new",
             "email_change",
             "email_change_sent_at",
             "last_sign_in_at",
             "raw_app_meta_data",
             "raw_user_meta_data",
             "is_super_admin",
             "created_at",
             "updated_at",
             "phone",
             "phone_confirmed_at",
             "phone_change",
             "phone_change_token",
             "phone_change_sent_at",
             "email_change_token_current",
             "email_change_confirm_status",
             "banned_until",
             "reauthentication_token",
             "reauthentication_sent_at",
             "is_sso_user",
             "deleted_at",
             "is_anonymous")
VALUES      ('00000000-0000-0000-0000-000000000000',
             '0a6c079b-5f79-4a21-ae4d-a9c2f7780991',
             'authenticated',
             'authenticated',
             'goldieclear30@gmail.com',
             '$2a$10$SlsHGrZ4/y483trEE/Sy9eXw/UGS1Wf6SjC01wvn2Qz7vI7n61i7C',
             '2026-02-22 04:54:31.411855+00',
             NULL,
             '',
             '2026-02-22 04:52:26.375694+00',
             '',
             '2026-02-22 05:27:56.896918+00',
             '',
             '',
             NULL,
             '2026-02-22 05:28:07.324869+00',
             '{"provider": "email", "providers": ["email"]}',
             '{"sub": "0a6c079b-5f79-4a21-ae4d-a9c2f7780991", "email": "goldieclear30@gmail.com", "email_verified": true, "phone_verified": false}',
             NULL,
             '2026-02-22 04:51:24.857029+00',
             '2026-02-22 05:28:07.326615+00',
             NULL,
             NULL,
             '',
             '',
             NULL,
             '2026-02-22 04:54:31.411855+00',
             '0',
             NULL,
             '',
             NULL,
             'false',
             NULL,
             'false')
ON CONFLICT (id) DO NOTHING;

-- ── public.users ─────────────────────────────────────────────
INSERT INTO public.users
  (id, name, emoji, days_sober, initial_frequency, show_in_group_rank, fcm_token, start_date, day_info, auth_id, phone_number, adjust_token, email, sms_settings, notification_settings, logging_id, created_at, platform, last_smoked, your_why, custom_check_ins, content_info, program_breaks, appstack_id, appstack_attribution, peer_support_migrated, peer_support_migrated_at, timezone, app_version)
VALUES
  (
    '0a6c079b-5f79-4a21-ae4d-a9c2f7780991',
    'Goldie',
    '😁',
    NULL,
    NULL,
    NULL,
    'cziNK_0SckO_hOlTffoSGd:APA91bHbwENYeEKSrKLZYkGBl_L7G6012vYwTBiCK_VbDKGoAxHM8Fk9sP8O8n22XOqQVXCGxqTcmZGwvyFlsYMLHYVxzmi-q_4QKXHnJomezBB2UeRbRKg',
    NULL,
    '["2026-02-22", {"sober": true, "popInType": null, "loggedCheckIns": [{"id": "sober-dab", "timestamp": "2026-02-22T07:00:00.000", "completion": true, "distinctID": "7593AA02-0ADB-47FC-AEAD-11E5413470F5"}], "loggedSymptoms": [], "variableRewardType": null}]',
    '0a6c079b-5f79-4a21-ae4d-a9c2f7780991',
    NULL,
    NULL,
    'goldieclear30@gmail.com',
    NULL,
    '{"all": true, "name": "Notifications", "options": {"Group Notifications": true, "Health Notifications": false, "Message Notifications": false, "Check In Notifications": true, "Progress Notifications": true, "Community Notifications": true, "Achievement Notifications": false}}',
    '{3102D9DE-F79E-4D7D-B8DD-BE5E43D7CEAB}',
    '2026-02-22 06:32:42.846817+00',
    'ios',
    '2026-02-22 06:06:54.268+00',
    NULL,
    '[]',
    '{"2026-02-22": {"message_ids": [339, 344]}, "2026-02-23": {"message_ids": [345, 556]}, "2026-02-24": {"message_ids": [353, 358]}, "2026-02-25": {"message_ids": [367, 368]}, "2026-02-26": {"message_ids": [475]}, "2026-02-27": {"message_ids": [389, 393]}, "2026-02-28": {"message_ids": [395]}, "2026-03-01": {"message_ids": [400]}, "2026-03-02": {"message_ids": [406, 412]}, "2026-03-03": {"message_ids": [424]}, "2026-03-04": {"message_ids": [431]}, "2026-03-05": {"message_ids": [436, 444]}, "2026-03-06": {"message_ids": [445, 448]}, "2026-03-07": {"message_ids": [449]}, "2026-03-08": {"message_ids": [456, 460]}, "2026-03-09": {"message_ids": [462]}, "2026-03-10": {"message_ids": [468, 470]}, "2026-03-11": {"message_ids": [471]}, "2026-03-12": {"message_ids": [537]}, "2026-03-13": {"message_ids": [476, 478]}, "2026-03-14": {"message_ids": [483]}, "2026-03-15": {"message_ids": [488, 494]}, "2026-03-16": {"message_ids": [495, 496]}, "2026-03-17": {"message_ids": [499, 568]}, "2026-03-18": {"message_ids": [503]}, "2026-03-19": {"message_ids": [509]}, "2026-03-20": {"message_ids": [510, 512]}, "2026-03-21": {"message_ids": [513]}, "2026-03-22": {"message_ids": [520]}, "2026-03-23": {"message_ids": [524]}, "2026-03-24": {"message_ids": [525]}}',
    '[{"name": "Clear30", "type": "clear30", "start_date": "2026-02-22T05:00:00.000", "normative_feedback": {"sections": [{"content": [{"title": "Trigger Insight", "subtitle": "You\u2019ve clearly pinpointed why you smoke\u2014understanding these triggers makes your path forward easier."}, {"title": "Goal Awareness", "subtitle": "Your clear goal gives you a strong foundation for meaningful progress."}], "sectionTitle": "\ud83c\udf1f Strengths"}, {"content": [{"title": "Improving Emotional Coping Strategies", "subtitle": "You often turn to cannabis to manage tough emotions or stress. Developing healthier coping strategies could lead to lasting emotional balance."}, {"title": "Managing Boredom in Healthier Ways", "subtitle": "You often use cannabis to combat boredom. Exploring more fulfilling activities could naturally decrease reliance and enhance enjoyment."}], "sectionTitle": "\ud83c\udf31 Areas for Exploration"}], "scoreCards": [{"score": 87, "title": "Current Use \ud83c\udf43", "color1": "#FF416C", "color2": "#FF4B2B", "insight": "Your cannbis use is higher than 87% of young adults (18 - 25 year olds)."}, {"score": 75, "title": "Habit Strength \ud83d\udd04", "color1": "#5BB4A9", "color2": "#80C97A", "insight": "Your cannabis use feels automatic and consistent. Reflecting on these habits can help you shift toward choices that match the life you want to build. Your habit score is calculated based on the days you use and your triggers."}], "amountCards": [{"title": "\ud83d\udcb0 Financial Opportunity", "amount": "$21.95", "color1": "#5B9CF0", "color2": "#5BAEE6", "subtitle": "Estimated Monthly Savings:"}]}, "assessment_response_id": 1, "money_saved_adjustment": 0, "post_assessment_completed": false}]',
    '55D7CAC4-2626-4250-A9AA-4FE65CF0578D',
    '{"fbc": "fb.1.1771612209158.PAZXh0bgNhZW0BMABhZGlkAastQPGMJdBzcnRjBmFwcF9pZA8xMjQwMjQ1NzQyODc0MTQAAaclmSq6eZdftvQTequLXyJ6hVJ_e7LhYT6llig7ForXoTpEo2bgLCLijwgtMw_aem_WyfdaundR8YPBcR79m9erA.AQIBAQEB", "fbp": "fb.1.1771612209158.16216504.AQIBAQEB", "fbclid": "PAZXh0bgNhZW0BMABhZGlkAastQPGMJdBzcnRjBmFwcF9pZA8xMjQwMjQ1NzQyODc0MTQAAaclmSq6eZdftvQTequLXyJ6hVJ_e7LhYT6llig7ForXoTpEo2bgLCLijwgtMw_aem_WyfdaundR8YPBcR79m9erA", "appstack_ad": "[CC] 189.3_female_static", "appstack_id": "55D7CAC4-2626-4250-A9AA-4FE65CF0578D", "appstack_adset": "CC 4 | Feb 5th | Previous Winners", "appstack_campaign": "CONVERSION CAMP 4 | Feb 5th 2025", "appstack_adnetwork": "meta"}',
    'false',
    NULL,
    'America/New_York',
    '2.14.5'
  )
ON CONFLICT (id) DO UPDATE SET
  content_info = EXCLUDED.content_info,
  day_info     = EXCLUDED.day_info;