create schema if not exists "community";

create table "community"."post_tags" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "post_id" uuid,
    "tag_id" uuid,
    "updated_at" timestamp with time zone
);


alter table "community"."post_tags" enable row level security;

create table "community"."posts" (
    "id" uuid not null default gen_random_uuid(),
    "user_id" text,
    "title" character varying,
    "content_type" text,
    "body" text,
    "video_url" text,
    "view_count" bigint default '0'::bigint,
    "is_pinned" boolean,
    "is_hidden" boolean,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone
);


alter table "community"."posts" enable row level security;

create table "community"."tags" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "name" character varying,
    "updated_at" timestamp with time zone
);


alter table "community"."tags" enable row level security;

CREATE UNIQUE INDEX post_tags_pkey ON community.post_tags USING btree (id);

CREATE UNIQUE INDEX posts_pkey ON community.posts USING btree (id);

CREATE UNIQUE INDEX tags_pkey ON community.tags USING btree (id);

alter table "community"."post_tags" add constraint "post_tags_pkey" PRIMARY KEY using index "post_tags_pkey";

alter table "community"."posts" add constraint "posts_pkey" PRIMARY KEY using index "posts_pkey";

alter table "community"."tags" add constraint "tags_pkey" PRIMARY KEY using index "tags_pkey";

alter table "community"."post_tags" add constraint "post_tags_post_id_fkey" FOREIGN KEY (post_id) REFERENCES community.posts(id) not valid;

alter table "community"."post_tags" validate constraint "post_tags_post_id_fkey";

alter table "community"."post_tags" add constraint "post_tags_tag_id_fkey" FOREIGN KEY (tag_id) REFERENCES community.tags(id) not valid;

alter table "community"."post_tags" validate constraint "post_tags_tag_id_fkey";

alter table "community"."posts" add constraint "posts_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL not valid;

alter table "community"."posts" validate constraint "posts_user_id_fkey";


create table "community"."comments" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "post_id" uuid not null,
    "user_id" text not null,
    "body" text,
    "parent_comment_id" uuid
);


alter table "community"."comments" enable row level security;

alter table "community"."tags" alter column "name" set not null;

CREATE UNIQUE INDEX comments_pkey ON community.comments USING btree (id);

alter table "community"."comments" add constraint "comments_pkey" PRIMARY KEY using index "comments_pkey";

alter table "community"."comments" add constraint "comments_parent_comment_id_fkey" FOREIGN KEY (parent_comment_id) REFERENCES community.comments(id) not valid;

alter table "community"."comments" validate constraint "comments_parent_comment_id_fkey";

alter table "community"."comments" add constraint "comments_post_id_fkey" FOREIGN KEY (post_id) REFERENCES community.posts(id) ON DELETE CASCADE not valid;

alter table "community"."comments" validate constraint "comments_post_id_fkey";

alter table "community"."comments" add constraint "comments_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) not valid;

alter table "community"."comments" validate constraint "comments_user_id_fkey";


create table "community"."reactions" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" text,
    "post_id" uuid not null,
    "emoji" character varying not null
);


alter table "community"."reactions" enable row level security;

CREATE UNIQUE INDEX reactions_pkey ON community.reactions USING btree (id);

alter table "community"."reactions" add constraint "reactions_pkey" PRIMARY KEY using index "reactions_pkey";

alter table "community"."reactions" add constraint "reactions_post_id_fkey" FOREIGN KEY (post_id) REFERENCES community.posts(id) not valid;

alter table "community"."reactions" validate constraint "reactions_post_id_fkey";

alter table "community"."reactions" add constraint "reactions_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) not valid;

alter table "community"."reactions" validate constraint "reactions_user_id_fkey";


create table "community"."reported_posts" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone default now(),
    "user_id" text,
    "post_id" uuid,
    "is_flagged_by_llm" boolean default false
);


alter table "community"."reported_posts" enable row level security;

alter table "community"."posts" alter column "is_hidden" set default false;

alter table "community"."posts" alter column "is_pinned" set default false;

CREATE UNIQUE INDEX reported_posts_pkey ON community.reported_posts USING btree (id);

alter table "community"."reported_posts" add constraint "reported_posts_pkey" PRIMARY KEY using index "reported_posts_pkey";

alter table "community"."reported_posts" add constraint "reported_posts_post_id_fkey" FOREIGN KEY (post_id) REFERENCES community.posts(id) not valid;

alter table "community"."reported_posts" validate constraint "reported_posts_post_id_fkey";

alter table "community"."reported_posts" add constraint "reported_posts_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) not valid;

alter table "community"."reported_posts" validate constraint "reported_posts_user_id_fkey";


alter table "community"."posts" add column "is_flagged_by_llm" boolean default false;

alter table "community"."reported_posts" drop column "is_flagged_by_llm";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION community.set_post_visibility()
 RETURNS trigger
 SECURITY DEFINER
 LANGUAGE plpgsql
AS $function$BEGIN
    -- Count reported entries for the same post_id
    IF (SELECT COUNT(*) FROM reported_posts WHERE post_id = NEW.post_id) > 3 THEN
        -- Update the post to set is_hidden to TRUE
        UPDATE posts SET is_hidden = TRUE WHERE post_id = NEW.post_id;
    END IF;
    RETURN NEW;
END;$function$
;

CREATE TRIGGER reported_posts_trigger AFTER INSERT ON community.reported_posts FOR EACH ROW EXECUTE FUNCTION community.set_post_visibility();


CREATE UNIQUE INDEX tags_name_key ON community.tags USING btree (name);

alter table "community"."tags" add constraint "tags_name_key" UNIQUE using index "tags_name_key";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION community.create_post_with_tags(p_title text, p_content_type text, p_body text, p_video_url text, p_user_id text, p_tags text[] DEFAULT '{}'::text[])
 RETURNS uuid
 LANGUAGE plpgsql
AS $function$DECLARE
  v_post_id uuid;
  v_tag_id uuid;
  v_tag TEXT;
BEGIN
  -- Input validation
  IF p_title IS NULL OR p_content_type IS NULL THEN
    RAISE EXCEPTION 'Title and content_type are required fields';
  END IF;

  IF p_content_type NOT IN ('text', 'video') THEN
    RAISE EXCEPTION 'Invalid content_type. Must be either text or video';
  END IF;

  IF p_content_type = 'text' AND p_body IS NULL THEN
    RAISE EXCEPTION 'Body is required for text posts';
  END IF;

  IF p_content_type = 'video' AND p_video_url IS NULL THEN
    RAISE EXCEPTION 'Video URL is required for video posts';
  END IF;

  -- Log the start of the operation
  RAISE LOG 'Creating new post with title: %, content_type: %, user_id: %', p_title, p_content_type, p_user_id;

  -- First create the post
  INSERT INTO community.posts (
    title,
    content_type,
    body,
    video_url,
    user_id,
    is_pinned,
    is_hidden,
    created_at,
    updated_at
  ) VALUES (
    p_title,
    p_content_type,
    p_body,
    p_video_url,
    p_user_id,
    false,
    false,
    NOW(),
    NULL
  ) RETURNING id INTO v_post_id;

  -- Log successful post creation
  RAISE LOG 'Successfully created post with ID: %', v_post_id;

  -- Then handle each tag
  IF array_length(p_tags, 1) > 0 THEN
    FOREACH v_tag IN ARRAY p_tags
    LOOP
      -- Log tag processing
      RAISE LOG 'Processing tag: %', v_tag;

      -- Try to find existing tag or create new one
      INSERT INTO community.tags (name, created_at)
      VALUES (v_tag, NOW())
      ON CONFLICT (name) 
      DO UPDATE SET name = EXCLUDED.name
      RETURNING id INTO v_tag_id;

      -- Create post_tag connection
      INSERT INTO community.post_tags (post_id, tag_id, created_at)
      VALUES (v_post_id, v_tag_id, NOW());

      -- Log successful tag association
      RAISE LOG 'Associated tag % (ID: %) with post %', v_tag, v_tag_id, v_post_id;
    END LOOP;
  END IF;

  RETURN v_post_id;
EXCEPTION
  WHEN others THEN
    -- Log any errors that occur
    RAISE LOG 'Error in create_post_with_tags: %', SQLERRM;
    RAISE EXCEPTION 'An error occurred while creating the post: %', SQLERRM;
END;$function$
;

grant delete on table "community"."comments" to "anon";

grant insert on table "community"."comments" to "anon";

grant references on table "community"."comments" to "anon";

grant select on table "community"."comments" to "anon";

grant trigger on table "community"."comments" to "anon";

grant truncate on table "community"."comments" to "anon";

grant update on table "community"."comments" to "anon";

grant delete on table "community"."comments" to "authenticated";

grant insert on table "community"."comments" to "authenticated";

grant references on table "community"."comments" to "authenticated";

grant select on table "community"."comments" to "authenticated";

grant trigger on table "community"."comments" to "authenticated";

grant truncate on table "community"."comments" to "authenticated";

grant update on table "community"."comments" to "authenticated";

grant delete on table "community"."post_tags" to "anon";

grant insert on table "community"."post_tags" to "anon";

grant references on table "community"."post_tags" to "anon";

grant select on table "community"."post_tags" to "anon";

grant trigger on table "community"."post_tags" to "anon";

grant truncate on table "community"."post_tags" to "anon";

grant update on table "community"."post_tags" to "anon";

grant delete on table "community"."post_tags" to "authenticated";

grant insert on table "community"."post_tags" to "authenticated";

grant references on table "community"."post_tags" to "authenticated";

grant select on table "community"."post_tags" to "authenticated";

grant trigger on table "community"."post_tags" to "authenticated";

grant truncate on table "community"."post_tags" to "authenticated";

grant update on table "community"."post_tags" to "authenticated";

grant delete on table "community"."posts" to "anon";

grant insert on table "community"."posts" to "anon";

grant references on table "community"."posts" to "anon";

grant select on table "community"."posts" to "anon";

grant trigger on table "community"."posts" to "anon";

grant truncate on table "community"."posts" to "anon";

grant update on table "community"."posts" to "anon";

grant delete on table "community"."posts" to "authenticated";

grant insert on table "community"."posts" to "authenticated";

grant references on table "community"."posts" to "authenticated";

grant select on table "community"."posts" to "authenticated";

grant trigger on table "community"."posts" to "authenticated";

grant truncate on table "community"."posts" to "authenticated";

grant update on table "community"."posts" to "authenticated";

grant delete on table "community"."reactions" to "anon";

grant insert on table "community"."reactions" to "anon";

grant references on table "community"."reactions" to "anon";

grant select on table "community"."reactions" to "anon";

grant trigger on table "community"."reactions" to "anon";

grant truncate on table "community"."reactions" to "anon";

grant update on table "community"."reactions" to "anon";

grant delete on table "community"."reactions" to "authenticated";

grant insert on table "community"."reactions" to "authenticated";

grant references on table "community"."reactions" to "authenticated";

grant select on table "community"."reactions" to "authenticated";

grant trigger on table "community"."reactions" to "authenticated";

grant truncate on table "community"."reactions" to "authenticated";

grant update on table "community"."reactions" to "authenticated";

grant delete on table "community"."reported_posts" to "anon";

grant insert on table "community"."reported_posts" to "anon";

grant references on table "community"."reported_posts" to "anon";

grant select on table "community"."reported_posts" to "anon";

grant trigger on table "community"."reported_posts" to "anon";

grant truncate on table "community"."reported_posts" to "anon";

grant update on table "community"."reported_posts" to "anon";

grant delete on table "community"."reported_posts" to "authenticated";

grant insert on table "community"."reported_posts" to "authenticated";

grant references on table "community"."reported_posts" to "authenticated";

grant select on table "community"."reported_posts" to "authenticated";

grant trigger on table "community"."reported_posts" to "authenticated";

grant truncate on table "community"."reported_posts" to "authenticated";

grant update on table "community"."reported_posts" to "authenticated";

grant delete on table "community"."tags" to "anon";

grant insert on table "community"."tags" to "anon";

grant references on table "community"."tags" to "anon";

grant select on table "community"."tags" to "anon";

grant trigger on table "community"."tags" to "anon";

grant truncate on table "community"."tags" to "anon";

grant update on table "community"."tags" to "anon";

grant delete on table "community"."tags" to "authenticated";

grant insert on table "community"."tags" to "authenticated";

grant references on table "community"."tags" to "authenticated";

grant select on table "community"."tags" to "authenticated";

grant trigger on table "community"."tags" to "authenticated";

grant truncate on table "community"."tags" to "authenticated";

grant update on table "community"."tags" to "authenticated";

create policy "comments"
on "community"."comments"
as permissive
for all
to anon
using (true);


create policy "post_tags"
on "community"."post_tags"
as permissive
for all
to anon
using (true);


create policy "Posts"
on "community"."posts"
as permissive
for all
to anon
using (true);


create policy "reactions"
on "community"."reactions"
as permissive
for all
to public
using (true);


create policy "reported_posts"
on "community"."reported_posts"
as permissive
for all
to anon
using (true);


create policy "tags"
on "community"."tags"
as permissive
for all
to anon
using (true);



set check_function_bodies = off;

CREATE OR REPLACE FUNCTION community.increment_view_count(post_id uuid)
 RETURNS void
 SECURITY DEFINER
 LANGUAGE plpgsql
AS $function$
BEGIN
    UPDATE community.posts 
    SET view_count = view_count + 1 
    WHERE id = post_id;
END;
$function$
;


-- Create the tag_type enum
CREATE TYPE community.tag_type AS ENUM ('program', 'day', 'event', 'general');

-- Add the tag_type column to the tags table with a default value
ALTER TABLE community.tags ADD COLUMN type community.tag_type NOT NULL DEFAULT 'general';

-- Add an index on the type column for better query performance
CREATE INDEX tags_type_idx ON community.tags(type);

-- Comment on the enum type for documentation
COMMENT ON TYPE community.tag_type IS 'Categories of tags: program (for program-specific tags), day (for day-specific content), event (for events), and general (for miscellaneous tags)'; -- Add color column with hex color validation
ALTER TABLE community.tags ADD COLUMN color text;

-- Add check constraint to ensure valid hex color format (e.g., #FF0000 or #ff0000)
ALTER TABLE community.tags 
    ADD CONSTRAINT valid_hex_color 
    CHECK (color IS NULL OR color ~ '^#[0-9A-Fa-f]{6}$');

-- Add comment for the color column
COMMENT ON COLUMN community.tags.color IS 'Hex color code for the tag (e.g., #FF0000 for red)';

-- Set default colors based on tag type
UPDATE community.tags 
SET color = CASE type
    WHEN 'program' THEN '#4A90E2'  -- Blue
    WHEN 'day' THEN '#7ED321'      -- Green
    WHEN 'event' THEN '#F5A623'    -- Orange
    WHEN 'general' THEN '#9B9B9B'  -- Gray
END
WHERE color IS NULL; -- Create deleted_posts_log table first
create table IF NOT EXISTS community.deleted_posts_log (
    id uuid NOT NULL,
    user_id text NOT NULL,
    title text NOT NULL,
    deleted_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_by_user_id text REFERENCES public.users(id),
    deleted_by_admin boolean DEFAULT false,
    metadata jsonb -- Store additional info if needed
);

-- Add indexes to optimize queries
CREATE INDEX IF NOT EXISTS idx_comments_parent_comment_id 
ON community.comments(parent_comment_id);

CREATE INDEX IF NOT EXISTS idx_posts_user_id 
ON community.posts(user_id);

-- Add RPC function for post deletion
CREATE OR REPLACE FUNCTION community.delete_post(post_id uuid)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = community, public
AS $$
DECLARE
    v_auth_id uuid;
    v_user_id text;
    v_post_user_id text;
    v_is_admin boolean;
BEGIN
    -- Get the auth_id of the authenticated user
    v_auth_id := auth.uid();
    
    -- Check if user is authenticated
    IF v_auth_id IS NULL THEN
        RAISE EXCEPTION 'Authentication required';
    END IF;

    -- Get the user_id from public.users using auth_id
    SELECT u.id, EXISTS(SELECT 1 FROM public.admins a WHERE a.auth_id = u.auth_id)
    INTO v_user_id, v_is_admin
    FROM public.users u
    WHERE u.auth_id = v_auth_id;

    -- If no user found in public.users, raise an exception
    IF v_user_id IS NULL THEN
        RAISE EXCEPTION 'User profile not found. Auth ID: %', v_auth_id;
    END IF;

    -- Get the post's user_id
    SELECT user_id INTO v_post_user_id
    FROM community.posts
    WHERE id = post_id;

    -- Check if post exists
    IF v_post_user_id IS NULL THEN
        RAISE EXCEPTION 'Post not found';
    END IF;

    -- Check if user is the post owner or an admin
    IF v_post_user_id != v_user_id AND NOT v_is_admin THEN
        RAISE EXCEPTION 'Only the post owner or admin can delete the post';
    END IF;

    -- Delete all reactions for the post
    DELETE FROM community.reactions r
    WHERE r.post_id = delete_post.post_id;

    -- Delete all post tags
    DELETE FROM community.post_tags pt
    WHERE pt.post_id = delete_post.post_id;

    -- Delete all reported posts entries
    DELETE FROM community.reported_posts rp
    WHERE rp.post_id = delete_post.post_id;

    -- Delete all comments and their replies using recursive CTE
    WITH RECURSIVE comment_tree AS (
        -- Base case: get all direct comments for the post
        SELECT c.id
        FROM community.comments c
        WHERE c.post_id = delete_post.post_id
        
        UNION ALL
        
        -- Recursive case: get all replies to comments
        SELECT c.id
        FROM community.comments c
        INNER JOIN comment_tree ct ON c.parent_comment_id = ct.id
    )
    DELETE FROM community.comments c
    WHERE c.id IN (SELECT id FROM comment_tree)
    OR c.post_id = delete_post.post_id;

    -- Log additional information about who deleted the post
    INSERT INTO community.deleted_posts_log (
        id, 
        user_id, 
        title, 
        metadata,
        deleted_by_user_id,
        deleted_by_admin
    )
    SELECT 
        p.id,
        p.user_id,
        p.title,
        jsonb_build_object(
            'content_type', p.content_type,
            'view_count', p.view_count,
            'is_pinned', p.is_pinned,
            'is_hidden', p.is_hidden,
            'is_flagged_by_llm', p.is_flagged_by_llm,
            'deleted_by', v_user_id,
            'was_admin_deletion', v_is_admin
        ),
        v_user_id,
        v_is_admin
    FROM community.posts p
    WHERE p.id = delete_post.post_id;

    -- Finally delete the post itself
    DELETE FROM community.posts p
    WHERE p.id = delete_post.post_id;

    RETURN true;
END;
$$;

-- Add comment for the function
COMMENT ON FUNCTION community.delete_post IS 'Deletes a post and all its related data (comments, reactions, tags, etc.). Only the post owner or admin can delete posts.';

-- Grant execute permission to authenticated users
GRANT EXECUTE ON FUNCTION community.delete_post TO authenticated;

-- Enable RLS on deleted_posts_log
ALTER TABLE community.deleted_posts_log ENABLE ROW LEVEL SECURITY;

-- Add policy for deleted_posts_log
CREATE POLICY "Only admins can view deleted posts log"
    ON community.deleted_posts_log
    FOR ALL
    TO authenticated
    USING (public.admin_check()); -- Grant schema usage to all roles
GRANT USAGE ON SCHEMA community TO anon;
GRANT USAGE ON SCHEMA community TO authenticated;
GRANT USAGE ON SCHEMA community TO authenticator;

-- Grant base SELECT permissions on all community tables
GRANT SELECT ON community.posts TO anon;
GRANT SELECT ON community.post_tags TO anon;
GRANT SELECT ON community.tags TO anon;
GRANT SELECT ON community.reactions TO anon;
GRANT SELECT ON community.comments TO anon;
GRANT SELECT ON community.reported_posts TO anon;

GRANT SELECT ON community.posts TO authenticated;
GRANT SELECT ON community.post_tags TO authenticated;
GRANT SELECT ON community.tags TO authenticated;
GRANT SELECT ON community.reactions TO authenticated;
GRANT SELECT ON community.comments TO authenticated;
GRANT SELECT ON community.reported_posts TO authenticated;

GRANT SELECT ON community.posts TO authenticator;
GRANT SELECT ON community.post_tags TO authenticator;
GRANT SELECT ON community.tags TO authenticator;
GRANT SELECT ON community.reactions TO authenticator;
GRANT SELECT ON community.comments TO authenticator;
GRANT SELECT ON community.reported_posts TO authenticator;

-- Grant additional permissions for specific operations (to authenticated and authenticator)
GRANT INSERT, UPDATE ON community.posts TO authenticated;
GRANT INSERT, DELETE ON community.reactions TO authenticated;
GRANT INSERT ON community.comments TO authenticated;
GRANT INSERT ON community.post_tags TO authenticated;
GRANT INSERT ON community.reported_posts TO authenticated;

GRANT INSERT, UPDATE ON community.posts TO authenticator;
GRANT INSERT, DELETE ON community.reactions TO authenticator;
GRANT INSERT ON community.comments TO authenticator;
GRANT INSERT ON community.post_tags TO authenticator;
GRANT INSERT ON community.reported_posts TO authenticator;

-- Grant USAGE on sequences (needed for INSERT operations)
GRANT USAGE ON ALL SEQUENCES IN SCHEMA community TO authenticated;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA community TO authenticator;

-- Add comment for documentation
COMMENT ON SCHEMA community IS 'Schema for community-related features including posts, comments, reactions, and tags. Anonymous users can view content, while authenticated users can create and update their own content.';

drop policy "Posts" on "community"."posts";

create policy "Posts"
on "community"."posts"
as permissive
for all
to public
using (true);



drop policy "comments" on "community"."comments";

drop policy "post_tags" on "community"."post_tags";

drop policy "reported_posts" on "community"."reported_posts";

drop policy "tags" on "community"."tags";

create policy "comments"
on "community"."comments"
as permissive
for all
to public
using (true);


create policy "post_tags"
on "community"."post_tags"
as permissive
for all
to public
using (true);


create policy "reported_posts"
on "community"."reported_posts"
as permissive
for all
to public
using (true);


create policy "tags"
on "community"."tags"
as permissive
for all
to public
using (true);



-- Main function to get filtered posts with range-based pagination
CREATE OR REPLACE FUNCTION community.get_filtered_posts(
    start_range int,                       -- Start of range (inclusive)
    end_range int,                         -- End of range (inclusive)
    tag_ids uuid[] DEFAULT NULL,           -- Array of tag IDs to filter by
    only_my_posts boolean DEFAULT false    -- Whether to show only the authenticated user's posts
)
RETURNS jsonb                              -- Return single JSON object
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = community, public
AS $$
DECLARE
    v_user_id text;
    v_total_count bigint;
    v_result jsonb;
BEGIN
    -- Get authenticated user's ID if only_my_posts is true
    IF only_my_posts THEN
        SELECT u.id INTO v_user_id
        FROM users u
        WHERE u.auth_id = auth.uid();

        IF v_user_id IS NULL THEN
            RAISE EXCEPTION 'User not found';
        END IF;
    END IF;

    -- Get total count first
    WITH base_query AS (
        SELECT DISTINCT p.id
        FROM community.posts p
        LEFT JOIN community.post_tags pt ON pt.post_id = p.id
        WHERE NOT p.is_hidden
        AND (v_user_id IS NULL OR p.user_id = v_user_id)
        AND (
            tag_ids IS NULL 
            OR array_length(tag_ids, 1) IS NULL 
            OR pt.tag_id = ANY(tag_ids)
        )
    )
    SELECT COUNT(*) INTO v_total_count FROM base_query;

    -- Get posts data and return as single JSON object
    WITH filtered_posts AS (
        SELECT DISTINCT p.*
        FROM community.posts p
        LEFT JOIN community.post_tags pt ON pt.post_id = p.id
        WHERE NOT p.is_hidden
        AND (CASE WHEN only_my_posts THEN p.user_id = v_user_id ELSE true END)
        AND (
            tag_ids IS NULL 
            OR array_length(tag_ids, 1) IS NULL 
            OR pt.tag_id = ANY(tag_ids)
        )
        ORDER BY p.is_pinned DESC, p.created_at DESC
        OFFSET start_range LIMIT (end_range - start_range + 1)
    ),
    post_data AS (
        SELECT 
            p.id,
            p.user_id,
            p.title,
            p.content_type,
            p.body,
            p.video_url,
            p.is_pinned,
            p.is_hidden,
            p.is_flagged_by_llm,
            p.view_count,
            p.created_at,
            p.updated_at,
            (
                SELECT jsonb_agg(
                    jsonb_build_object(
                        'tag', jsonb_build_object(
                            'id', t.id,
                            'name', t.name
                        )
                    )
                )
                FROM community.post_tags pt
                JOIN community.tags t ON t.id = pt.tag_id
                WHERE pt.post_id = p.id
            ) as post_tags,
            (
                SELECT jsonb_agg(
                    jsonb_build_object(
                        'emoji', r.emoji,
                        'user_id', r.user_id
                    )
                )
                FROM community.reactions r
                WHERE r.post_id = p.id
            ) as reactions,
            (
                SELECT COUNT(*)
                FROM community.comments c
                WHERE c.post_id = p.id
            ) as comments_count
        FROM filtered_posts p
    )
    SELECT jsonb_build_object(
        'data', COALESCE(jsonb_agg(to_jsonb(post_data.*)), '[]'::jsonb),
        'total_count', v_total_count
    ) INTO v_result
    FROM post_data;

    RETURN v_result;
END;
$$;

-- Grant execute permissions
GRANT EXECUTE ON FUNCTION community.get_filtered_posts TO anon;
GRANT EXECUTE ON FUNCTION community.get_filtered_posts TO authenticated;
GRANT EXECUTE ON FUNCTION community.get_filtered_posts TO authenticator;

-- Add helpful comment
COMMENT ON FUNCTION community.get_filtered_posts IS 'Fetches filtered posts with range-based pagination, tag filtering, and optional my-posts-only filter. Returns a single JSON object with posts data and total count.'; -- Create enums for activity types
CREATE TYPE community.activity_entity_type AS ENUM (
    'post',
    'comment'
);

CREATE TYPE community.activity_action AS ENUM (
    'created',
    'commented',
    'replied'
);

-- Create activities table
create table community.activities (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    actor_id text NOT NULL REFERENCES public.users(id),
    recipient_id text REFERENCES public.users(id),
    entity_type community.activity_entity_type NOT NULL,
    entity_id uuid NOT NULL,
    action community.activity_action NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    is_read boolean DEFAULT false NOT NULL
);

-- Add indexes for better query performance
CREATE INDEX idx_activities_recipient_unread ON community.activities(recipient_id) WHERE NOT is_read;
CREATE INDEX idx_activities_actor ON community.activities(actor_id);
CREATE INDEX idx_activities_entity ON community.activities(entity_type, entity_id);
CREATE INDEX idx_activities_created_at ON community.activities(created_at DESC);

-- Create function for post activities
CREATE FUNCTION community.create_post_activity()
RETURNS trigger AS $$
BEGIN
    INSERT INTO community.activities (
        actor_id,
        entity_type,
        entity_id,
        action
    ) VALUES (
        NEW.user_id,
        'post'::community.activity_entity_type,
        NEW.id,
        'created'::community.activity_action
    );
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Create function for comment activities
CREATE FUNCTION community.create_comment_activity()
RETURNS trigger AS $$
DECLARE
    v_post_author_id text;
    v_parent_comment_author_id text;
BEGIN
    -- Don't create activity if the actor would be the recipient
    IF NEW.parent_comment_id IS NULL THEN
        -- Direct comment on post
        SELECT user_id INTO v_post_author_id
        FROM community.posts
        WHERE id = NEW.post_id;

        -- Only create activity if the commenter is not the post author
        IF NEW.user_id <> v_post_author_id THEN
            INSERT INTO community.activities (
                actor_id,
                recipient_id,
                entity_type,
                entity_id,
                action
            ) VALUES (
                NEW.user_id,
                v_post_author_id,
                'comment'::community.activity_entity_type,
                NEW.id,
                'commented'::community.activity_action
            );
        END IF;
    ELSE
        -- Reply to comment
        SELECT user_id INTO v_parent_comment_author_id
        FROM community.comments
        WHERE id = NEW.parent_comment_id;

        -- Only create activity if the replier is not the parent comment author
        IF NEW.user_id <> v_parent_comment_author_id THEN
            INSERT INTO community.activities (
                actor_id,
                recipient_id,
                entity_type,
                entity_id,
                action
            ) VALUES (
                NEW.user_id,
                v_parent_comment_author_id,
                'comment'::community.activity_entity_type,
                NEW.id,
                'replied'::community.activity_action
            );
        END IF;
    END IF;

    RETURN NEW;
EXCEPTION
    WHEN OTHERS THEN
        -- Log error but don't prevent comment creation
        RAISE WARNING 'Error creating activity for comment %: %', NEW.id, SQLERRM;
        RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Create triggers
CREATE TRIGGER after_post_created
    AFTER INSERT ON community.posts
    FOR EACH ROW
    EXECUTE FUNCTION community.create_post_activity();

CREATE TRIGGER after_comment_created
    AFTER INSERT ON community.comments
    FOR EACH ROW
    EXECUTE FUNCTION community.create_comment_activity();

-- Add RLS policies
ALTER TABLE community.activities ENABLE ROW LEVEL SECURITY;

-- Users can see activities where they are the recipient or actor
CREATE POLICY "Users can see their own activities"
    ON community.activities
    FOR ALL
    USING (
        actor_id = auth.uid()::text
        OR recipient_id = auth.uid()::text
        OR recipient_id IS NULL  -- Allow viewing broadcast activities (post creations)
    );

-- Grant permissions
GRANT SELECT ON community.activities TO authenticated;
GRANT SELECT ON community.activities TO anon;

-- Add helpful comments
COMMENT ON TABLE community.activities IS 'Stores activity events for posts and comments';
COMMENT ON COLUMN community.activities.entity_type IS 'Type of entity this activity relates to (post or comment)';
COMMENT ON COLUMN community.activities.entity_id IS 'ID of the related entity (post_id or comment_id)';
COMMENT ON COLUMN community.activities.action IS 'Type of action (created, commented, replied)';
COMMENT ON COLUMN community.activities.actor_id IS 'User who performed the action';
COMMENT ON COLUMN community.activities.recipient_id IS 'User who should be notified of this activity (null for broadcast activities)'; set check_function_bodies = off;

CREATE OR REPLACE FUNCTION community.get_filtered_posts(start_range integer, end_range integer, tag_ids uuid[] DEFAULT NULL::uuid[], only_my_posts boolean DEFAULT false)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'community', 'public'
AS $function$DECLARE
    v_user_id text;
    v_total_count bigint;
    v_result jsonb;
BEGIN
    -- Get authenticated user's ID if only_my_posts is true
    IF only_my_posts THEN
        SELECT u.id INTO v_user_id
        FROM users u
        WHERE u.auth_id = auth.uid();

        IF v_user_id IS NULL THEN
            RAISE EXCEPTION 'User not found';
        END IF;
    END IF;

    -- Get total count first
    WITH base_query AS (
        SELECT DISTINCT p.id
        FROM community.posts p
        LEFT JOIN community.post_tags pt ON pt.post_id = p.id
        WHERE NOT p.is_hidden
        AND (v_user_id IS NULL OR p.user_id = v_user_id)
        AND (
            tag_ids IS NULL 
            OR array_length(tag_ids, 1) IS NULL 
            OR pt.tag_id = ANY(tag_ids)
        )
    )
    SELECT COUNT(*) INTO v_total_count FROM base_query;

    -- Get posts data and return as single JSON object
    WITH filtered_posts AS (
        SELECT DISTINCT p.*
        FROM community.posts p
        LEFT JOIN community.post_tags pt ON pt.post_id = p.id
        WHERE NOT p.is_hidden
        AND (CASE WHEN only_my_posts THEN p.user_id = v_user_id ELSE true END)
        AND (
            tag_ids IS NULL 
            OR array_length(tag_ids, 1) IS NULL 
            OR pt.tag_id = ANY(tag_ids)
        )
        ORDER BY p.is_pinned DESC, p.created_at DESC
        OFFSET start_range LIMIT (end_range - start_range + 1)
    ),
    post_data AS (
        SELECT 
            p.id,
            p.user_id,
            p.title,
            p.content_type,
            p.body,
            p.video_url,
            p.is_pinned,
            p.is_hidden,
            p.is_flagged_by_llm,
            p.view_count,
            p.created_at,
            p.updated_at,
            (
                SELECT jsonb_agg(
                    jsonb_build_object(
                        'tag', jsonb_build_object(
                            'id', t.id,
                            'name', t.name,
                            'type', t.type,
                            'color', t.color
                        )
                    )
                )
                FROM community.post_tags pt
                JOIN community.tags t ON t.id = pt.tag_id
                WHERE pt.post_id = p.id
            ) as post_tags,
            (
                SELECT jsonb_agg(
                    jsonb_build_object(
                        'emoji', r.emoji,
                        'user_id', r.user_id,
                        'post_id', r.post_id
                    )
                )
                FROM community.reactions r
                WHERE r.post_id = p.id
            ) as reactions,
            (
                SELECT COUNT(*)
                FROM community.comments c
                WHERE c.post_id = p.id
            ) as comments_count
        FROM filtered_posts p
    )
    SELECT jsonb_build_object(
        'data', COALESCE(jsonb_agg(to_jsonb(post_data.*)), '[]'::jsonb),
        'total_count', v_total_count
    ) INTO v_result
    FROM post_data;

    RETURN v_result;
END;$function$
;


create policy "Public policy"
on "public"."users"
as permissive
for select
to public
using (true);



-- Add RPC function for getting activity feed
CREATE OR REPLACE FUNCTION community.get_activity_feed(
    start_range int,                    -- Start of range (inclusive)
    end_range int                       -- End of range (inclusive)
)
RETURNS TABLE (
    id uuid,
    created_at timestamptz,
    is_read boolean,
    message text,
    entity_type community.activity_entity_type,
    entity_id uuid,
    post_id uuid,
    action community.activity_action
) 
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = community, public
AS $$
DECLARE
    v_user_id text;
BEGIN
    -- Get the authenticated user's ID
    SELECT u.id INTO v_user_id
    FROM public.users u
    WHERE u.auth_id = auth.uid();

    IF v_user_id IS NULL THEN
        RAISE EXCEPTION 'User not found';
    END IF;

    RETURN QUERY
    SELECT 
        a.id,
        a.created_at,
        a.is_read,
        CASE 
            WHEN a.action = 'created' THEN 
                CASE 
                    WHEN a.actor_id = a.recipient_id THEN 'You created a new post "' || p.title || '"'
                    ELSE actor.name || ' created a new post "' || p.title || '"'
                END
            WHEN a.action = 'commented' THEN
                CASE 
                    WHEN a.actor_id = a.recipient_id THEN 'You commented on your post saying "' || c.body || '"'
                    ELSE actor.name || ' commented on your post saying "' || c.body || '"'
                END
            WHEN a.action = 'replied' THEN
                CASE 
                    WHEN a.actor_id = a.recipient_id THEN 'You replied to your comment saying "' || c.body || '"'
                    ELSE actor.name || ' replied to your comment saying "' || c.body || '"'
                END
        END,
        a.entity_type,
        a.entity_id,
        COALESCE(c.post_id, p.id) as post_id,
        a.action
    FROM community.activities a
    JOIN public.users actor ON actor.id = a.actor_id
    LEFT JOIN community.posts p ON 
        (a.entity_type = 'post' AND a.entity_id = p.id)
    LEFT JOIN community.comments c ON 
        (a.entity_type = 'comment' AND a.entity_id = c.id)
    WHERE a.recipient_id = v_user_id
    ORDER BY a.created_at DESC
    OFFSET start_range LIMIT (end_range - start_range + 1);
END;
$$;

-- Grant execute permissions
GRANT EXECUTE ON FUNCTION community.get_activity_feed TO authenticated;

-- Add helpful comment
COMMENT ON FUNCTION community.get_activity_feed IS 'Returns paginated activity feed for the authenticated user with formatted messages'; -- Drop existing trigger and function
DROP TRIGGER IF EXISTS after_post_created ON community.posts;
DROP FUNCTION IF EXISTS community.create_post_activity();

-- Recreate function with recipient_id
CREATE FUNCTION community.create_post_activity()
RETURNS trigger AS $$
BEGIN
    INSERT INTO community.activities (
        actor_id,
        recipient_id,      -- Adding recipient_id: user sees their own post creation
        entity_type,
        entity_id,
        action
    ) VALUES (
        NEW.user_id,
        NEW.user_id,      -- Same user is both actor and recipient
        'post'::community.activity_entity_type,
        NEW.id,
        'created'::community.activity_action
    );
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Recreate trigger
CREATE TRIGGER after_post_created
    AFTER INSERT ON community.posts
    FOR EACH ROW
    EXECUTE FUNCTION community.create_post_activity();

-- Add helpful comment
COMMENT ON FUNCTION community.create_post_activity IS 'Creates an activity record when a post is created, setting the creator as both actor and recipient'; -- Grant schema usage
GRANT USAGE ON SCHEMA community TO authenticated;

-- Grant table permissions
GRANT SELECT, UPDATE ON community.activities TO authenticated;

-- Update RLS policy
DROP POLICY IF EXISTS "Users can see their own activities" ON community.activities;
CREATE POLICY "Users can see their own activities"
    ON community.activities
    FOR ALL
    USING (
        actor_id = auth.uid()::text
        OR recipient_id = auth.uid()::text
    );



-- This migration adds deletion activity tracking to the existing activity system
-- It builds upon:
-- 1. migrations/20250221113136_add_activities.sql - which created the activities table and initial triggers
-- 2. migrations/20250207000002_add_delete_post_rpc.sql - which created the deleted_posts_log table
-- 3. migrations/20250224064339_add_activity_feed_rpc.sql - which created the get_activity_feed function

-- Add 'deleted' action to the enum
ALTER TYPE community.activity_action ADD VALUE IF NOT EXISTS 'deleted' AFTER 'replied';

-- Create function for post deletion activities
CREATE OR REPLACE FUNCTION community.create_post_deletion_activity()
RETURNS trigger AS $$
BEGIN
    -- Create activity for the post author (they deleted their own post)
    INSERT INTO community.activities (
        actor_id,
        recipient_id,
        entity_type,
        entity_id,
        action
    ) VALUES (
        OLD.user_id,
        OLD.user_id,
        'post'::community.activity_entity_type,
        OLD.id,
        'deleted'::community.activity_action
    );
    
    -- Note: The post is already being logged in deleted_posts_log by the delete_post RPC
    
    RETURN OLD;
EXCEPTION
    WHEN OTHERS THEN
        -- Log error but don't prevent post deletion
        RAISE WARNING 'Error creating deletion activity for post %: %', OLD.id, SQLERRM;
        RETURN OLD;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Create function for comment deletion activities
CREATE OR REPLACE FUNCTION community.create_comment_deletion_activity()
RETURNS trigger AS $$
DECLARE
    v_post_author_id text;
    v_post_title text;
BEGIN
    -- Get post information
    SELECT p.user_id, p.title INTO v_post_author_id, v_post_title
    FROM community.posts p
    WHERE p.id = OLD.post_id;
    
    -- Create activity for the comment author (they deleted their own comment)
    INSERT INTO community.activities (
        actor_id,
        recipient_id,
        entity_type,
        entity_id,
        action
    ) VALUES (
        OLD.user_id,
        OLD.user_id,
        'comment'::community.activity_entity_type,
        OLD.id,
        'deleted'::community.activity_action
    );
    
    -- If the comment author is not the post author, notify the post author
    IF OLD.user_id <> v_post_author_id THEN
        INSERT INTO community.activities (
            actor_id,
            recipient_id,
            entity_type,
            entity_id,
            action
        ) VALUES (
            OLD.user_id,
            v_post_author_id,
            'comment'::community.activity_entity_type,
            OLD.id,
            'deleted'::community.activity_action
        );
    END IF;
    
    RETURN OLD;
EXCEPTION
    WHEN OTHERS THEN
        -- Log error but don't prevent comment deletion
        RAISE WARNING 'Error creating deletion activity for comment %: %', OLD.id, SQLERRM;
        RETURN OLD;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Create triggers
DROP TRIGGER IF EXISTS before_post_deleted ON community.posts;
CREATE TRIGGER before_post_deleted
    BEFORE DELETE ON community.posts
    FOR EACH ROW
    EXECUTE FUNCTION community.create_post_deletion_activity();

DROP TRIGGER IF EXISTS before_comment_deleted ON community.comments;
CREATE TRIGGER before_comment_deleted
    BEFORE DELETE ON community.comments
    FOR EACH ROW
    EXECUTE FUNCTION community.create_comment_deletion_activity();

-- Update the existing activity feed RPC to handle deletion messages
-- We're only adding the 'deleted' case to the CASE statement, not recreating the entire function
CREATE OR REPLACE FUNCTION community.get_activity_feed(
    start_range int,
    end_range int
)
RETURNS TABLE (
    id uuid,
    created_at timestamptz,
    is_read boolean,
    message text,
    entity_type community.activity_entity_type,
    entity_id uuid,
    post_id uuid,
    action community.activity_action
) 
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = community, public
AS $$
DECLARE
    v_user_id text;
BEGIN
    -- Get the authenticated user's ID
    SELECT u.id INTO v_user_id
    FROM public.users u
    WHERE u.auth_id = auth.uid();

    IF v_user_id IS NULL THEN
        RAISE EXCEPTION 'User not found';
    END IF;

    RETURN QUERY
    WITH post_titles AS (
        -- Get titles for both existing and deleted posts
        SELECT 
            p.id AS post_id,
            p.title AS title
        FROM community.posts p
        UNION ALL
        SELECT 
            dl.id AS post_id,
            dl.title AS title
        FROM community.deleted_posts_log dl
    )
    SELECT 
        a.id,
        a.created_at,
        a.is_read,
        CASE 
            WHEN a.action = 'created' THEN 
                CASE 
                    WHEN a.actor_id = a.recipient_id THEN 
                        'You created a new post "' || 
                        COALESCE(
                            (SELECT pt.title FROM post_titles pt WHERE pt.post_id = a.entity_id),
                            'Untitled'
                        ) || '"'
                    ELSE 
                        actor.name || ' created a new post "' || 
                        COALESCE(
                            (SELECT pt.title FROM post_titles pt WHERE pt.post_id = a.entity_id),
                            'Untitled'
                        ) || '"'
                END
            WHEN a.action = 'commented' THEN
                CASE 
                    WHEN a.actor_id = a.recipient_id THEN 'You commented on your post saying "' || c.body || '"'
                    ELSE actor.name || ' commented on your post saying "' || c.body || '"'
                END
            WHEN a.action = 'replied' THEN
                CASE 
                    WHEN a.actor_id = a.recipient_id THEN 'You replied to your comment saying "' || c.body || '"'
                    ELSE actor.name || ' replied to your comment saying "' || c.body || '"'
                END
            WHEN a.action = 'deleted' THEN
                CASE 
                    WHEN a.entity_type = 'post' THEN
                        CASE 
                            WHEN a.actor_id = a.recipient_id THEN 
                                'You deleted your post "' || 
                                COALESCE(
                                    (SELECT pt.title FROM post_titles pt WHERE pt.post_id = a.entity_id),
                                    'Untitled'
                                ) || '"'
                            ELSE 
                                actor.name || ' deleted their post "' || 
                                COALESCE(
                                    (SELECT pt.title FROM post_titles pt WHERE pt.post_id = a.entity_id),
                                    'Untitled'
                                ) || '"'
                        END
                    WHEN a.entity_type = 'comment' THEN
                        CASE 
                            WHEN a.actor_id = a.recipient_id THEN 'You deleted your comment'
                            ELSE actor.name || ' deleted their comment on your post'
                        END
                END
        END,
        a.entity_type,
        a.entity_id,
        COALESCE(c.post_id, p.id, 
            -- For deleted posts, the entity_id is the post id
            CASE WHEN a.entity_type = 'post' AND a.action = 'deleted' THEN a.entity_id ELSE NULL END
        ) as post_id,
        a.action
    FROM community.activities a
    JOIN public.users actor ON actor.id = a.actor_id
    LEFT JOIN community.posts p ON 
        (a.entity_type = 'post' AND a.entity_id = p.id)
    LEFT JOIN community.comments c ON 
        (a.entity_type = 'comment' AND a.entity_id = c.id)
    WHERE a.recipient_id = v_user_id
    ORDER BY a.created_at DESC
    OFFSET start_range LIMIT (end_range - start_range + 1);
END;
$$;

-- Add helpful comments
COMMENT ON FUNCTION community.create_post_deletion_activity IS 'Creates an activity record when a post is deleted';
COMMENT ON FUNCTION community.create_comment_deletion_activity IS 'Creates activity records when a comment is deleted'; alter table "community"."posts" add column "thumbnail_url" text;


CREATE OR REPLACE FUNCTION community.create_post_with_tags(
  p_title TEXT,
  p_content_type TEXT,
  p_body TEXT,
  p_video_url TEXT,
  p_thumbnail_url TEXT, -- New parameter added
  p_user_id TEXT,
  p_tags TEXT[]
) RETURNS UUID 
  SECURITY DEFINER
  AS $$
DECLARE
  v_post_id uuid;
  v_tag_id uuid;
  v_tag TEXT;
BEGIN
  -- Input validation
  IF p_title IS NULL OR p_content_type IS NULL THEN
    RAISE EXCEPTION 'Title and content_type are required fields';
  END IF;

  IF p_content_type NOT IN ('text', 'video') THEN
    RAISE EXCEPTION 'Invalid content_type. Must be either text or video';
  END IF;

  IF p_content_type = 'text' AND p_body IS NULL THEN
    RAISE EXCEPTION 'Body is required for text posts';
  END IF;

  IF p_content_type = 'video' AND p_video_url IS NULL THEN
    RAISE EXCEPTION 'Video URL is required for video posts';
  END IF;

  -- Log the start of the operation
  RAISE LOG 'Creating new post with title: %, content_type: %, user_id: %', p_title, p_content_type, p_user_id;

  -- First create the post
  INSERT INTO community.posts (
    title,
    content_type,
    body,
    video_url,
    thumbnail_url, -- New column added
    user_id,
    is_pinned,
    is_hidden,
    created_at,
    updated_at
  ) VALUES (
    p_title,
    p_content_type,
    p_body,
    p_video_url,
    p_thumbnail_url, -- New parameter included
    p_user_id,
    false,
    false,
    NOW(),
    NULL
  ) RETURNING id INTO v_post_id;

  -- Log successful post creation
  RAISE LOG 'Successfully created post with ID: %', v_post_id;

  -- Then handle each tag
  IF array_length(p_tags, 1) > 0 THEN
    FOREACH v_tag IN ARRAY p_tags
    LOOP
      -- Log tag processing
      RAISE LOG 'Processing tag: %', v_tag;

      -- Try to find existing tag or create new one
      INSERT INTO community.tags (name, created_at)
      VALUES (v_tag, NOW())
      ON CONFLICT (name) 
      DO UPDATE SET name = EXCLUDED.name
      RETURNING id INTO v_tag_id;

      -- Create post_tag connection
      INSERT INTO community.post_tags (post_id, tag_id, created_at)
      VALUES (v_post_id, v_tag_id, NOW());

      -- Log successful tag association
      RAISE LOG 'Associated tag % (ID: %) with post %', v_tag, v_tag_id, v_post_id;
    END LOOP;
  END IF;

  RETURN v_post_id;
EXCEPTION
  WHEN others THEN
    -- Log any errors that occur
    RAISE LOG 'Error in create_post_with_tags: %', SQLERRM;
    RAISE EXCEPTION 'An error occurred while creating the post: %', SQLERRM;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION community.get_filtered_posts(start_range integer, end_range integer, tag_ids uuid[] DEFAULT NULL::uuid[], only_my_posts boolean DEFAULT false, include_pinned boolean DEFAULT true)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'community', 'public'
AS $function$DECLARE
    v_user_id text;
    v_total_count bigint;
    v_result jsonb;
BEGIN
    -- Get authenticated user's ID if only_my_posts is true
    IF only_my_posts THEN
        SELECT u.id INTO v_user_id
        FROM users u
        WHERE u.auth_id = auth.uid();

        IF v_user_id IS NULL THEN
            RAISE EXCEPTION 'User not found';
        END IF;
    END IF;

    -- Get total count first
    WITH base_query AS (
        SELECT DISTINCT p.id
        FROM community.posts p
        LEFT JOIN community.post_tags pt ON pt.post_id = p.id
        WHERE NOT p.is_hidden
        AND (v_user_id IS NULL OR p.user_id = v_user_id)
        AND (
            tag_ids IS NULL 
            OR array_length(tag_ids, 1) IS NULL 
            OR pt.tag_id = ANY(tag_ids)
        )
    )
    SELECT COUNT(*) INTO v_total_count FROM base_query;

    -- Get posts data and return as single JSON object
    WITH filtered_posts AS (
        SELECT DISTINCT p.*
        FROM community.posts p
        LEFT JOIN community.post_tags pt ON pt.post_id = p.id
        WHERE NOT p.is_hidden
        AND (CASE WHEN only_my_posts THEN p.user_id = v_user_id ELSE true END)
        AND (include_pinned OR NOT p.is_pinned)
        AND (
            tag_ids IS NULL 
            OR array_length(tag_ids, 1) IS NULL 
            OR pt.tag_id = ANY(tag_ids)
        )
        ORDER BY p.is_pinned DESC, p.created_at DESC
        OFFSET start_range LIMIT (end_range - start_range + 1)
    ),
    post_data AS (
        SELECT 
            p.id,
            p.user_id,
            p.title,
            p.content_type,
            p.body,
            p.video_url,
            p.thumbnail_url,
            p.is_pinned,
            p.is_hidden,
            p.is_flagged_by_llm,
            p.view_count,
            p.created_at,
            p.updated_at,
            (
                SELECT jsonb_agg(
                    jsonb_build_object(
                        'tag', jsonb_build_object(
                            'id', t.id,
                            'name', t.name,
                            'type', t.type,
                            'color', t.color
                        )
                    )
                )
                FROM community.post_tags pt
                JOIN community.tags t ON t.id = pt.tag_id
                WHERE pt.post_id = p.id
            ) as post_tags,
            (
                SELECT jsonb_agg(
                    jsonb_build_object(
                        'emoji', r.emoji,
                        'user_id', r.user_id,
                        'post_id', r.post_id
                    )
                )
                FROM community.reactions r
                WHERE r.post_id = p.id
            ) as reactions,
            (
                SELECT COUNT(*)
                FROM community.comments c
                WHERE c.post_id = p.id
            ) as comments_count
        FROM filtered_posts p
    )
    SELECT jsonb_build_object(
        'data', COALESCE(jsonb_agg(to_jsonb(post_data.*)), '[]'::jsonb),
        'total_count', v_total_count
    ) INTO v_result
    FROM post_data;

    RETURN v_result;
END;$function$
;


drop function if exists "community"."create_post_with_tags"(p_title text, p_content_type text, p_body text, p_video_url text, p_user_id text, p_tags text[]);

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION community.delete_post(post_id uuid)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'community', 'public'
AS $function$DECLARE
    v_auth_id uuid;
    v_user_id text;
    v_post_user_id text;
    v_is_admin boolean;
BEGIN
    -- Get the auth_id of the authenticated user
    v_auth_id := auth.uid();
    
    -- Check if user is authenticated
    IF v_auth_id IS NULL THEN
        RAISE EXCEPTION 'Authentication required';
    END IF;

    -- First check if the user is an admin (regardless of being in public.users)
    SELECT EXISTS(SELECT 1 FROM public.admins a WHERE a.auth_id = v_auth_id) 
    INTO v_is_admin;

    -- If user is an admin, they can proceed without further user checks
    IF NOT v_is_admin THEN
        -- Non-admin users must be in the public.users table
        SELECT u.id
        INTO v_user_id
        FROM public.users u
        WHERE u.auth_id = v_auth_id;
        
        -- If not in public.users, raise an exception
        IF v_user_id IS NULL THEN
            RAISE EXCEPTION 'User profile not found. Auth ID: %', v_auth_id;
        END IF;
    END IF;

    -- Get the post's user_id
    SELECT user_id INTO v_post_user_id
    FROM community.posts
    WHERE id = post_id;

    -- Check if post exists
    IF v_post_user_id IS NULL THEN
        RAISE EXCEPTION 'Post not found';
    END IF;

    -- Admin users can delete any post
    -- Non-admin users can only delete their own posts
    IF NOT v_is_admin AND v_post_user_id != v_user_id THEN
        RAISE EXCEPTION 'Only the post owner or admin can delete the post';
    END IF;

    -- Delete all reactions for the post
    DELETE FROM community.reactions r
    WHERE r.post_id = delete_post.post_id;

    -- Delete all post tags
    DELETE FROM community.post_tags pt
    WHERE pt.post_id = delete_post.post_id;

    -- Delete all reported posts entries
    DELETE FROM community.reported_posts rp
    WHERE rp.post_id = delete_post.post_id;

    -- Delete all comments and their replies using recursive CTE
    WITH RECURSIVE comment_tree AS (
        -- Base case: get all direct comments for the post
        SELECT c.id
        FROM community.comments c
        WHERE c.post_id = delete_post.post_id
        
        UNION ALL
        
        -- Recursive case: get all replies to comments
        SELECT c.id
        FROM community.comments c
        INNER JOIN comment_tree ct ON c.parent_comment_id = ct.id
    )
    DELETE FROM community.comments c
    WHERE c.id IN (SELECT id FROM comment_tree)
    OR c.post_id = delete_post.post_id;

    -- Log additional information about who deleted the post
    INSERT INTO community.deleted_posts_log (
        id, 
        user_id, 
        title, 
        metadata,
        deleted_by_user_id,
        deleted_by_admin
    )
    SELECT 
        p.id,
        p.user_id,
        p.title,
        jsonb_build_object(
            'content_type', p.content_type,
            'view_count', p.view_count,
            'is_pinned', p.is_pinned,
            'is_hidden', p.is_hidden,
            'is_flagged_by_llm', p.is_flagged_by_llm,
            'deleted_by', v_user_id,
            'was_admin_deletion', v_is_admin
        ),
        v_user_id,
        v_is_admin
    FROM community.posts p
    WHERE p.id = delete_post.post_id;

    -- Finally delete the post itself
    DELETE FROM community.posts p
    WHERE p.id = delete_post.post_id;

    RETURN true;
END;$function$
;


set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.get_user_id()
 RETURNS text
 LANGUAGE plpgsql
AS $function$
BEGIN
  RETURN (SELECT id FROM users WHERE auth_id = auth.uid());
END;
$function$
;


drop policy "Users can see their own activities" on "community"."activities";

drop policy "comments" on "community"."comments";

drop policy "Only admins can view deleted posts log" on "community"."deleted_posts_log";

drop policy "post_tags" on "community"."post_tags";

drop policy "Posts" on "community"."posts";

drop policy "reactions" on "community"."reactions";

drop policy "reported_posts" on "community"."reported_posts";

drop policy "tags" on "community"."tags";

create policy "Users can set read for own activity"
on "community"."activities"
as permissive
for update
to public
using ((recipient_id = ( SELECT get_user_id() AS get_user_id)))
with check ((recipient_id = ( SELECT get_user_id() AS get_user_id)));


create policy "Users can view own activity"
on "community"."activities"
as permissive
for select
to public
using ((recipient_id = ( SELECT get_user_id() AS get_user_id)));


create policy "Public select"
on "community"."comments"
as permissive
for select
to public
using (true);


create policy "Users can create for self"
on "community"."comments"
as permissive
for insert
to public
with check ((user_id = ( SELECT get_user_id() AS get_user_id)));


create policy "Admin only"
on "community"."deleted_posts_log"
as permissive
for all
to authenticated
using (admin_check());


create policy "Public select"
on "community"."post_tags"
as permissive
for select
to public
using (true);


create policy "Public select"
on "community"."posts"
as permissive
for select
to public
using (true);


create policy "Public select"
on "community"."reactions"
as permissive
for select
to public
using (true);


create policy "Users can react for self"
on "community"."reactions"
as permissive
for insert
to public
with check ((user_id = ( SELECT get_user_id() AS get_user_id)));


create policy "Admin all"
on "community"."reported_posts"
as permissive
for all
to public
using (( SELECT admin_check() AS admin_check));


create policy "Users can insert for self"
on "community"."reported_posts"
as permissive
for insert
to public
with check ((user_id = ( SELECT get_user_id() AS get_user_id)));


create policy "Users can select for self"
on "community"."reported_posts"
as permissive
for select
to public
using ((user_id = ( SELECT get_user_id() AS get_user_id)));


create policy "Admin all"
on "community"."tags"
as permissive
for all
to public
using (( SELECT admin_check() AS admin_check));


create policy "Public select"
on "community"."tags"
as permissive
for select
to public
using (true);

create table "community"."profiles" (
    "id" text not null,
    "name" text not null,
    "emoji" text not null
);


alter table "community"."profiles" enable row level security;

CREATE UNIQUE INDEX profiles_pkey ON community.profiles USING btree (id);

alter table "community"."profiles" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";

alter table "community"."profiles" add constraint "profiles_id_fkey" FOREIGN KEY (id) REFERENCES users(id) ON UPDATE CASCADE not valid;

alter table "community"."profiles" validate constraint "profiles_id_fkey";

set check_function_bodies = off;

create policy "Public select"
on "community"."profiles"
as permissive
for select
to public
using (true);



drop trigger if exists "after_comment_created" on "community"."comments";

drop trigger if exists "after_post_created" on "community"."posts";

drop function if exists "community"."get_filtered_posts"(start_range integer, end_range integer, tag_ids uuid[], only_my_posts boolean);

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION community.create_profile()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$BEGIN
  -- Check if a profile with the user_id already exists in community.profiles
  IF NOT EXISTS (SELECT 1 FROM community.profiles WHERE id = NEW.user_id) THEN
    -- If no profile exists, insert a new one using data from public.users
    INSERT INTO community.profiles (id, name, emoji)
    SELECT id, name, emoji
    FROM public.users
    WHERE id = NEW.user_id;
  END IF;
  
  RETURN NEW;
END;$function$
;

grant delete on table "community"."activities" to "anon";

grant insert on table "community"."activities" to "anon";

grant references on table "community"."activities" to "anon";

grant trigger on table "community"."activities" to "anon";

grant truncate on table "community"."activities" to "anon";

grant update on table "community"."activities" to "anon";

grant delete on table "community"."activities" to "authenticated";

grant insert on table "community"."activities" to "authenticated";

grant references on table "community"."activities" to "authenticated";

grant trigger on table "community"."activities" to "authenticated";

grant truncate on table "community"."activities" to "authenticated";

grant delete on table "community"."activities" to "service_role";

grant insert on table "community"."activities" to "service_role";

grant references on table "community"."activities" to "service_role";

grant select on table "community"."activities" to "service_role";

grant trigger on table "community"."activities" to "service_role";

grant truncate on table "community"."activities" to "service_role";

grant update on table "community"."activities" to "service_role";

grant delete on table "community"."comments" to "service_role";

grant insert on table "community"."comments" to "service_role";

grant references on table "community"."comments" to "service_role";

grant select on table "community"."comments" to "service_role";

grant trigger on table "community"."comments" to "service_role";

grant truncate on table "community"."comments" to "service_role";

grant update on table "community"."comments" to "service_role";

grant delete on table "community"."deleted_posts_log" to "anon";

grant insert on table "community"."deleted_posts_log" to "anon";

grant references on table "community"."deleted_posts_log" to "anon";

grant select on table "community"."deleted_posts_log" to "anon";

grant trigger on table "community"."deleted_posts_log" to "anon";

grant truncate on table "community"."deleted_posts_log" to "anon";

grant update on table "community"."deleted_posts_log" to "anon";

grant delete on table "community"."deleted_posts_log" to "authenticated";

grant insert on table "community"."deleted_posts_log" to "authenticated";

grant references on table "community"."deleted_posts_log" to "authenticated";

grant select on table "community"."deleted_posts_log" to "authenticated";

grant trigger on table "community"."deleted_posts_log" to "authenticated";

grant truncate on table "community"."deleted_posts_log" to "authenticated";

grant update on table "community"."deleted_posts_log" to "authenticated";

grant delete on table "community"."deleted_posts_log" to "service_role";

grant insert on table "community"."deleted_posts_log" to "service_role";

grant references on table "community"."deleted_posts_log" to "service_role";

grant select on table "community"."deleted_posts_log" to "service_role";

grant trigger on table "community"."deleted_posts_log" to "service_role";

grant truncate on table "community"."deleted_posts_log" to "service_role";

grant update on table "community"."deleted_posts_log" to "service_role";

grant delete on table "community"."post_tags" to "service_role";

grant insert on table "community"."post_tags" to "service_role";

grant references on table "community"."post_tags" to "service_role";

grant select on table "community"."post_tags" to "service_role";

grant trigger on table "community"."post_tags" to "service_role";

grant truncate on table "community"."post_tags" to "service_role";

grant update on table "community"."post_tags" to "service_role";

grant delete on table "community"."posts" to "service_role";

grant insert on table "community"."posts" to "service_role";

grant references on table "community"."posts" to "service_role";

grant select on table "community"."posts" to "service_role";

grant trigger on table "community"."posts" to "service_role";

grant truncate on table "community"."posts" to "service_role";

grant update on table "community"."posts" to "service_role";

grant delete on table "community"."profiles" to "anon";

grant insert on table "community"."profiles" to "anon";

grant references on table "community"."profiles" to "anon";

grant select on table "community"."profiles" to "anon";

grant trigger on table "community"."profiles" to "anon";

grant truncate on table "community"."profiles" to "anon";

grant update on table "community"."profiles" to "anon";

grant delete on table "community"."profiles" to "authenticated";

grant insert on table "community"."profiles" to "authenticated";

grant references on table "community"."profiles" to "authenticated";

grant select on table "community"."profiles" to "authenticated";

grant trigger on table "community"."profiles" to "authenticated";

grant truncate on table "community"."profiles" to "authenticated";

grant update on table "community"."profiles" to "authenticated";

grant delete on table "community"."profiles" to "service_role";

grant insert on table "community"."profiles" to "service_role";

grant references on table "community"."profiles" to "service_role";

grant select on table "community"."profiles" to "service_role";

grant trigger on table "community"."profiles" to "service_role";

grant truncate on table "community"."profiles" to "service_role";

grant update on table "community"."profiles" to "service_role";

grant delete on table "community"."reactions" to "service_role";

grant insert on table "community"."reactions" to "service_role";

grant references on table "community"."reactions" to "service_role";

grant select on table "community"."reactions" to "service_role";

grant trigger on table "community"."reactions" to "service_role";

grant truncate on table "community"."reactions" to "service_role";

grant update on table "community"."reactions" to "service_role";

grant delete on table "community"."reported_posts" to "service_role";

grant insert on table "community"."reported_posts" to "service_role";

grant references on table "community"."reported_posts" to "service_role";

grant select on table "community"."reported_posts" to "service_role";

grant trigger on table "community"."reported_posts" to "service_role";

grant truncate on table "community"."reported_posts" to "service_role";

grant update on table "community"."reported_posts" to "service_role";

grant delete on table "community"."tags" to "service_role";

grant insert on table "community"."tags" to "service_role";

grant references on table "community"."tags" to "service_role";

grant select on table "community"."tags" to "service_role";

grant trigger on table "community"."tags" to "service_role";

grant truncate on table "community"."tags" to "service_role";

grant update on table "community"."tags" to "service_role";

CREATE TRIGGER after_comment_created_activity AFTER INSERT ON community.comments FOR EACH ROW EXECUTE FUNCTION community.create_comment_activity();

CREATE TRIGGER after_comment_created_profile AFTER INSERT ON community.comments FOR EACH ROW EXECUTE FUNCTION community.create_profile();

CREATE TRIGGER after_post_created_activity AFTER INSERT ON community.posts FOR EACH ROW EXECUTE FUNCTION community.create_post_activity();

CREATE TRIGGER after_post_created_profile AFTER INSERT ON community.posts FOR EACH ROW EXECUTE FUNCTION community.create_profile();


set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.community_update_profile()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$BEGIN
  -- Check if a profile with the user id exists in community.profiles
  IF EXISTS (SELECT 1 FROM community.profiles WHERE id = NEW.id) THEN
    -- If profile exists, update the name and emoji
    UPDATE community.profiles
    SET 
      name = NEW.name,
      emoji = NEW.emoji
    WHERE id = NEW.id;
  END IF;
  
  RETURN NEW;
END;$function$
;

CREATE TRIGGER after_user_update AFTER UPDATE ON public.users FOR EACH ROW EXECUTE FUNCTION community_update_profile();


drop policy "Public policy" on "public"."users";


CREATE POLICY "Give users access to own folder 1ajt695_1" ON storage.objects FOR INSERT TO public WITH CHECK (bucket_id = 'community' AND (select get_user_id()) = (storage.foldername(name))[1]);

CREATE POLICY "Give users access to own folder 1ajt695_0" ON storage.objects FOR SELECT TO public USING (bucket_id = 'community' AND (select get_user_id()) = (storage.foldername(name))[1]);

CREATE POLICY "Give users access to own folder 1ajt695_2" ON storage.objects FOR UPDATE TO public USING (bucket_id = 'community' AND (select get_user_id()) = (storage.foldername(name))[1]);

CREATE POLICY "Give users access to own folder 1ajt695_3" ON storage.objects FOR DELETE TO public USING (bucket_id = 'community' AND (select get_user_id()) = (storage.foldername(name))[1]);
create policy "Users can edit own posts"
on "community"."posts"
as permissive
for update
to public
using ((user_id = ( SELECT get_user_id() AS get_user_id)))
with check ((user_id = ( SELECT get_user_id() AS get_user_id)));



drop trigger if exists "before_comment_deleted" on "community"."comments";

drop trigger if exists "before_post_deleted" on "community"."posts";

drop function if exists "community"."create_comment_deletion_activity"();

drop function if exists "community"."create_post_deletion_activity"();

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION community.create_comment_activity()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$DECLARE
    v_post_author_id text;
    v_parent_comment_author_id text;
BEGIN
    -- Don't create activity if the actor would be the recipient
    IF NEW.parent_comment_id IS NULL THEN
        -- Direct comment on post
        SELECT user_id INTO v_post_author_id
        FROM community.posts
        WHERE id = NEW.post_id;

        -- Only create activity if the commenter is not the post author
        IF NEW.user_id <> v_post_author_id THEN
            INSERT INTO community.activities (
                actor_id,
                recipient_id,
                entity_type,
                entity_id,
                action
            ) VALUES (
                NEW.user_id,
                v_post_author_id,
                'comment'::community.activity_entity_type,
                NEW.id,
                'commented'::community.activity_action
            );
        END IF;
    ELSE
        -- Reply to comment
        SELECT user_id INTO v_parent_comment_author_id
        FROM community.comments
        WHERE id = NEW.parent_comment_id;

        -- Only create activity if the replier is not the parent comment author
        IF NEW.user_id <> v_parent_comment_author_id THEN
            INSERT INTO community.activities (
                actor_id,
                recipient_id,
                entity_type,
                entity_id,
                action
            ) VALUES (
                NEW.user_id,
                v_parent_comment_author_id,
                'comment'::community.activity_entity_type,
                NEW.id,
                'replied'::community.activity_action
            );
        END IF;
    END IF;

    RETURN NEW;
EXCEPTION
    WHEN OTHERS THEN
        -- Log error but don't prevent comment creation
        RAISE WARNING 'Error creating activity for comment %: %', NEW.id, SQLERRM;
        RETURN NEW;
END;$function$
;

CREATE OR REPLACE FUNCTION community.delete_post(post_id uuid)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'community', 'public'
AS $function$DECLARE
    v_auth_id uuid;
    v_user_id text;
    v_post_user_id text;
    v_is_admin boolean;
BEGIN
    -- Get the auth_id of the authenticated user
    v_auth_id := auth.uid();
    
    -- Check if user is authenticated
    IF v_auth_id IS NULL THEN
        RAISE EXCEPTION 'Authentication required';
    END IF;

    -- First check if the user is an admin (regardless of being in public.users)
    SELECT EXISTS(SELECT 1 FROM public.admins a WHERE a.auth_id = v_auth_id) 
    INTO v_is_admin;

    -- If user is an admin, they can proceed without further user checks
    IF NOT v_is_admin THEN
        -- Non-admin users must be in the public.users table
        SELECT u.id
        INTO v_user_id
        FROM public.users u
        WHERE u.auth_id = v_auth_id;
        
        -- If not in public.users, raise an exception
        IF v_user_id IS NULL THEN
            RAISE EXCEPTION 'User profile not found. Auth ID: %', v_auth_id;
        END IF;
    END IF;

    -- Get the post's user_id
    SELECT user_id INTO v_post_user_id
    FROM community.posts
    WHERE id = post_id;

    -- Check if post exists
    IF v_post_user_id IS NULL THEN
        RAISE EXCEPTION 'Post not found';
    END IF;

    -- Admin users can delete any post
    -- Non-admin users can only delete their own posts
    IF NOT v_is_admin AND v_post_user_id != v_user_id THEN
        RAISE EXCEPTION 'Only the post owner or admin can delete the post';
    END IF;

    -- Delete all reactions for the post
    DELETE FROM community.reactions r
    WHERE r.post_id = delete_post.post_id;

    -- Delete all post tags
    DELETE FROM community.post_tags pt
    WHERE pt.post_id = delete_post.post_id;

    -- Delete all reported posts entries
    DELETE FROM community.reported_posts rp
    WHERE rp.post_id = delete_post.post_id;

    -- Delete all comments and their replies using recursive CTE
    WITH RECURSIVE comment_tree AS (
        -- Base case: get all direct comments for the post
        SELECT c.id
        FROM community.comments c
        WHERE c.post_id = delete_post.post_id
        
        UNION ALL
        
        -- Recursive case: get all replies to comments
        SELECT c.id
        FROM community.comments c
        INNER JOIN comment_tree ct ON c.parent_comment_id = ct.id
    )
    DELETE FROM community.comments c
    WHERE c.id IN (SELECT id FROM comment_tree)
    OR c.post_id = delete_post.post_id;

    -- Log additional information about who deleted the post
    INSERT INTO community.deleted_posts_log (
        id, 
        user_id, 
        title, 
        metadata,
        deleted_by_user_id,
        deleted_by_admin
    )
    SELECT 
        p.id,
        p.user_id,
        p.title,
        jsonb_build_object(
            'content_type', p.content_type,
            'view_count', p.view_count,
            'is_pinned', p.is_pinned,
            'is_hidden', p.is_hidden,
            'is_flagged_by_llm', p.is_flagged_by_llm,
            'deleted_by', v_user_id,
            'was_admin_deletion', v_is_admin
        ),
        v_user_id,
        v_is_admin
    FROM community.posts p
    WHERE p.id = delete_post.post_id;

    -- Delete activies about post
    DELETE FROM community.activities a
    WHERE a.entity_type = 'post' AND a.entity_id::text = delete_post.post_id::text;


    -- Finally delete the post itself
    DELETE FROM community.posts p
    WHERE p.id = delete_post.post_id;

    RETURN true;
END;$function$
;

CREATE OR REPLACE FUNCTION community.get_activity_feed(start_range integer, end_range integer)
 RETURNS TABLE(id uuid, created_at timestamp with time zone, is_read boolean, message text, entity_type community.activity_entity_type, entity_id uuid, post_id uuid, action community.activity_action)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'community', 'public'
AS $function$DECLARE
    v_user_id text;
BEGIN
    -- Get the authenticated user's ID
    SELECT u.id INTO v_user_id
    FROM public.users u
    WHERE u.auth_id = auth.uid();

    IF v_user_id IS NULL THEN
        RAISE EXCEPTION 'User not found';
    END IF;

    RETURN QUERY
    WITH post_titles AS (
        -- Get titles for existing
        SELECT 
            p.id AS post_id,
            p.title AS title
        FROM community.posts p
    )
    SELECT 
        a.id,
        a.created_at,
        a.is_read,
        CASE 
            -- Created something
            WHEN a.action = 'created' THEN 
                CASE 
                    -- You created post
                    WHEN a.actor_id = a.recipient_id THEN 
                        'You created a new post "' || 
                        COALESCE(
                            (SELECT pt.title FROM post_titles pt WHERE pt.post_id = a.entity_id),
                            'Untitled'
                        ) || '"'
                    -- Someone else created a post
                    ELSE
                        actor.name || ' created a new post "' || 
                        COALESCE(
                            (SELECT pt.title FROM post_titles pt WHERE pt.post_id = a.entity_id),
                            'Untitled'
                        ) || '"'
                END
            WHEN a.action = 'commented' THEN
                CASE 
                    WHEN a.actor_id = a.recipient_id THEN 'You commented on your post saying "' || c.body || '"'
                    ELSE actor.name || ' commented on your post saying "' || c.body || '"'
                END
            WHEN a.action = 'replied' THEN
                CASE 
                    WHEN a.actor_id = a.recipient_id THEN 'You replied to your comment saying "' || c.body || '"'
                    ELSE actor.name || ' replied to your comment saying "' || c.body || '"'
                END
        END,
        a.entity_type,
        a.entity_id,
        COALESCE(c.post_id, p.id) as post_id,
        a.action
    FROM community.activities a
    JOIN public.users actor ON actor.id = a.actor_id
    LEFT JOIN community.posts p ON 
        (a.entity_type = 'post' AND a.entity_id = p.id)
    LEFT JOIN community.comments c ON 
        (a.entity_type = 'comment' AND a.entity_id = c.id)
    WHERE a.recipient_id = v_user_id
    ORDER BY a.created_at DESC
    OFFSET start_range LIMIT (end_range - start_range + 1);
END;$function$
;


